### ISSUE TITLE
korio: assets from commonTest are stored in korio library and in target build apk

### ISSUE THREAD

**Issue by ArtRoman** [korlibs/korge#1065]
Some test files from korio lib is stored in target apk file (debug and release) if I use any of korio library dependency, that takes up to 928 KB of unwanted files (uncompressed).

<img width="408" alt="Снимок экрана 2022-10-24 в 02 16 04" src="https://user-images.githubusercontent.com/1625142/197416478-792dbf9a-23a4-4fdf-8f41-1bbff79741fc.png">

Here are source files: https://github.com/korlibs/korge/tree/main/korio/src/commonTest/resources

They are also available on dev/build machine as uncompressed aar and jetified folder like

`~/.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.korio/korio-android/3.3.0/ef987d8be8e73f060d8986f6de602e5b89ea5976/korio-debug/assets/isotest.iso`

and
`~/.gradle/caches/transforms-3/6adbc6bed511be3ddd28d55180216e07/transformed/jetified-korio-debug/assets/hello.zip`

Workaround is to add to build.gradle, that saves ~100kB in result apk:
```
aaptOptions {
    ignoreAssetsPattern "tresfolder:android200-sqlite.cblite2.zip:compressedHello.zip:hello.zip:isotest.iso:resource.txt:simple1.fla.zip:test.xml"
}
```

**Comment by soywiz** [comment]
Is this problem with korge, or korio alone?

Can you show a simple/empty gradle project reproducing the problem? Within that gradle project which task are you using to generate the apl, that I can run to reproduce the problem?

**Comment by ArtRoman** [comment]
> Is this problem with korge, or korio alone?

I'm using korio only (klock is provided with korio).

Adding korio dependency to android or multiplatform project repoduces issue in empty project:
`implementation "com.soywiz.korlibs.korio:korio:3.3.0"`
Attaching `korio-jvm` doensn't reproduce it.

Here is empty project to repro:
https://github.com/ArtRoman/korioTest
