### ISSUE TITLE
ShaderFilter smooths view's texture

### ISSUE THREAD

**Issue by i-d-c-p** [korlibs/korge#107]
Shader filter smooths texture without taking into account if the view has **_filtering = false_**, it's a headache for pixel art gamedevs. The problem is in the below line of code:

https://github.com/korlibs/korge/blob/e1efe95e30a5d479ae35c7aac581c5149f278a86/korge/src/commonMain/kotlin/com/soywiz/korge/view/filter/ShaderFilter.kt#L94

The solution could be to modify the render method declaration inside **_Filter_** interface to include **_filtering: Boolean_** parameter.

https://github.com/korlibs/korge/blob/e1efe95e30a5d479ae35c7aac581c5149f278a86/korge/src/commonMain/kotlin/com/soywiz/korge/view/filter/Filter.kt#L45-L54

The problem with that approach is that **_View_** class doesn't have a filtering field, only inherited views like _**Text**_ and _**Image**_ (smooth field) have, so the **_renderFiltered(...)_** method inside **_View_** doesn't have a way to know whether or not the inherited class has filtering field. It might be solved creating an interface or **_filtering_** field inside **_View_** class(I came from Java world, maybe with a Kotlin feature you can get a cleaner solution).

**Comment by soywiz** [comment]
Have you tried: https://github.com/korlibs/korge/blob/e1efe95e30a5d479ae35c7aac581c5149f278a86/korge/src/commonMain/kotlin/com/soywiz/korge/view/ScaleView.kt#L10
?

**Comment by i-d-c-p** [comment]
I tried, but it didn't work or I might've not used it in the right way, is the below use right?

```kotlin
override suspend fun Container.sceneInit() {
	var img = Image(getAssetManager().getImage("image-1.png"), smoothing = false)
	var texture = ScaleView(img.width.toInt(), img.height.toInt(), scale = 1.0, filtering = false).apply{
		filter = ColorMatrixFilter(ColorMatrixFilter.GRAYSCALE_MATRIX)
	}
	texture += img
	this += texture
}
```

I think the filter is being rendered with `filtering = true` regardless `renderInternal` implementations. Even if we were allowed to override `renderFiltered` method, we wouldn't be able to fix anything since the `ShaderFilter` class has filtering hardcoded to true.

**Comment by i-d-c-p** [comment]
Let me know if you need some help because of time availability and your approach for a solution. I'd be very glad to contribute with this project.

**Comment by soywiz** [comment]
@i-d-c-p contributions are always welcome! If you want to do a proposal yourself, go ahead :)
