### ISSUE TITLE
Support ray-based collision testing inside tilemaps

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge#1088]
For tiled maps and for ldtk maps: https://github.com/korlibs/korge-ldtk

This can be used to create generic sensors and enable other stuff:

https://info.sonicretro.org/SPG:Solid_Tiles#Sensors

**Comment by jobe-m** [comment]
This sounds interesting:)

**Comment by soywiz** [comment]
@jobe-m 

Done: https://www.youtube.com/watch?v=nbIoJ3f6zrU
