### ISSUE TITLE
FR: Drag and drop functionality

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1117]
Similar to this functionality:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/5054996/202390496-a06555b0-acb7-4165-857c-7e3ab7e19e54.png">

Example: https://imgbb.com/upload

Basically a user can drag and drop a file from their file system into the website area and the website is able to somehow detect the file that was dropped.

api idea:

onFileDrop { file: VfsFile ->
   // do stuff
}

**Comment by soywiz** [comment]
It is already available:

https://github.com/korlibs/korge-swf/blob/0ddc1397f5eca6746fe3a768339a4cdb3b8e57fb/example/src/commonMain/kotlin/MainSWF.kt#L98-L104

In the SWF sample, you can drop a `.swf` file there and it will be loaded

**Comment by Kietyo** [comment]
oh! nice!

**Comment by soywiz** [comment]
In any case, it is not easy to discover it by autocompletion. Maybe we can create an extension function similar to mouse or keys that internally registers that event locally. So people can type `this.drop` + `<space>` and discover that functionality
