### ISSUE TITLE
Incorrect root.width and root.height in Korge block

### ISSUE THREAD

**Issue by RezMike** [korlibs/korge#112]
When I comment the first line, the root.width is much greater than the actual width of the window, I need to use root.height to get the width value. But with the first line, the root.width and root.height are correct.

![image](https://user-images.githubusercontent.com/19624167/77221023-61d7c680-6b78-11ea-9e8b-f21ff5e59d1f.png)

**Comment by soywiz** [comment]
```
suspend fun main() = Korge(width = 1280, height = 720, bgcolor = Colors["#2b2b2b"]) {
	println(root.width)
	delay(100.milliseconds)
	println(root.width)
}
```

-->

```
640.0
1280.0
```
