### ISSUE TITLE
Key Recognition: Alt, Shift, Ctrl

### ISSUE THREAD

**Issue by Maddin-M** [korlibs/korge#1168]
Hello, I recently noticed a key not working when running in native. And after some investigation i have found these problems:

When running in JVM:
- when pressing the right side ALT, SHIFT or CTRL key, KoreGE recognizes them as left side keys although mappings for RIGHT_ALT etc. exist

When running in Native:
- ALT, SHIFT and CRTL are seen as unknown

Tested in KorGE 3.4.0 on Windows 11 by simply printing the key:
```
keys {
    down {
        println("${it.key}")
    }
}
```

**Comment by soywiz** [comment]
I guess it is not possible to distinguish between them (LEFT and RIGHT) in most targets. So maybe we should keep only one (ALT) and deprecate (ALT_LEFT, ALT_RIGHT) variants.

The unknown ones should be fixed
