### ISSUE TITLE
FSprite doesn't respect global position

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korge#1176]
Hello,
it seems FSprite recently stopped to respect global position of views. 

**What do I mean and how to reproduce:**
In MainBunnymark.kt you need to replace `addChild(bunny.createView(...))` with 
```kotlin
val view = bunnys.createView(wabbitTexture0, wabbitTexture1)
view.xy(300, 300)
addChild(view)
```

**Culprit commit:** ecef73260aa6943cdeac66eccb011566b65ecad1
Probably, caused by changes in AGQueueProcessorOpenGL, but I wasn't able to nail it.

**Comment by soywiz** [comment]
Can't reproduce anymore, so I guess this was fixed at some point
