### ISSUE TITLE
Idea: Add CameraContainer follow method, that doesn't tween

### ISSUE THREAD

**Issue by Maddin-M** [korlibs/korge#1188]
If you run `./gradlew :samples:collision2d-roguelike:runJvm` and move the red square around, I would expect that the camera always stays exactly on the square, but it drags behind due to it having some amount of tween set.

I would suggest to have a followTween() method that works as is does right now. And a new follow() method that moves the camera instantly to the following view.

**Comment by soywiz** [comment]
We can create a kproject with camera extensions. For now I have done some camera experiments in the starter-kit-platformer.

* https://github.com/korlibs/korge-starter-kit-platformer/blob/b679e94b595c77ba33d580e5bba4d146e538b971/src/commonMain/kotlin/main.kt#L257-L284
* https://github.com/korlibs/korge-starter-kit-platformer/blob/b679e94b595c77ba33d580e5bba4d146e538b971/src/commonMain/kotlin/main.kt#L226-L237

**Comment by Maddin-M** [comment]
Yes, the new `Camera` class does essentially fix this issue. Using this cameras `tweenTo` method moves it without delay and `setTo` sets it instantly, all is as expected. LGTM
I hope it stays this way, as it's marked as Experimental for now 😄

**Comment by soywiz** [comment]
The idea is to keep that interface. I made it as simple as possible. Still to make it useful some extensions are needed. But until battle tested, I'm not sure what would be the right interface to provide, so let's use kproject, experiment and evolve it with feedback.
