### ISSUE TITLE
Playing sounds at volumes other than 1.0 doesn't play them after building Windows executable

### ISSUE THREAD

**Issue by Maddin-M** [korlibs/korge#1189]
How to reproduce:

- checkout `minesweeper` from korge-samples
- In `Process.kt`, line 112 change:
```
sound.play(views.coroutineContext, times)
```
to
```
sound.play(views.coroutineContext, PlaybackParameters(times, volume = 0.5)) // or anything other than 1.0
```
- run `packageMingwX64AppRELEASE` (or DEBUG)
- run the generated exe and click somewhere on the minesweeper field
- no sounds are played now

**Comment by soywiz** [comment]
Not applicable anymore
