### ISSUE TITLE
Collision detection for circles works improperly (?) with non-default anchor

### ISSUE THREAD

**Issue by cra** [korlibs/korge#1190]
Hi!

Thanks for such a nice library it brings me real joy to learn kotlin and korge. However when I was writing a small "particles in the box" example based on the hello world I encountered a weird collision behavior which I think I can demonstrate on this screenshot:
![image](https://user-images.githubusercontent.com/408698/211003870-b51bb488-2150-47db-866f-fb63b2d470b5.png)

The scene uses 4 big circles with different anchors and multiple circles on a grid with collision detection enabled. Colliding circles turn red. You can see code for this here: https://github.com/cra/koding-in-kotlin/commit/1ba893a0efb9fc3bbaa81376650012e89740eceb

Here's the main part  of that commit:
```kotlin
    override suspend fun SContainer.sceneMain() {
        val L = 75.0
        val R = 405.0
        val B = 395.0
        val T = 80.0
        val r = 100.0
        val bigTL = circle(r, Colors.TRANSPARENT_BLACK, Colors.WHITE, 5.0) {x = L; y = T}
        val bigTR = circle(r, Colors.TRANSPARENT_BLACK, Colors.WHITE, 5.0) {x = R; y = T}
        val bigBL = circle(r, Colors.TRANSPARENT_BLACK, Colors.WHITE, 5.0) {x = L; y = B}
        val bigBR = circle(r, Colors.TRANSPARENT_BLACK, Colors.WHITE, 5.0) {x = R+100; y = B+100}
        bigTR.anchor(0.5, 0.5)
        bigBL.anchor(0.3, 0.3)
        bigBR.anchor(1.0, 1.0)

        textView.text = """Anchors:
TL: ${bigTL.anchorX}, ${bigTL.anchorY}    TR: ${bigTR.anchorX}, ${bigTR.anchorY}
BL: ${bigBL.anchorX}, ${bigBL.anchorY}    BR: ${bigBR.anchorX}, ${bigBR.anchorY}
Small red colored circles are colliding with big ones 
"""

        (10..700 step 12).forEach { xx ->
            (0..600 step 12).forEach { yy ->
                circle(
                    3.0,
                    Colors.GREEN
                ){
                    x = xx.toDouble()
                    y = yy.toDouble()
                }.onCollision (filter = { it is Circle && it.radius > 15.0 }, kind = CollisionKind.SHAPE){
                    (this as Circle).fill = Colors.RED
                }
            }
        }

    }
```

What I don't understand is that why the circles move but the collisions don't.

P.s. You can see us struggling figuring it out here https://www.youtube.com/watch?v=wSl34Z2rhac

**Comment by SerVB** [comment]
Related, but old and considered fixed, bug: https://github.com/korlibs-archive/korma/issues/32.

Well, at least it fixed the collisions in my game: https://github.com/SerVB/korge-zombie-bird/commit/80dce22a84bda386a0435d8a4ad01188f5b1c996.

It's interesting that some variation of it is still presented.

**Comment by cra** [comment]
I realized I used old korge version (3.0.0). Once I bumped it to 3.4.0 it works fine
![image](https://user-images.githubusercontent.com/408698/212306443-f701b1a9-000d-4875-be7e-e46fa1b44935.png)

Maybe hello-world should be updated to use more recent korge version? 
https://github.com/korlibs/korge-hello-world/blob/main/gradle/libs.versions.toml

**Comment by soywiz** [comment]
Done
