### ISSUE TITLE
BitmapFont can't display chinese characters

### ISSUE THREAD

**Issue by stormcenter** [korlibs/korge#1192]
I write those code 
`
val font3 = resourcesVfs["fzltxh.ttf"].readTtfFont();
val font2 = BitmapFont(
font3, 64
)
text("你好,2023", font = font2, textSize = 64.0, alignment = TextAlignment.BASELINE_LEFT).position(200,100)
text("你好,2023", font = font3, textSize = 64.0, alignment = TextAlignment.BASELINE_LEFT).position(200, 200) `

the first line font2 can't display chinese characters, only see  2023.
the second line works fine.

<img width="512" alt="infoflow 2023-01-08 16-54-23" src="https://user-images.githubusercontent.com/3783795/211188034-587659e4-3c6e-46ca-a6f2-296e3a77f2ca.png">

It's a bug or I have messing some configurations ?

**Comment by soywiz** [comment]
When creating a BitmapFont on the fly based on other font you have to provide the characters you want to include in the atlas, in an extra parameter. By default it only includes basic latin characters. 

IIRC in the latest main branch there is an option to lazily compute characters and include atlases as required for BitmapFonts which would help Chinese and Japanese a lot, but it will be released in KorGE 4.0

**Comment by stormcenter** [comment]
when will KorGE 4.0 release ? 

and 

if I write a new CharacterSet Like CharacterSet.Chinese that include all Chinese characters. 

`val font2 = BitmapFont(
		font3, 64 ,
		CharacterSet.Chinese
	)`
Is that can be resolve this issue ?
