### ISSUE TITLE
Text parses to fractional version for some reason.

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1200]
So I'm using the Atkinson Bold:

https://fonts.google.com/specimen/Atkinson+Hyperlegible/glyphs

Here's how I use it:

```
            val speedText = text("41/41", textSize = textSize, color = Colors.BLACK, font = GlobalResources.FONT_ATKINSON_BOLD) {
                centerOn(cooldownIcon)
                alignTopToBottomOf(cooldownIcon, 5.0)
            }
```

For some reason, this parses into the fraction 1/4 version when rendered:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/5054996/213897174-54c62f4f-1aae-4787-ab9c-b14e3fe0b099.png">

But I do not want the fractional version, I want it to look like "41/41" not "4¼1".

I also tried specifying the unicode for the forward slash directly, but that didn't seem to work either:

```
            val speedText = text("41\u002F41", textSize = textSize, color = Colors.BLACK, font = GlobalResources.FONT_ATKINSON_BOLD) {
                centerOn(cooldownIcon)
                alignTopToBottomOf(cooldownIcon, 5.0)
            }
```

Is there a way to make it so that it renders "41/41" rather than "4¼1"?

**Comment by soywiz** [comment]
This seems to be related to ligatures. Ligatures were implemented to support emoji variants mainly, but also some fonts support this kind of thing.

You can try to change this if to be false:
https://github.com/korlibs/korge/blob/ccbb98ecdd51acb60c0eb1f8b2557f07e7b30d84/korim/src/commonMain/kotlin/com/soywiz/korim/font/TtfFont.kt#L1765

And see if it changes the behaviour, and that's likely to happen.

If that's the case I see two options:
* Either create a boolean as part of the font to enable/disable ligatures globally for that font
* Pass a boolean enabling/disabling ligatures to that function and propagate it to callers recursively until we get to the `Text : View` class where we can create a boolean for enabling disabling them

What do you think?

**Comment by Kietyo** [comment]
Thanks. I would prefer the first option since it seems the easiest to implement.

**Comment by soywiz** [comment]
Okay. Do you want to implement it yourself or should I add this task to the backlog?

**Comment by Kietyo** [comment]
I can try implementing it myself.

**Comment by soywiz** [comment]
This was fixed already
