### ISSUE TITLE
No audio (no error either) while playing a mp3 file in android

### ISSUE THREAD

**Issue by pablocaviglia** [korlibs/korge#124]
Trying to play the attached mp3 files in korge's project.
The way to play the files is:

resourcesVfs[type.resourceName].readSound("filename.mp3").play()

[resources.zip](https://github.com/korlibs/korge/files/4531938/resources.zip)

**Comment by soywiz** [comment]
Does this happen with the latest version?

**Comment by pablocaviglia** [comment]
With latest version getting this:

resourcesVfs["target_go_hit.mp3"].readSound(false).play()


2020-04-30 12:39:40.899 27332-27370/com.senaptec.senxtoolpt
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.senaptec.senxtoolpt, PID: 27332
    kotlin.KotlinNullPointerException
        at
com.soywiz.korau.sound.AndroidNativeSoundProvider.createAudioStream(AndroidNativeSoundProvider.kt:27)
        at
com.soywiz.korau.sound.NativeSoundProvider$createStreamingSound$3.play(NativeSound.kt:74)
        at
com.soywiz.korau.sound.NativeSound.play$default(NativeSound.kt:249)
        at
com.senaptec.toolframework.tool.GenericScene$hitTarget$1.invokeSuspend(GenericScene.kt:371)
        at
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by soywiz** [comment]
End the end it was related to a custom entrypoint without calling withAndroidContext.
I have changed the null pointer exception to something more descriptive: https://github.com/korlibs/korau/commit/981807423cbee87ae8f0a061dd63caa2cb4a40ea
