### ISSUE TITLE
Crash on Safari when running js target

### ISSUE THREAD

**Issue by emign** [korlibs/korge#128]
Newer versions of korge produce JS targets which do crash on safari. The message is:
"A problem repeatedly ocurred with this webpage"
You can only reload it and it crashes again

test here:
https://rezmike.github.io/2048/

Same sites work with firefox and chrome.

<img width="607" alt="2048" src="https://user-images.githubusercontent.com/5278352/80680408-fcec8600-8abe-11ea-9419-ece3da79ad80.png">

**Comment by soywiz** [comment]
Happens here too: https://emig.me/engineEmi/samples/flappyClone/index.html

**Comment by emign** [comment]
Funny thin I just noticed. When reloading the respective pages with the devtools open in Safari, the webpage sometimes loads. maybe its a race condition of some sort.

![Jun-24-2020 09-06-00](https://user-images.githubusercontent.com/5278352/85512281-021b0c80-b5fa-11ea-8946-20ba82ff9141.gif)

**Comment by emign** [comment]
Some progress investigating:

**no crash in safari** but "webpage was reloaded due to problems:"
```
suspend fun main() = Korge(width = 512, height = 512) {
	circle ()
}
```

**no crash in safari** but "webpage was reloaded due to problems:"
```
suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors.YELLOW) {
	circle ()
}
```

**no crash in safari** but "webpage was reloaded due to problems:"
```
suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors.YELLOW) {
	circle ()
}
```

**crash in safari**
```
suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors.TRANSPARENT_BLACK) {
	circle ()
}
```

**Comment by soywiz** [comment]
First time I tried, it crashed. Then tried again and all the next times it worked :/. Maybe it will work with the new backend with Kotlin 1.4 that changes how JS is generated. So I will start to target 1.4 and see if this is fixed

**Comment by emign** [comment]
Yes. It’s inconsistent

**Comment by soywiz** [comment]
With Kotlin 1.4 it doesn't crashes. The exception thrown is fixed here: https://github.com/korlibs/korge-next/commit/c3f0062f7c1761e5ebf20d4c3ec3a7e2de4821d9
So I'm closing this issue
