### ISSUE TITLE
Unexpected Behavior of On Click with Nested Views

### ISSUE THREAD

**Issue by cmhulbert** [korlibs/korge#133]
When nesting a view, the click event doesn't seem to trigger in a nested view, only a top level view.

A basic test is the following:
```kotlin
suspend fun main() = Korge(width = 400, height = 400) {
  solidRect(400, 400, Colors.RED) {
    onClick {
      println("OuterRect")
    }
  }
  solidRect(200, 200, Colors.GREEN) {
    onClick {
      println("InnerRect")
    }
  }
}
```
Which yields the following:
![image](https://user-images.githubusercontent.com/1859669/80870859-0d476100-8c77-11ea-8dc0-ed5c5284f28d.png)
When clicking on the green square, you get `InnerRect` as expected, and on the red square, you get `OuterRect`
The above works because the green square is not a child of the red square. I would expected the same behavior if the green square was a child of the red square. I'll demonstrate below what the actual behavior is though.

Here is the same portion above, but with the green square inside the red square:
```kotlin
suspend fun main() = Korge(width = 400, height = 400) {
  solidRect(400, 400, Colors.RED) {
    onClick {
      println("OuterRect")
    }
  }.solidRect(200, 200, Colors.GREEN) {
    onClick {
      println("InnerRect")
    }
  }
}
```
Which yields:
![image](https://user-images.githubusercontent.com/1859669/80870921-7e871400-8c77-11ea-9a22-1e2df96abf8e.png)

Obviously the first thing to note is that the green square is rendered black. I actually didn't realize that until this test.
Upon clicking in the red square, you properly get a println of `OuterRect`, however when clicking in the area that should be a green square, you _also_ get `OuterRect` when I would expect `InnerRect`

**Comment by soywiz** [comment]
There are several things here:

* I guess `Rect` shouldn't be a container but just a plain View.
* The black rect looks like a bug indeed.
* And the event part I think it is normal with the current implementation. I guess that when an object has a listener, doesn't try to reach its children first. I can have a look. The problem is that changing that might break other code. But might have sense. Or maybe I can enable a toggle to have this behaviour for now, and in KorGE 2.0 switch to the new behaviour What do you think?

**Comment by cmhulbert** [comment]
I feel like it would make sense for the click event to trigger in the order that it is seen. I think it might be easiest to offer an option for containers to pass the event "through" themselves, on to their children. I may have looked in the wrong place, but I saw that the events have an `isOver` flag, based on the `hitTest`. Perhaps even offering an event-level option to reset the `isOver` flag in the parents event handler, so `hitTest` can find the next view. 

I'm not sure I was following that portion 100% when looking at the code, but that's just a thought.

**Comment by soywiz** [comment]
Can't reproduce this anymore:

```kotlin
container {
    onClick { println("OuterRect") }
    solidRect(400, 400, Colors.RED)

    solidRect(200, 200, Colors.GREEN).onClick {
        println("InnerRect")
    }
}
```

Both the black rect, and the events seem to work properly. Feel free to reopen if you can find other case where this is not working
