### ISSUE TITLE
Some of the methods in MRectangle can be put into IRectangle

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1344]
For example the intersection methods:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/219555422-be41ca87-5a22-4ef6-a64e-edf6f9620bce.png">

There are also more but I haven't looked much into it.

**Comment by soywiz** [comment]
Fixed here: https://github.com/korlibs/korge/commit/fb96ac25979fa26de8ba74d1743b0b2d3c1258b0

Feel free to update them if you find that the arguments could be `I` variants, you can either commit to the main branch for that or make a PR. We can resolve conflicts if I update them in the meantime
