### ISSUE TITLE
text display effect had been impaired

### ISSUE THREAD

**Issue by CobbGao** [korlibs/korge#1351]
val font3 = resourcesVfs["simple_chinese_song.ttf"].readTtfFont(preload = true)
        text(
            "你好,2023",
            font = font3,
            textSize = 16.0,
            alignment = TextAlignment.BASELINE_LEFT,
            autoScaling = true
        )
            .xy(200, 200)
            .apply {
                smoothing = false
            }
with version v2.7.0 (the version adopted by korge-samples)
![20230220-192458](https://user-images.githubusercontent.com/26893419/220093161-c3a8d743-82f7-47a3-a5f1-b0bbf06c1459.jpg)
and same code with v3.3.0 (also tried with v4.0.0-alpha-3)
![20230220-192451](https://user-images.githubusercontent.com/26893419/220093319-7911aed1-be91-434e-8f0d-3c974cd7d405.jpg)

**Comment by CobbGao** [comment]
[simple_chinese_song.ttf.zip](https://github.com/korlibs/korge/files/10784052/simple_chinese_song.ttf.zip)

**Comment by soywiz** [comment]
This should be fixed by now since KorGE by default now it uses lazy SDF fonts from the default TTF
