### ISSUE TITLE
Text scaling on 4.x

### ISSUE THREAD

**Issue by Maddin-M** [korlibs/korge#1373]
How to reproduce:
- create a KorGE project using a 4.x version (I used 4.0.0-alpha-3)
- add `text(text = "foobar", textSize = 100.0, color = Colors.BLACK)`
- text is blurry

Two images showing the difference between 3.4.0 and 4.0.0-alpha-3
![before](https://user-images.githubusercontent.com/34421118/221615468-cd822c52-d6a5-4ef9-955e-edbf6d6b3746.png)
![after](https://user-images.githubusercontent.com/34421118/221615462-fd76b7fb-a6e0-489b-8b07-d5bceff1c436.png)

**Comment by soywiz** [comment]
Can you try to set `text(font = DefaultTtfFont)`? It was changed to a lazily computed bitmap font by default, so it favours performance over quality by default

**Comment by Maddin-M** [comment]
Yes, this fixes it

**Comment by soywiz** [comment]
This was fixed somehow. Now the default font uses a lazily computed bitmap font with SDF that should scale better and give excellent performance. For higher quality results you can still use DefaultTtfFont.
