### ISSUE TITLE
Flickering in Korge

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1374]
https://youtu.be/sHrsKFPK8mA

**Comment by soywiz** [comment]
Can you provide more details? Version of korge, kind of view that is having the flickering? Is that a Graphics using GPU as renderer?

**Comment by Kietyo** [comment]
Latest commit of korge.

Looks like the pathing lines is using gpuGraphics

https://github.com/Kietyo/XenoTacticV2/blob/aa1e9aeab00016beac8a25197d3c7621c1aca1da/korge/src/commonMain/kotlin/com/xenotactic/korge/ui/UIMapV2.kt#L89

I also have a mix of graphics/containers

**Comment by soywiz** [comment]
`Shapes`, `GpuVectorRendering` & `EmojiColrv1` korge-sandbox samples reproduces this issue

**Comment by soywiz** [comment]
Can you verify this is fixed after https://github.com/korlibs/korge/pull/1450 ?

**Comment by soywiz** [comment]
Closing as I believe this is fixed. Feel free to reopen if it is not the case.

**Comment by Maddin-M** [comment]
Sorry, still flickering, reproduced [here](https://github.com/Maddin-M/korge-playground/tree/flickering).
Hover over the button or scrollbar to flicker.
Use scrollbar to flicker.

**Comment by soywiz** [comment]
It seems that flickers the views before the uiScrollable:

Snippet:
```kotlin

suspend fun main() = Korge(windowSize = SizeInt(512, 512), bgcolor = Colors["#2b2b2b"]).start {
	val sceneContainer = sceneContainer()

	sceneContainer.changeTo({ MyScene() })
}

class MyScene : Scene() {

    override suspend fun SContainer.sceneMain() {
        solidRect(scaledWidth, scaledHeight, Colors.DARKBLUE).xy(0, 0)
        uiScrollable(width = 100.0, height = 100.0) {
            uiButton(
                label = "foo",
                width = 30.0,
                height = 30.0,
            )
            text("\n\n\n\n\n\n\n\n\n\n")
        }
        solidRect(scaledWidth, scaledHeight, Colors.DARKRED).xy(100, 100)
    }
}
```

**Comment by soywiz** [comment]
BTW. I have reproduced the problem locally and in a test, and I'm working on a fix. In the meantime, you can circumvent the issue with `uiScrollable(cache = false)`
