### ISSUE TITLE
Multi-module project example that works with autoreload

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1387]
Would be nice to have a multi module project template that has:

- a korge client
- a server
- common game logic

and works with autoreload. Haven't been able to get auto-reload working myself for my own multi-module project.

https://github.com/Kietyo/XenoTacticV2 (only shared with soywiz thus far)

**Comment by soywiz** [comment]
This existed already. I have updated it: https://github.com/korlibs/korge-hello-world-client-server

It seems to work. But it doesn't get changes in the common module, only changes in the client module

**Comment by soywiz** [comment]
With this change: https://github.com/korlibs/korge/pull/1405
you can make changes in the shared module of 
https://github.com/korlibs/korge-hello-world-client-server
and still get hotreloading :)

So I guess that repo is exactly `a multi-module project example that works with autoreload`, so I'm closing this. Feel free to reopen the issue if for some reason that sample doesn't work for you after doing a `./gradlew clean publishToMavenLocal` here in the korge repo
