### ISSUE TITLE
KorTE: Accessing Map's declared properties

### ISSUE THREAD

**Issue by olehs** [korlibs/korge#1413]
Is it possible to access Maps' declared properties from templates ?

Imagine this class as sample

```kotlin
class TemplateTimeStamp : LinkedHashMap<String, Any?>() {
    val time: String? by this.withDefault { null }
    val date: String? by this.withDefault { null }

    val dateTime: Date?
        get() = if (time != null && date != null) {
            SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ROOT).parse("$date $time")
        } else null
}
```
How can I get dateTime value from template?

Ref. code:
https://github.com/korlibs/korge/blob/122992a79c0fd6500f1c503763f11c6da2f32708/korte/src/commonMain/kotlin/com/soywiz/korte/dynamic/Dynamic2.kt#L156-L178

**Comment by olehs** [comment]
Unfortunately, this line actually causes the problem.

It doesn't allow to access dateTime property, as it tries to find key 'dateTime' in the map.
But dateTime property can be accessed only with mapper.

Here is modified version that can clarify my point
```kotlin
suspend fun accessAny(instance: Any?, key: Any?, mapper: ObjectMapper2): Any? {
        val keyStr = DynamicContext { key.toDynamicString() }
        return when {
            instance == null -> null
            instance is Dynamic2Gettable -> instance.dynamic2Get(key)
            mapper.hasProperty(instance, keyStr) -> {
                //println("Access dynamic property : $keyStr")
                mapper.get(instance, key)
            }
            mapper.hasMethod(instance, keyStr) -> {
                //println("Access dynamic method : $keyStr")
                mapper.invokeAsync(instance::class as KClass<Any>, instance as Any?, keyStr, listOf())
            }
            instance is Map<*, *> -> instance[key]
            instance is Iterable<*> -> instance.toList()[Dynamic2.toInt(key)]
            else -> {
                //println("Access dynamic null : '$keyStr'")
                null
            }
        }
    }
```

More 'Kotlin' way would be to access `instance['key']` as map fields and `instance.key` as object properties.
But I guess this would break compatibility with current implementation

**Comment by soywiz** [comment]
But then methods available in the Map interface/implementation could be called instead.
This tries to mimic the behaviour of liquid template engine. And that's the usual behaviour: maps and objects act the same.

Could you consider doing something else like?:

```kotlin
class TemplateTimeStamp(val map = LinkedHashMap<String, Any?>()) {
    val time: String? by map.withDefault { null }
    val date: String? by map.withDefault { null }
```

**Comment by olehs** [comment]
I get your point, but in real implementation things are a little bit more complicated (include custom delegated properties, nested maps, participate in serialization etc.)

I think another solution could be moving accessAny processing to Mapper so this behavior could be overridden.
If you think this can't be done, please close the issue freely.

BTW, thank you for great library and support
