### ISSUE TITLE
gpuGraphics is cropping when parent container scale changes

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1440]
Built on latest commit: https://github.com/korlibs/korge/commit/3a76dd04a9aabace803828b961adf4645df9a5d5

When parent container scale changes, the gpuContainer doesn't seem to account for that fact and it crops if entities are moved out of a certain region.

Video that better shows this: https://youtu.be/6jBL27C_xBw

**Comment by soywiz** [comment]
Fixed in https://github.com/korlibs/korge/pull/1450
