### ISSUE TITLE
Class ... is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler when running runJvm

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1461]
Built on commit:
https://github.com/korlibs/korge/commit/1ca9ef634057bcaad1050494b733afd0a913ee6d

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/227412690-15157aed-4a3c-48a1-afd0-8c95668f6420.png">

**Comment by Kietyo** [comment]
Here's what my compiler settings look like:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/5054996/227413202-e611d73b-7029-43d0-a4b6-cb342720af4c.png">

**Comment by Kietyo** [comment]
Note, adding this to build.gradle.kts fixed it for me:

```
tasks{
    withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        kotlinOptions {
            freeCompilerArgs += listOf("-Xskip-prerelease-check")
        }
    }
}
```

**Comment by soywiz** [comment]
Fixed
