### ISSUE TITLE
Unable to import KorgeGradlePlugin

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#1493]
Built on commit:

https://github.com/korlibs/korge/commit/90bc4c320eca3c5598fb58f7519366ea6a438fd1

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/228723350-235d4cfb-b0ca-4b66-8cc5-991c91dded83.png">

Can you please update https://github.com/korlibs/korge-hello-world to use 4.0 beta? Then maybe I can reverse engineer how to get it working for my project.

**Comment by soywiz** [comment]
Dragonbones and Spine already updated:

* https://github.com/korlibs/korge-dragonbones/blob/main/example/build.gradle.kts
* https://github.com/korlibs/korge-spine/blob/main/example/build.gradle.kts

**Comment by soywiz** [comment]
Hello World: https://github.com/korlibs/korge-hello-world/pull/21

**Comment by soywiz** [comment]
And the Hello World with multiple modules client/server, that might be helpful for your case: https://github.com/korlibs/korge-hello-world-client-server/pull/2

**Comment by Kietyo** [comment]
Thanks! Got it working for my project.
