### ISSUE TITLE
Memory usage for graphics

### ISSUE THREAD

**Issue by kirk88** [korlibs/korge#1518]
I'm using pose detection to display skeleton data to graphics

https://user-images.githubusercontent.com/72687899/230910977-1491a0a2-39fb-41f3-b522-c1fc183f8198.mp4

I found that the memory usage continues to increase during use. My code is written like this. Is there any way to optimize it?
![屏幕截图 2023-04-10 205604](https://user-images.githubusercontent.com/72687899/230909554-7f50ca09-6062-4e57-b7f0-277c51a9b906.png)

![屏幕截图 2023-04-10 204608](https://user-images.githubusercontent.com/72687899/230909576-0bf22673-e62d-4dcb-afb4-4ae397791ca2.png)

**Comment by soywiz** [comment]
Maybe it was fixed at some point. Then we can consider this issue fixed?

**Comment by kirk88** [comment]
Thanks, issue fixed, I'll close it.
