### ISSUE TITLE
The alignment of text

### ISSUE THREAD

**Issue by kirk88** [korlibs/korge#1519]
```kotlin
val p = Point(640, 320)
        graphics {
            fill(Colors.RED) {
                circle(p, 60f)
            }

            fillText("A", p, textSize = 60f, font = DefaultTtfFont, halign = HorizontalAlign.CENTER, valign = VerticalAlign.CENTER, color = Colors.WHITE)

            drawText("B", p, size = 60f, font = DefaultTtfFont, fillStyle = Colors.WHITE, align = TextAlignment.MIDDLE_CENTER)
        }
```
![Screenshot_2023-04-11-13-33-24-19_cce5dd7e1c7e341727b458551232e150](https://user-images.githubusercontent.com/72687899/231066806-bc2626a5-54f4-4390-8af7-3b5dece35ca3.jpg)

halign and valign are not work in fillText

**Comment by soywiz** [comment]
Also, let's unify halign/valign -> align

**Comment by soywiz** [comment]
Fixed in https://github.com/korlibs/korge/commit/84f8d3b3496dff2e79c3650bcca01beb6b7f038e
