### ISSUE TITLE
Support WASM target to krypto

### ISSUE THREAD

**Issue by bmalkow** [korlibs/korge#1536]
Would you like to add `wasm` target to [krypto](https://github.com/korlibs/korge/tree/main/krypto) module, please?

**Comment by soywiz** [comment]
Yes, there are plans for it. But that will happen after the release of 4.0.

**Comment by soywiz** [comment]
Available in https://github.com/korlibs/korge/releases/tag/v4.0.1 along kds, kmem, klock, krypto, klogger, kbignum
