### ISSUE TITLE
Android release build are being published without code since 4.0.0-beta2

### ISSUE THREAD

**Issue by iTanChi** [korlibs/korge#1554]
Beta version:
```
[kbignum-android-4.0.0-beta.aar](https://repo1.maven.org/maven2/com/soywiz/korlibs/kbignum/kbignum-android/4.0.0-beta/kbignum-android-4.0.0-beta.aar)                    2023-03-29 19:33     60494
```
Beta2 version  to latest:
```
[kbignum-android-4.0.0-beta2.aar](https://repo1.maven.org/maven2/com/soywiz/korlibs/kbignum/kbignum-android/4.0.0-beta2/kbignum-android-4.0.0-beta2.aar)                   2023-04-04 09:31       952
```

Inside the arr:
<img width="349" alt="Screenshot 2023-04-26 at 21 40 46" src="https://user-images.githubusercontent.com/45251281/234611561-a231bf96-1950-4e9e-ba30-451180bbf462.png">

**Comment by soywiz** [comment]
I guess this was fixed at some point before or in `4.0.0-rc`:

[kbignum-android-4.0.0-rc-debug.aar](https://repo1.maven.org/maven2/com/soywiz/korlibs/kbignum/kbignum-android/4.0.0-rc/kbignum-android-4.0.0-rc-debug.aar)                2023-04-13 15:00     63317

https://repo1.maven.org/maven2/com/soywiz/korlibs/kbignum/kbignum-android/4.0.0-rc/

Can you confirm it is the case?

**Comment by soywiz** [comment]
https://github.com/korlibs/korge/compare/v4.0.0-beta...v4.0.0-beta2

Looking at the diff it seems that we bumped Kotlin 1.8.20 and changed some stuff to the buildscript related to Android.

* https://github.com/korlibs/korge/commit/dcd5d68fa0f10e096c06c18328309a87b18d58d6#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87df
* https://github.com/korlibs/korge/commit/5d52a55da9acef9439145d7d2ea39ab1cdbac6ea

**Comment by soywiz** [comment]
But I can't think of any of those changes that could make the debug vs release to not include the classes. Do you have any idea of what could it be?

**Comment by soywiz** [comment]
I have reproduced it. A korge project using 4.0.0-rc can execute the `runAndroidDebug` task, but fails with `runAndroidRelease` since it cannot find required symbols.
