### ISSUE TITLE
ReadSound function from resources does not play music indefinitely

### ISSUE THREAD

**Issue by azartx** [korlibs/korge#1559]
Hello

Korge 4.0.0-rc, jvm, android (android is in priority)

https://discord.com/channels/728582275884908604/801658049244430377/1100060631396266044

When i trying to play music indefinitely by calling readSound() function = music plays once and then stopeed.
When i call function readMusic() - sound plays fine with infinity looping.

![image](https://user-images.githubusercontent.com/66694997/234907096-3c89a45d-1350-444d-8225-93a392b8013d.png)

SoundsCoroutineContext - just context, which contains sound String name

**Comment by azartx** [comment]
And i found another issue with sounds. I dont know how it reproduce, but i have music, which start playing in KorgeRunner(Korge(main = { play() })) (all code on the screenshot)
![image](https://user-images.githubusercontent.com/66694997/234975084-0eee23d1-2b8d-4cae-8282-4bc22a3d5de2.png)

function playDefaultMusic() call function playAsync from previous screenshot from my previous post.

And when i start playing game (music is playing) - i heard what this song superimposed on each other. After few minutes game start freezing because of many songs are playing at the moment.

**Comment by soywiz** [comment]
That's on Android only, right?

**Comment by soywiz** [comment]
Better to have a separate issue for that
