### ISSUE TITLE
Better integration with Box2d

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge#156]
Proposal: https://github.com/korlibs/korge-samples/pull/18

**Comment by emign** [comment]
Sorry for being late to the party. I was just able to check the box2dv2 sample and it looks really concise. I would call it something like `attachBody` or `attachPhysicsBody` but thats subjective

**Comment by RezMike** [comment]
I will check the box2dv2 sample and try to port some jbox2d examples there. During that I will probably update box2d integration with korge. And I will think about suggestion, @emign.

**Comment by soywiz** [comment]
Nice. Then what I suggest is that you try this into something more complex. If it works fine we should integrate into the korge-box2d project
