### ISSUE TITLE
UTC to local conversion on iOS incorrect when date is different DST value

### ISSUE THREAD

**Issue by dalewking** [korlibs/korge#1587]
Here is example code that demonstrates the issue:

```
            val nov5_11am_locally = DateTime(1699200000)
            println(nov5_11am_locally)
            println(nov5_11am_locally.local)
            println(nov5_11am_locally.local.format("h:mma"))
```

The date time is the UTC value corresponding to November 5th at 11am in our local time which is Eastern standard time which is GMT-4 currently but for that time would be GMT-5. November 5th is after DST ends.

Here is what I get on Android which is correct:
```
DateTime(1699200000)
DateTimeTz(DateTime(1681200000), GMT-0500)
11:00am
```

But here is what I get on iOS which is an hour off:
```
DateTime(1699200000)
DateTimeTz(DateTime(1684800000), GMT-0400)
12:00pm
```

This is with version 3.4.0

**Comment by dalewking** [comment]
The example code was missing 3 zeroes from the timestamp, but it does not fundamentally change the result:

```
            val nov5_11am_locally = DateTime(1699200000000)
            println(nov5_11am_locally)
            println(nov5_11am_locally.local)
            println(nov5_11am_locally.local.format("h:mma"))
```

And on Android I get:
```
DateTime(1699200000000)
DateTimeTz(DateTime(1699182000000), GMT-0500)
11:00am
```

And on iOS I get:
```
DateTime(1699200000000)
DateTimeTz(DateTime(1699185600000), GMT-0400)
12:00pm
```

**Comment by dalewking** [comment]
You can see here (https://github.com/korlibs/korge/blob/main/klock/src/darwinMain/kotlin/korlibs/time/internal/KlockInternal.kt#L34) that the function is totally ignoring the parameter.

**Comment by soywiz** [comment]
This call should be replaced by the proper time: https://developer.apple.com/documentation/corefoundation/1543542-cfabsolutetimegetcurrent

**Comment by soywiz** [comment]
Thanks for pointing out to the method that was missing the parameter. It has been fixed already.

**Comment by dalewking** [comment]
Thanks for fixing it, but unfortunately due to the removal of the wrapped classes we can't upgrade to get the fix. We have a workaround using kotlinx-datetime and plan to migrate to kotlinx-datetime and only use klock for formatting

**Comment by soywiz** [comment]
I asked and kept that PR open for a while. I could restore the wrapped classes in 4.0.1. But if you plan to use kotlinx-datetime and nobody else misses the wrapped classes, it might not be worth to restore them.

I hope that at some point inline, now called value classes, are represented as structs instead in all targets where it make sense and they could expose methods to those targets.

In any case fixing this, since it was a bug made sense, so thanks for reporting it and pointing to the issue.
