### ISSUE TITLE
The Text component seems to only display English.

### ISSUE THREAD

**Issue by ijero** [korlibs/korge#1597]
After writing this piece of code, only the English part of the word `login` is displayed.
```
VStack {
    Text(Language.CURRENT.name, Colors.WHITE)
    Text("login", Colors.WHITE)
    Text("login あ", Colors.WHITE)
    Text("login 测试", Colors.WHITE)
}
```
![Desktop Screenshot 2023 05 14 - 02 18 20 21](https://github.com/korlibs/korge/assets/7928858/96631870-ef12-4ffe-829b-73b3cd71318d)

**Comment by soywiz** [comment]
The default font only includes latin characters. You would need to provide another font.

In the case of compose, current components are prototypes:

https://github.com/korlibs/korge-compose/blob/b7ae8b47da4d96581c601af8ca07c19a1ef6a9dd/korge-compose/src/commonMain/kotlin/korlibs/korge/compose/ComposeWidgets.kt#L19

You can create a custom TextWithFont:

```kotlin
@Composable
fun TextWithFont(text: String, color: RGBA = Colors.WHITE, font: Font = DefaultTtfFont, onClick: () -> Unit = {}) {
    ComposeKorgeView({
        TextBlock(RichTextData(text), size = Size(100, 32)).also {
            it.align = TextAlignment.MIDDLE_LEFT
            it.padding = Margin(0f, 8f)
            it.wordWrap = true
            it.font = font
        }
        //UIText("DUMMY", height = UIButton.DEFAULT_HEIGHT).also {
        //    println("Created UIText")
        //}
    }) {
        set(text) { this.text = RichTextData(it) }
        set(font) { this.font = it }
        set(color) { this.colorMul = it }
        set(onClick) {
            this.onClick { onClick() }
        }
    }
}
``` 

Or maybe pass a Modifier or something `modifier: Modifier = Modifier`.

**Comment by ijero** [comment]
Thank you for providing the method that solved my problem.
