### ISSUE TITLE
[Klock] DateFormat outputs invalid results and doesn't work with "X" pattern

### ISSUE THREAD

**Issue by LennyLizowzskiy** [korlibs/korge#1632]
# Klock's DateFormat doesn't work with "X" pattern:

Input:
```kotlin
DateFormat("EEE MMM dd HH:mm:ss Z yyyy").parseUtc("Sat Feb 18 00:10:00 +0000 2023")
```

Output (exception):
```
korlibs.time.DateException: Not a valid format: 'Sat Feb 18 00:10:00 +0000 2023' for 'EEE MMM dd HH:mm:ss Z yyyy'
```

But it works OK when I use "X" pattern instead of "Z" (but it should work with "Z")

# Klock's DateFormat outputs wrong string in some cases

Input:
```kotlin
DateFormat("EEE, dd MMM yyyy HH:mm:ss X").parseUtc("Sun, 21 Oct 2018 12:16:24 +0300")
```

Output:
```kotlin
1539044184 // should be 1540115784 - 1071600 seconds difference
```

## Environment
Kotlin-Multiplatform: 1.8.21
Klock version: 4.0.1

**Comment by LennyLizowzskiy** [comment]
typo:

`Klock's DateFormat outputs wrong string in some cases` -> ` Klock's DateFormat outputs wrong unix seconds in some cases`

**Comment by soywiz** [comment]
@LennyLizowzskiy 

Can you validate this is what you would expect?

![Screenshot 2023-05-26 at 01 09 12](https://github.com/korlibs/korge/assets/570848/9f1b9653-1276-4b1b-8a09-a7325b9cc4b2)

```
parse("EEE MMM dd HH:mm:ss Z yyyy", "Sat Feb 18 00:10:00 +0000 2023")
// 1676679000000
```

```
parse("EEE, dd MMM yyyy HH:mm:ss X", "Sun, 21 Oct 2018 12:16:24 +0300")
// 1540124184000
```

```kotlin
fun parse(
    pattern: String,
    dateString: String
): Long {
    val formatter = DateTimeFormatter.ofPattern(pattern)
    val dateTime = LocalDateTime.parse(dateString, formatter);
    val timestampMillis = dateTime.toInstant(ZoneOffset.UTC).toEpochMilli();
    return timestampMillis
}
```

If that's so I can investigate and try to fix it

**Comment by LennyLizowzskiy** [comment]
@soywiz 

`parse("EEE, dd MMM yyyy HH:mm:ss Z", "Sun, 21 Oct 2018 12:16:24 +0300")` instead of `parse("EEE, dd MMM yyyy HH:mm:ss X", "Sun, 21 Oct 2018 12:16:24 +0300")`.

And yes, outputs in your screenshot are valid

**Comment by soywiz** [comment]
@LennyLizowzskiy I said because:

> `1539044184 // should be 1540115784 - 1071600 seconds difference`

The should be is different than `1540124184000`, so I'm not sure if it is a typing mistake, or that I computed it wrongly.

**Comment by LennyLizowzskiy** [comment]
@soywiz it was my mistake. I accidentally calculated timezone, so my result there was ahead by 3 hours. Your output is correct

**Comment by soywiz** [comment]
@LennyLizowzskiy you can get the desired result by replacing `parseUtc(str)` with `parse(str).local`
