### ISSUE TITLE
Add fps and graph overlay

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge#164]

**Comment by rishavs** [comment]
Can we also add cpu per core usage, ram usage, gpu memory and gpu compute usage to the overlay as well?

**Comment by soywiz** [comment]
We can try, though that info won't be available on all the platforms

**Comment by soywiz** [comment]
Should we do a remote coding session with this? Do you want any of you do this? Or do you want me to do this?

**Comment by emign** [comment]
I would love to take part in a remote session

**Comment by soywiz** [comment]
Nico, do you mind if we record it? https://kotlinlang.slack.com/archives/CJEF0LB6Y/p1594333531022500
