### ISSUE TITLE
Rect right and bottom sides not displayed

### ISSUE THREAD

**Issue by dhakehurst** [korlibs/korge#17]
`stage.graphics {
                stroke(Colors.BLACK, Context2d.StrokeInfo(thickness=2.0)) {
                    rect(x, y, w, h)
                    //roundRect(x, y, w, h, 5,5)
                }
            }`

The right and bottom sides are not visible.

**Comment by dhakehurst** [comment]
I'm using the latest versions, and this is still a problem?

**Comment by soywiz** [comment]
Are you using 1.1.3? That's strange:
https://korge.soywiz.com/samples/korge-box2d/index.html
That circle has a stroke with with, and previously was working wrong, but now displays fine.

**Comment by dhakehurst** [comment]
yep, version 1.1.3.
rounded rects, right and bottom not visible

**Comment by dhakehurst** [comment]
still an issue in version 1.2.0

**Comment by dhakehurst** [comment]
suspend fun main() = Korge(
    width = 512,
    height = 512,
    bgcolor = Colors["#ffffff"]
) {

    graphics {
        stroke(Colors.BLACK, Context2d.StrokeInfo(thickness=1.0)) {
            roundRect(10,10,300,200, 5,5)
        }
    }

}

![image](https://user-images.githubusercontent.com/5618533/54921137-4f936000-4f05-11e9-9eb3-ee7793171d23.png)

**Comment by soywiz** [comment]
Fixed. To try it with 1.2.0, you can:

```
git clone https://github.com/korlibs/korim.git
 ./gradlew :korim:publishJvmPublicationToMavenLocal :korim:publishJsPublicationToMavenLocal :korim:publishMetadataPublicationToMavenLocal
```

Then try again (might need to refresh the gradle project in intellij so it uses the artifact from maven local)

<img width="640" alt="Screenshot 2019-04-02 at 23 46 39" src="https://user-images.githubusercontent.com/570848/55438405-c97cb680-55a1-11e9-8cf9-2c3545a87a18.png">
