### ISSUE TITLE
Blurry Text in uiScrollable

### ISSUE THREAD

**Issue by cmhulbert** [korlibs/korge#1748]
When using text in a `uiScrollable` text is much blurrier:

![image](https://github.com/korlibs/korge/assets/1859669/8b8b78af-4892-415d-82ff-1a99a4472a28)

minimal script to reproduce: 
```kt
suspend fun main() = Korge(
        windowSize = Size(400, 800),
        virtualSize = Size(100, 200)
    ) {
    uiVerticalStack(100f) {
        uiScrollable(size = Size(100, 100)) {
            textBlock(align = TextAlignment.MIDDLE_CENTER, size = Size(100, 100)) {
                name = "blurry"
                text = RichTextData("test", font = DefaultTtfFontAsBitmap, textSize = 16.0f)
                blendMode = BlendMode.NORMAL
                fill = Colors.WHITE
            }
        }
        textBlock(align = TextAlignment.MIDDLE_CENTER, size = Size(100, 100)) {
            name = "sharp"
            text = RichTextData("test", font = DefaultTtfFontAsBitmap, textSize = 16.0f)
            blendMode = BlendMode.NORMAL
            fill = Colors.WHITE
        }
    }
}
```

**Comment by cmhulbert** [comment]
Actually, it's a bit more involved I guess. It looks like it has to do with the default font. Maybe when nested in the `uiScrollable`, the other font is not being respected? Here is a side by side. Top row is in a scrollable, left column has `font = DefaultTtfFontAsBitmap` and right column has default font:


![image](https://github.com/korlibs/korge/assets/1859669/75ddcd7c-b849-4d58-bd13-80e1af155f67)

```kt
suspend fun main() = Korge(
        windowSize = Size(800, 800),
        virtualSize = Size(200, 200)
    ) {
    uiHorizontalStack {
        uiVerticalStack {
            uiScrollable(size = Size(100, 100)) {
                textBlock(align = TextAlignment.MIDDLE_CENTER, size = Size(100, 100)) {
                    name = "blurry"
                    text = RichTextData("in scrollable ttfAsbitmap", font = DefaultTtfFontAsBitmap)
                    fill = Colors.WHITE
                }
            }
            textBlock(align = TextAlignment.MIDDLE_CENTER, size = Size(100, 100)) {
                name = "sharp"
                text = RichTextData("alone ttfAsbitmap", font = DefaultTtfFontAsBitmap)
                fill = Colors.WHITE
            }
        }
        uiVerticalStack {
            uiScrollable(size = Size(100, 100)) {
                textBlock(align = TextAlignment.MIDDLE_CENTER, size = Size(100, 100)) {
                    name = "blurry"
                    text = RichTextData("in scrollable defaultFont")
                    fill = Colors.WHITE
                }
            }
            textBlock(align = TextAlignment.MIDDLE_CENTER, size = Size(100, 100)) {
                name = "sharp"
                text = RichTextData("alone defaultFont")
                fill = Colors.WHITE
            }
        }
    }
}
```

**Comment by soywiz** [comment]
Related to SDF fonts and probably HiDpi screen right?

**Comment by cmhulbert** [comment]
I do have a HiDPi screen, for the regular fonts, I think you are probably right (though, I haven't checked anything more). Doe you have an idea why it's blurry in the `uiScrollable` with `DefaultTtfFontAsBitmap` when it is not blurry outside of the `uiScrollable`?

**Comment by cmhulbert** [comment]
Ok, so I figured out why `uiScrollable` is different in this regard. `UIScrollable` inherits from `UIView` and set's `cache = true` by default. With `cache=false` you get the sharper text again. I'm not sure the underlying cause, but at least I have a way to get non-blurry text again in a UIScrollable component

**Comment by soywiz** [comment]
That's because an intermediate texture is created. And the texture size is not HIDPI aware, and in fact it uses virtual pixels instead, so it is created with a smaller size and when scaled it is blurry.

We can convert local space pixel dimensions into screen pixel dimensions and create a texture of that size to fix this. But we migth want to do this conditionally so we can use the old method if we want to favour speed over quality.

**Comment by soywiz** [comment]
This was fixed with the linked PR
