### ISSUE TITLE
korim 4.0.8 not backwards compatible with 4.0.1

### ISSUE THREAD

**Issue by sproctor** [korlibs/korge#1783]
```
No virtual method getRect-Xvl6pYU()Lkorlibs/memory/pack/Int4Pack; in class Lkorlibs/image/bitmap/Bitmap; or its super classes (declaration of 'korlibs.image.bitmap.Bitmap' appears in base.apk)
```

I have an app using korim 4.0.8 that depends on a library built using 4.0.1 and I get that exception.

**Comment by sproctor** [comment]
This is the line in my library that causes the crash: https://github.com/sproctor/SignaturePad/blob/master/signaturepad/src/commonMain/kotlin/com/seanproctor/signaturepad/SignaturePadState.kt#L225

**Comment by soywiz** [comment]
I'm sorry for the inconvenience. Indeed that breaking change doesn't follow the SemVer rules.
In 4.0.0 I missed some classes that were wrapping some of those `Int4Pack` as I did experiments with MFVC to reduce GC allocations. Once I figured out, reverted them back to `data class` in that minor version. It is a source-based compatible change, but indeed a binary breaking change.
I don't expect to make more of those binary-breaking changes in 4.0.x. But I prefer to keep the data classes now.
Do you think it is possible to update that library to include the latest one?
Again, I'm sorry for the inconvenience.

**Comment by sproctor** [comment]
Yes, I've already updated it to the latest version. Thanks for the reply. I've just been blindly updating patch versions. I guess I should add some tests to confirm binary compatibility. I usually skim the change log, so for me it would be super helpful to have a warning there for versions that have potentially backwards-incompatible changes. It seems like there's no good way to address this breakage that doesn't cause additional breakage, so I'm closing this.
