### ISSUE TITLE
Audio played via KorAU is choppy and plays way faster than expected

### ISSUE THREAD

**Issue by ArrayBolt3** [korlibs/korge#1784]
Environment: Kubuntu 22.04 LTS, IntelliJ IDEA Community Edition 2023.1.3, OpenJDK 20, KorAU 4.0.8.

Steps to reproduce:

1. Create a new, blank Kotlin project in IntelliJ IDEA, and name it whatever you want (I used korauTest).
2. Add the Maven package "com.soywiz.korlibs.korau:korau-jvm:4.0.8" to the project via the Project Structure settings.
3. Put a sound file into the src/main/resources directory named "beeper.mp3". (I'm using a file made in Audacity for this.)
4. Create a new file in src/main/kotlin named "main.kt".
5. Paste the following code into the file:
```
import korlibs.audio.sound.*
import kotlinx.coroutines.*

fun main() {
    val soundBytes = object {}.javaClass.getResourceAsStream("beeper.mp3")!!.readAllBytes()
    runBlocking {
        NativeSoundProvider().createSound(soundBytes).toStream().playAndWait()
    }
}
```
6. Press the "Run" button in IntelliJ IDEA.

Expected result: The audio should play back sounding the same as if it is played back using a media player.

Actual result: The audio plays back quicker than expected, and sounds as if it's being quickly interrupted and restarted as it plays.

Additional info: The same results are observed whether the "beeper" sound is a WAV file or an MP3 file. Loading the audio data from a file on disk using the solution [here](https://stackoverflow.com/a/75973581/19474638) has the same problem - it's not specific to loading a sound from a resource file.

This video demonstrates the problem (you'll need audio on in order to hear it).

https://github.com/korlibs/korge/assets/104878738/5b556fee-6319-4e21-b72f-759a95792196

**Comment by soywiz** [comment]
Can you include your `beeper.mp3` here so I can reproduce exactly your issue (hz, etc.)?

**Comment by ArrayBolt3** [comment]
Another observation I've made is that, sometimes when the sound plays, it only plays part-way through (only two of the three beeps in my beeper.mp3 file manage to play), and then the whole program freezes. This has only happened to me two or three times, and it's not reliably reproducible, but I thought I should mention that detail.

**Comment by soywiz** [comment]
I managed to get it better. Still not perfect. I have plans to simplify audio implementations, and make them more robust with some common changes.
