### ISSUE TITLE
Exception for generate TypedAse

### ISSUE THREAD

**Issue by kirk88** [korlibs/korge#1800]
An exception for ASEInfo.getAseInfo:
``
FILE: aseFile=LocalSFile(D:\Android\WorkPlace\GameCenter\game-korge-sample\resources\fleks\sprites.ase)
java.lang.IllegalStateException: Can't read byte at 10 in ByteArraySlice[10]
	at korlibs.korge.gradle.util.ByteArraySimpleInputStream.readU8(InputStreamExt.kt:32)
	at korlibs.korge.gradle.util.ByteArraySimpleInputStream.readS32LE(InputStreamExt.kt:53)
	at korlibs.korge.gradle.util.ASEInfo$Companion.getAseInfo(ASEInfo.kt:72)
	at korlibs.korge.gradle.util.ASEInfo$Companion.getAseInfo(ASEInfo.kt:27)
``

sprites.ase  is taken from the [korge-fleks](https://github.com/korlibs/korge-fleks/blob/main/example/src/commonMain/resources/sprites.ase) project

**Comment by soywiz** [comment]
https://github.com/korlibs/korge/blob/0289a0392377bdd2d42fae2e3ac8570b3c34914e/buildSrc/src/main/kotlin/korlibs/korge/gradle/KorgeExtension.kt#L148

Thanks for reporting. We'll investigate.

In the meantime, please, disable typed resource generation https://github.com/korlibs/korge/blob/0289a0392377bdd2d42fae2e3ac8570b3c34914e/buildSrc/src/main/kotlin/korlibs/korge/gradle/KorgeExtension.kt#L148:

In the `build.gradle.kts`:

```kotlin
korge {
  autoGenerateTypedResources = false
}
```

**Comment by soywiz** [comment]
Fixed here https://github.com/korlibs/korge/pull/2062
