### ISSUE TITLE
Firststeps documentation page not loading 

### ISSUE THREAD

**Issue by basildoesstuff** [korlibs/korge#1809]
First steps page not loading 
Page link : https://docs.korge.org/korge/firststeps
![image](https://github.com/korlibs/korge/assets/61533404/95f61238-4cce-47b7-8d6a-e820e3d6325c)
redirected to that page from https://docs.korge.org/korge/
![image](https://github.com/korlibs/korge/assets/61533404/0f41387c-ef06-416b-b8ac-925034afdc92)

**Comment by soywiz** [comment]
That page doesn't exist anymore.

I have added a check to ensure there are no more local broken links: https://github.com/korlibs/korge/blob/cc9f37efe745c776957c0a69989f3733300fa1f5/.github/workflows/TEST.yml#L121
