### ISSUE TITLE
Default Button text should be dark

### ISSUE THREAD

**Issue by rishavs** [korlibs/korge#181]
Currently, the default button theme is white and the default button text is white as well. which makes for some weird looking buttons.

![image](https://user-images.githubusercontent.com/1210239/83688401-f8117980-a60a-11ea-8d26-32c3cbdc3f64.png)

The default button text should be Dark Grey so as to be legible on all UI themes.

**Comment by soywiz** [comment]
Shadow was being rendered in front of the white part. It is fixed already (not sure if in next or in the latest version)
