### ISSUE TITLE
The https://korlibs.soywiz.com/korge/changelog/ page should be kept updated

### ISSUE THREAD

**Issue by rishavs** [korlibs/korge#185]
As a new user, when I looked at the changelog page, it looked like the engine hadn't been updated in an year. The last entry is for 1.2.0 (2019-03-17)

Only when I checked the GH, I realized that this project was in heavy development.
I think having an out-of-date changelog in the main is detrimental to potential users checking out the documentation.

Proposal:
1. https://korlibs.soywiz.com/korge/changelog/ should be linked to the https://github.com/korlibs/korge/releases/tag/<release id> so the changelog always shows the updated changelog.
2. Also, the current changelog logs like https://github.com/korlibs/korge/releases/tag/release-1.12.14 do not contain any details of what's new. I feel it will be very helpful to have simple bullet point list of the new stuff in there.

**Comment by soywiz** [comment]
Note, that the real version is the one from gradle `korge-plugins` here: https://github.com/korlibs/korge-plugins/releases
Those versions include some fixes from other libraries that don't need to fully recompile KorGE
