### ISSUE TITLE
Do I correctly understand, that this project become a monolith?

### ISSUE THREAD

**Issue by InsanusMokrassar** [korlibs/korge#1906]
I do not see independent artifacts in maven repo of [korge](https://repo.maven.apache.org/maven2/com/soywiz/korge/) and I do not see new releases in artifacts of [korlibs](https://repo.maven.apache.org/maven2/com/soywiz/korlibs/).

Do I correctly understand that currently there are no any way to use some independent parts of korge libs (like time)?

**Comment by soywiz** [comment]
There are two options to use the `korlibs.time` package:

* Include the `korge-foundation` artifact for >= 5.0.0, which indeed include time and other packages.
* Use 4.0.x versions from this repo: https://github.com/korlibs/korlibs4 .

In 5.0 not exactly a monolith but the number of artifacts were reduced significatively. New packages introduced there that were previously not possible without creating extra artifacts or strange interdependencies, etc.

**Comment by InsanusMokrassar** [comment]
Will it be possible to get some updates in korlibs4 since this update? I am not working with any 3D or 2D works (as for now) and do not need in my projects all the foundation :(

**Comment by soywiz** [comment]
> Will it be possible to get some updates in korlibs4 since this update? I am not working with any 3D or 2D works (as for now) and do not need in my projects all the foundation :(

Yes. The Korlibs4 repo is Open Source, and PRs are welcome!
