### ISSUE TITLE
Extreme performance problems during resize and move

### ISSUE THREAD

**Issue by Xyndra** [korlibs/korge#1997]
Whenever I try to move or resize the window there is a large performance drop.
System: Win64, JVM
Code: Default Hello World! template

This is a very noticeable problem which I do not want to ship to my users. Perhaps the default minimum RAM or similar should be increased.

**Comment by soywiz** [comment]
Didn't notice those. Can you provide a small video, and put which Windows, KorGE and JVM version are you using to run it?

**Comment by Xyndra** [comment]
My whole IntelliJ reindexed itself when trying to take run it again. It seems to not have been a IDE problem. It works now, so I will close this until it ever reoccurs.
