### ISSUE TITLE
Different click areas on scaled desktop with `View.onClick()` on JS backend

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#20]
If you create a view and add an `onClick()` listener this doesn't work as excpeted on JavaScript build.
``` kotlin
suspend fun main() = Korge(width = 256, height = 256, bgcolor = Colors.LIGHTGREY) {

    solidRect(256,256, Colors.WHITE){
        onClick { colorMul = Colors.BLUE }
    }

    solidRect(100,100, color = Colors.RED){
        onClick { colorMul = Colors.GREEN }
    }
    
}
```

![graphics](https://user-images.githubusercontent.com/1190109/53769524-6af9e500-3edc-11e9-825d-cc329b185628.png)

On the JS build, it makes a difference where you click the green rect. The upper right part of the rect triggers the listener in the background. But the green one is in front of the white. Clicking on the green should never trigger the white rect. On the JVM all works, regardless which green part is clicked.

And we can see that the rect in front of the blue one has a rendering error. You can see, that it's drawn by two rectangles.

**Comment by soywiz** [comment]
On a first try I was not able to reproduce it. Do you have more information? Operating System? Resolution? Maybe it is related to retina? I will try later on a hidpi to see if I can reproduce it

![screen recording 2019-03-05 at 11 57 30 2019-03-05 12_03_35](https://user-images.githubusercontent.com/570848/53801178-c957af80-3f3e-11e9-99a6-57d57df5ccbb.gif)
![screen recording 2019-03-05 at 11 58 14 2019-03-05 12_03_53](https://user-images.githubusercontent.com/570848/53801179-c9f04600-3f3e-11e9-96eb-048c0911a79e.gif)

**Comment by TobseF** [comment]
Yes you're right! The problem is the custom scaling. To see something without a loupe on my 3840 x 2160, I enabled a 125% scaling. I tested it on Firefox and Chrome:
![korge_rect](https://user-images.githubusercontent.com/1190109/53802645-a3cca500-3f42-11e9-9b02-2f8f9cc04354.gif)

Set the scale back to 100% solves this issue.

**Comment by soywiz** [comment]
Fix already on korgw. If you want to try it.

git checkout https://github.com/korlibs/korui.git
cd korui
./gradlew :korgw:publishJsPublicationToMavenLocal :korgw:publishMetadataPublicationToMavenLocal

The KorGE plugin check for artifacts in maven local first, so you should be able to use the fix already.

**Comment by TobseF** [comment]
Yes! It's fixed. And it also solves the problem of the changed 125% Windows scaling: https://github.com/korlibs/korge/issues/22
Great work, thank you!
