### ISSUE TITLE
dependencies cause unwanted addition of Android permissions

### ISSUE THREAD

**Issue by mstarostik** [korlibs/korge#2003]
Spotted on all korGE projects I've tried so far:

The dependencies managed by kproject, internal, external, or just ` ./deps` result in the addition of Android permissions ` READ_EXTERNAL_STORAGE`, `WRITE_EXTERNAL_STORAGE`, and most noteworthy `READ_PHONE_STATE`
This is caused by the dependencies' build.gradle files not specifying any Android SDK versions and so, there will be intermediate AndroidManifest.xml files generated for the deps, that contain
```
    <uses-sdk
        android:minSdkVersion="1"
        android:targetSdkVersion="1" />
```

While the final manifest actually specifies sensible SDK versions, this intermediate version 1 leads to:

```
uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
IMPLIED from [...]/build/AndroidManifest.xml:2:1-32:12 reason: hello.deps has a targetSdkVersion < 4
uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from [...]/build/AndroidManifest.xml:2:1-32:12 reason: hello.deps has a targetSdkVersion < 4
uses-permission#android.permission.READ_EXTERNAL_STORAGE
IMPLIED from [...]/build/AndroidManifest.xml:2:1-32:12 reason: hello.deps requested WRITE_EXTERNAL_STORAGE
```

Especially READ_PHONE_STATE is not something I want the app to request.

**Comment by soywiz** [comment]
Moved, since now the kproject stuff is integrated in the korge repo
