### ISSUE TITLE
Add color as a settable property for Text types

### ISSUE THREAD

**Issue by rishavs** [korlibs/korge#201]
Currently, once text has been initialized, I am unable to set the color property.
ie. this code doesn't works;
```
        var gameNameText = text("Super Pong Bros II") {
            color = Colors.FIREBRICK
            position(views.actualVirtualWidth/2 - 128, views.actualVirtualHeight/2 - 128)
        }
```

Expected:
a user is able to create a text object and then set the color property of the instance whenever needed.

**Comment by soywiz** [comment]
Are you using the latest version? It was added here: https://github.com/korlibs/korge/pull/183

**Comment by rishavs** [comment]
I think I am still on 12.8
my build.gradle.kts shows;
```
import com.soywiz.korge.gradle.*

buildscript {
	val korgeVersion: String by project

	repositories {
		mavenLocal()
		maven { url = uri("https://dl.bintray.com/korlibs/korlibs") }
		maven { url = uri("https://plugins.gradle.org/m2/") }
		mavenCentral()
	}
	dependencies {
		classpath("com.soywiz.korlibs.korge.plugins:korge-gradle-plugin:1.12.8.0")
	}
}

apply<KorgeGradlePlugin>()

korge {
	id = "com.example.example"
}
```

I dont know how I can upgrade. :/

**Comment by soywiz** [comment]
To upgrade just replace `1.12.8.0` with the latest version. That as for now is `1.13.2.0`. Hope it helps!
