### ISSUE TITLE
Fullscreen mode not working

### ISSUE THREAD

**Issue by rishavs** [korlibs/korge#202]
In my code I tried both these variants, but the fullscreen mode isn't working for me. I tried ;
```
object MyModule : Module() {
	// define the opening scene
	override val mainScene: KClass<out Scene> = MenuScene::class
	// define the game configs
	override val title: String = "My Test Game"
	override val icon: String = "icon.png"
//	override val size: SizeInt = SizeInt(800, 600)
	override val fullscreen: Boolean = true
```
and
```
class MenuScene() : Scene() {
    suspend override fun Container.sceneInit() {
        // set a background color
        views.clearColor = Colors.BLACK
        views.gameWindow.fullscreen = true
```

I am on WIndows 10 and used the runJVM target.

**Comment by alex199568** [comment]
Fullscreen is not working, neither on jvm nor on native windows. The window matches the size of the monitor, but it's not fullscreen, not even maximized. Korge plugin 2.0.6.1

**Comment by soywiz** [comment]
@alex199568 

This code works fine for me on the JVM Windows on the latest version: `2.1.1.4`

```kotlin
keys.down(Key.F1) {
	gameWindow.fullscreen = !gameWindow.fullscreen
}
```

Doesn't work for you?

**Comment by damalmax** [comment]
@soywiz, it is not working for me too (Windows 10).
I've tried different Korge versions and got the same result (Fullscreen mode):
![Fullscreen mode](https://user-images.githubusercontent.com/2301193/126909836-362257a0-a2a8-46f5-a7ee-bf274920e1a2.png)
