### ISSUE TITLE
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8

### ISSUE THREAD

**Issue by maik-mursall** [korlibs/korge#2028]
When `targetJs()` is missing from the build targets, my IDE throws this warning for every Korge-Component(Text, Button, etc...):
`Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option`

You can reproduce this by creating a new project using the "Hello World"-Template and removing `targetJs()` from the `build.gradle`.

### Further notes
- This seems to be only an issue with the language server, since building and running the application results in no error, even when the JavaScript build target is missing.
- ~~`jvmTarget` inside the `korge`-block is being completely ignored as well~~
- `jvmTarget` is only used for running the application
  - I encounter the same error during building/running when setting the `jvmTarget` to "1.8"

In the Module Settings I noticed the following (When `targetJs()` is present):
  - `commonMain` uses "JVM 1.8 & JavaScript"
  - `androidMain` uses "JVM 1.8"
  - `jvmMain` uses "JVM 11"
  - `jsMain` uses "JavaScript"

I believe because `targetJvm()` seems to always target "JVM 11" and not "JVM 1.8" like the others, that this is the root cause of the problem.

And because `targetJs()` adds `JavaScript` to the `commonMain` build targets, the language server doesn't notice the JVM differences anymore...

**Comment by maik-mursall** [comment]
I fear this might be not possible to solve according to [this issue](https://youtrack.jetbrains.com/issue/KTIJ-18375/MPP-IDE-common-source-set-always-has-default-JVM-target#focus=Comments-27-8193064.0-0).

I tried around a lot and was only able to lower the target of `jvmMain` to "1.8" but I'm not sure if that breaks something :/

So I think always including `targetJs()` or prepending `@file:Suppress("INLINE_FROM_HIGHER_PLATFORM")` to every file using Korge Methods is our only solution for now :/
(At least if we cannot make `jvmMain`.target = "JVM 1.8" work)

**Comment by Kietyo** [comment]
I too am running into this issue on the hello world example when I configured it to only enable jvm.

E.g:

```
korge {
	id = "com.sample.demo"
	targetJvm()
	serializationJson()
}
```

What the error looks like:

<img width="1280" alt="image" src="https://github.com/korlibs/korge/assets/5054996/9e61dc74-432d-424b-af49-5c815459f89c">

**After some browsing I found that JVM target 11 comes from here:**

https://github.com/korlibs/korge/blob/cbf8ef853b55198bec45d65b31b14bc694ae8d9e/buildSrc/src/main/kotlin/korlibs/korge/gradle/KorgeExtension.kt#L307

https://github.com/korlibs/korge/blob/cbf8ef853b55198bec45d65b31b14bc694ae8d9e/buildSrc/src/main/kotlin/korlibs/korge/gradle/targets/android/Android.kt#L155

**Comment by maik-mursall** [comment]
@Kietyo I had that suspicion as well, but I was only able to change the JVM Target of the Platform Modules, not the `common` Module itself :/

[This issue](https://youtrack.jetbrains.com/issue/KTIJ-18375/MPP-IDE-common-source-set-always-has-default-JVM-target#focus=Comments-27-8193064.0-0) might be rooted into Kotlin-Multiplatform itself 😅

**Comment by maik-mursall** [comment]
And for lowering the JVM-Target for all Modules to 1.8:
We really need to test if Korge is able to run entirely on 1.8. Because I think there was some kind of assert somewhere, that it needs to run on JVM 11.

I might check later if I find that.

**Comment by mipastgt** [comment]
I have been suffering from this issue independently of korge for quite some time too but in the latest version of IntelliJ this seems to be fixed now.
```
IntelliJ IDEA 2023.3 (Community Edition)
Build #IC-233.11799.241, built on December 2, 2023
```
I removed all the lines with `@file:Suppress("INLINE_FROM_HIGHER_PLATFORM")` in my code yesterday and don't see any issues anymore.

**Comment by maik-mursall** [comment]
Thank you @mipastgt for the info :)

I can confirm, that the IntelliJ Update indeed fixes this Issue 🎉 
Now the `common` Modules are configured properly to target the same & correct JVM-Version as the other Modules 🎉
