### ISSUE TITLE
SVG Doesn't support `t` Commands

### ISSUE THREAD

**Issue by gilbert-jolly** [korlibs/korge#204]
```kotlin.NotImplementedError: An operation is not implemented: Unsupported command 't' : Parsed: 'M0 0M161.1 242.6Q161.1 261.1, 147.8 273.9', Original: 'M161.118 242.688q0 18.432-13.312 31.232t-30.72 12.8q-19.456 0-33.792-12.288t-14.336-30.72q-1.024-20.48 11.776-34.816t31.232-14.336q20.48 0 34.816 13.824t14.336 34.304zM76.126 829.44v-450.56h69.632v450.56h-69.632z'```

Full SVG is available below
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="230" height="1024" viewBox="0 0 230 1024">
<title></title>
<g id="icomoon-ignore">
</g>
<path d="M161.118 242.688q0 18.432-13.312 31.232t-30.72 12.8q-19.456 0-33.792-12.288t-14.336-30.72q-1.024-20.48 11.776-34.816t31.232-14.336q20.48 0 34.816 13.824t14.336 34.304zM76.126 829.44v-450.56h69.632v450.56h-69.632z"></path>
</svg>
```

**Comment by soywiz** [comment]
Reference:

* Arcs: https://github.com/memononen/nanosvg/blob/25241c5a8f8451d41ab1b02ab2d865b01600d949/src/nanosvg.h#L2067
* T command: https://github.com/memononen/nanosvg/blob/25241c5a8f8451d41ab1b02ab2d865b01600d949/src/nanosvg.h#L2018

Place to implement:
* https://github.com/korlibs/korim/blob/c24a34170b2e1498d3928be1abcf17656e2a48e1/korim/src/commonMain/kotlin/com/soywiz/korim/vector/format/SVG.kt#L287
