### ISSUE TITLE
tilemap object layer not useable

### ISSUE THREAD

**Issue by emign** [korlibs/korge#205]
https://kotlinlang.slack.com/archives/G014YN8Q7TK/p1591718578024400

[Archiv.zip](https://github.com/korlibs/korge/files/4754218/Archiv.zip)

**Comment by soywiz** [comment]
![Screenshot from 2020-06-11 01-02-50](https://user-images.githubusercontent.com/570848/84327301-4aa8e380-ab7f-11ea-9293-205f4279794e.png)
