### ISSUE TITLE
[FR] onHover call back for button types

### ISSUE THREAD

**Issue by rishavs** [korlibs/korge#206]
Currently, the various button types have a default onHover effect but the onhover callback is not exposed to the user.

OnHover callback enables the Korge users to craft their own hover effects on the buttons, add soud cues on mouse over and even implement extra cues like tooltips.

**Comment by soywiz** [comment]
It is available:
https://korlibs.soywiz.com/korge/input/#mouse-1
`onOver`, `onOut`

**Comment by rishavs** [comment]
Thanks. This was my bad. I kept searching for the word "hover".

**Comment by soywiz** [comment]
Not you bad. Since I know now that you were searching for "hover", now I can add that word to the documentation :) Thanks!
