### ISSUE TITLE
Add Support for Subprotocol/subScheme in URL

### ISSUE THREAD

**Issue by itboy87** [korlibs/korge#2101]
The current `URL` lacks support for recognizing and handling subprotocols within URLs.

### Example Use Cases:

* jdbc:mysql://localhost:3306/database
* jar:file:/path/to/archive.jar!/entry/in/jar

**Comment by itboy87** [comment]
Hi @soywiz, I need your suggestion. Is it a good idea to add one more variable, subScheme or subProtocol, in the URL?

**Comment by soywiz** [comment]
Umh. I was not aware of that, but makes sense. Because it would be simpler in terms of building to do something like `$protocol:$subProtocol:`. If it is empty, it would just work. So yeah.

**Comment by itboy87** [comment]
After reviewing the code, I've identified that implementing `jdbc:mysql://localhost:3306/database` can be easily achieved by adding a `subScheme` and making some minor adjustments. This will effectively handle the format `<scheme>:<subscheme>://<host>:<port>/<path>?<query_parameters>#<fragment>`.

However, the `jar:file:/path/to/archive.jar!/entry/in/jar` format is not a widely used standard. Considering its limited usage and potential major changes required, I recommend temporarily omitting this feature. Additionally, there are various jar: variations, some of which might involve URLs instead of files.

For now, I'll focus on fixing and supporting the standard format `<scheme>:<subscheme>://<host>:<port>/<path>?<query_parameters>#<fragment>`.
