### ISSUE TITLE
Blur filter (maybe other too) isn't working on JVM and JS build

### ISSUE THREAD

**Issue by i-d-c-p** [korlibs/korge#213]
On both platforms it shows a black screen whenever a view is using the blur filter.

On JS: `ERROR::WebGL: INVALID_VALUE: uniformMatrix3fv: invalid size`
On JVM: Just a log line `OpenglAG: Created program program with id 6 because contextVersion: -1 != 0`

**Comment by massanchik** [comment]
Actually, I've tried out different filters from docs, and none of them worked. Graphics just disappearing when filters set.

**Comment by i-d-c-p** [comment]
Yes, they work only on Native and Android.

**Comment by soywiz** [comment]
Uhm. Does this sample work for you? https://github.com/korlibs/korge-samples/blob/master/filters/src/commonMain/kotlin/main.kt (it works for me)

```
./gradlew :filters:runJvm
```

**Comment by i-d-c-p** [comment]
It works on JS but nothing on JVM. I'm on a Mac with Catalina.

**Comment by soywiz** [comment]
Thanks! I will investigate

**Comment by soywiz** [comment]
Fixed on JS and seems to work on Windows and Linux. On JVM MacOS it doesn't work. Looking at this.
