### ISSUE TITLE
korlibs.graphics.gl.AGOpengl$ShaderException: Error Compiling Shader

### ISSUE THREAD

**Issue by quanticworld** [korlibs/korge#2135]
Hi dear Korge contributors,

I ran into this issue, on ubuntu, launching runJvmAutoreload task : 
`Caused by: korlibs.graphics.gl.AGOpengl$ShaderException: Error Compiling Shader : BatchBuilder2D.Tinted type=35632 : 0x00000000 : '' : source='#extension GL_OES_standard_derivatives : enable`

Any hints about that ? 

- I didn't modify anything in the created project
- The app has been created with Korge plugin. The android task works well on my phone (with android.useAndroidX=true in gradle.properties) but the desktop app does not launch.

Thanks in advance for your help !

**Comment by quanticworld** [comment]
OMG, I just needed to install opengl drivers...

To check : `glxinfo | grep "OpenGL version"`.

Sorry ! Hope it will help newbies like me :)

**Comment by soywiz** [comment]
Which OpenGL version was being reported by glxinfo? Which Linux variant/version were you using?
