### ISSUE TITLE
Sounds aren't playing on JS build

### ISSUE THREAD

**Issue by i-d-c-p** [korlibs/korge#214]
Hi guys I made this piece of code to make my characters sounds on jump:

```kotlin
var jumpSound: NativeSound

suspend fun loadCharacter(){
    jumpSound = resourcesVfs["sounds/fx/jump_fx.wav"].readSound()
}

fun explode() {
    jumpSound.play()
}
```

But on JS it's not playing, well actually it is playing since I awaited the channel and log, but nothing sounds.

**Comment by i-d-c-p** [comment]
UPDATE: On native build (MacOSx64) it shows the next error:
```
init[a] -- bb
init[b]
Korui[0]
CanvasApplicationEx.IN[0]
CanvasApplicationEx.IN[1]
Korui[1]
OpenglAG: Created program BatchBuilder2D.Premultiplied.Tinted with id 1 because contextVersion: -1 != 0
ERROR: AudioQueueEnqueueBuffer
ERROR: AudioQueueEnqueueBuffer
ERROR: AudioQueueEnqueueBuffer
ERROR: AudioQueueEnqueueBuffer
ERROR: AudioQueueEnqueueBuffer
ERROR: AudioQueueEnqueueBuffer
```

It appears on my Gamejam [game](https://github.com/i-d-c-p/parasite-game) just before the Game scene.

**Comment by soywiz** [comment]
I'll try to reproduce.

Btw ivan if you haven't contacted it already for your prize. Please send me an email: soywiz@gmail.com
:)

**Comment by soywiz** [comment]
I have performed a lot of sound fixes on all the targets including JS on korge-next. In next version should I hope this will work. If it is not the case, feel free to reopen it :)
