### ISSUE TITLE
Different click areas with `View.onClick()` on JS backend

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#22]
I tried to get my game buttons working on JS build -without success. 
So I tried it with a hello world. The first barrier was my the problem with my [scaled Windows desktop resolution](https://github.com/korlibs/korge/issues/20) on 125%. Then I had problems with the key events in general [because of a nasty chrome extension](https://github.com/korlibs/korge/issues/21). 

Both are easy to solve and my the hello button example runs on JVM and JS. So it's time for the get dirty in my game. Here i have still the problem of unpredictable bounding boxes on JavaScript run. It's hard to find out, what I did wrong, because on JVM all works.

Desktop JVM:
![korge_hitklack_desktop](https://user-images.githubusercontent.com/1190109/53805534-ad5a0b00-3f4a-11e9-835c-92d08ccfea81.gif)

Chrome JS:
![korge_hitklack_js](https://user-images.githubusercontent.com/1190109/53805538-b0ed9200-3f4a-11e9-9633-2670e6ad4e89.gif)

The problem also occurs on Firefox. All Browser extensions are disabled. Resolution is 3840 x 2160 without scaling. System: Windows 10.

The code for the game: https://github.com/TobseF/HitKlackOnKorGE

Don't know if it's related to this change on my game:
[Fix wrong timer position in JavaScript build](https://github.com/TobseF/HitKlackOnKorGE/commit/9c9a92ed9b3f31286a2c4e3c42dd8ba89a5f798a)
Here the `transform` also had a different effect on the JS version.

**Comment by TobseF** [comment]
The Buttons are created here: `de.tfr.game.ui.Button#create`

``` kotlin
   fun create(container: Container): Button {
        val posX = x
        val posY = y
        image = container.image(style.normal) {
            position(posX, posY)
        }

        image.onKeyDown { ifControlPressed(it) { setDown() } }
        image.onKeyUp { ifControlPressed(it) { setUp() } }
        image.onUp { setUp() }
        image.onDown { setDown() }
        return this
    }
```

**Comment by soywiz** [comment]
My bet is that it is related to `window.devicePixelRatio` and probably will have to be fixed here: 
* https://github.com/korlibs/korui/tree/master/korev
* https://github.com/korlibs/korui/tree/master/korgw

Can you check the JS value of `window.devicePixelRatio` in your browser when not working correctly?

**Comment by TobseF** [comment]
Exact! It's the `devicePixelRatio` of `0.75`. Setting it in the Browser console to `1` solves the issue.

**Comment by soywiz** [comment]
Ok, so probably the mouse/touch coordinates in the events are not scaled using that value or they are scaled without having too. I'll fix it this afternoon.

**Comment by TobseF** [comment]
Thanks a lot your support and your fix. This issue is gone after your latest KoreIU update: https://github.com/korlibs/korge/issues/20
