### ISSUE TITLE
The project is using an incompatible version (AGP 8.2.0) of the Android Gradle plugin. Latest supported version is AGP 8.1.0

### ISSUE THREAD

**Issue by hv6kyh** [korlibs/korge#2212]
<img width="1470" alt="스크린샷 2024-03-31 오후 12 23 16" src="https://github.com/korlibs/korge/assets/22249490/4e6de0d3-6a7f-4107-a968-75be17e7c3c7">

Build Error with Incompatible Android Gradle Plugin Version in "hello world" Project

**Comment by ArtRoman** [comment]
You should update your IDE. Current Android Studio version supports AGP 8.3.1, and last IDEA supports AGP 8.2.2.
<img width="442" alt="318239334-4e6de0d3-6a7f-4107-a968-75be17e7c3c7" src="https://github.com/korlibs/korge/assets/1625142/882dc7a1-6077-488e-ada0-e82a021b557a">

**Comment by hv6kyh** [comment]
thank you for your help. your solution worked perfectly. I'm going to close this issue now.
