### ISSUE TITLE
Korau: Pitch change doesn't work

### ISSUE THREAD

**Issue by ArtyomZhukov** [korlibs/korge#2217]
korge-core library: 5.4.0

Pitch changes doesn't affect on a result sound.
Tried to change pitch in PlaybackParameters and in SoundChannel.

`sound = resourcesVfs["sound.mp3"].readMusic()`
`soundChannel = sound?.play(params = PlaybackParameters(pitch = params.value.pitch))`

`soundChannel?.pitch = newPitch`

**Comment by soywiz** [comment]
Pitch shifting might be needed to be implemented via software, when no hardware option is available. In the meantime we can indicate that it won't work in all the cases.

**Comment by soywiz** [comment]
I have decided not to support it directly. At least for now due to complexity and not available on all the APIs.
