### ISSUE TITLE
Wav sound gets double length after decode

### ISSUE THREAD

**Issue by IkuzItsuki** [korlibs/korge#2220]
### The problem:
I tried to play a wav audio file and I found out that the length double after decoding.

I call localVfs to read the file
![image](https://github.com/korlibs/korge/assets/73303056/f09749a1-ff54-45ef-b447-b5ee2a8a2486)
and play it with AudioChannel
![image](https://github.com/korlibs/korge/assets/73303056/0d645dd2-30c8-444f-8b2f-79612f4de321)
the await outputs this, but it should be 1m 20s.
![image](https://github.com/korlibs/korge/assets/73303056/0d220f79-7320-44b4-82e7-c673c205fb3d)

### Platform:
I am using korge-core 5.4.0 in compose multiplatform for jvm and testing on windows.

**Comment by soywiz** [comment]
Can you try to korge 6.0.0-beta1?
