### ISSUE TITLE
Support Spine

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge#225]
http://esotericsoftware.com/spine-runtimes

I guess we can port the LibGDX one.

**Comment by emign** [comment]
I would really like to endorse this. Dragonbones seems to be dying or is at the least very very neglected by the developer. You can't even download the software atm

**Comment by soywiz** [comment]
Done

**Comment by soywiz** [comment]
![Screenshot from 2020-07-22 18-57-24](https://user-images.githubusercontent.com/570848/88205542-3f9ca500-cc4d-11ea-93e7-71b74301b1f2.png)
