### ISSUE TITLE
Stroke rectangle has different thinkness

### ISSUE THREAD

**Issue by dector** [korlibs/korge#227]
```kotlin
graphics {
  stroke(Colors["#f0f0f0"], Context2d.StrokeInfo()) {
    rect(100.0, 100.0, 300.0, 200.0)
  }
}
```

![Screenshot_2020-06-17_11-25-28](https://user-images.githubusercontent.com/265872/84868339-94b52c00-b08d-11ea-80d6-52c556ff4e8c.png)

(Left/top sides are thicker than right/bottom)

**Comment by soywiz** [comment]
Will be fixed on KorGE 2.0

**Comment by dector** [comment]
Some ETA for 2.0 version? :)

**Comment by RezMike** [comment]
No sooner than Kotlin 1.4
