### ISSUE TITLE
Korge Forge and Korge Wrapper command line installs are broken on Windows 10

### ISSUE THREAD

**Issue by elMuso** [korlibs/korge#2271]
Following the tutorial from https://docs.korge.org/getting-started/install/ it suggest ussing a command line to install Korge. The .cmd get's executed and downloads the resources to .korge in the users folder.

The problematic part comes with `jre-21.tar.xz` and the `tar --strip-components %STRIP_COMPONENTS% -C "%OUT%" -xf "%INPUT_FILE%"` . Windows `tar` doesn't support .xz files so the installation fails with the following error:

`Extracting C:\Users\PC\.korge\jre-21.tar.xz...
tar: Error opening archive: Can't initialize filter; unable to run program "xz -d -qq"`

According to this SO answer, to extract .xz you need to install additional software : https://superuser.com/a/1735194

Maybe the compression format for Windows should be changed to something that windows supports by default?

Edit:

Succesfully ran the hello world example on windows. BUT...

After looking at https://blog.korge.org/korge-wrapper i wanted to try it to setup Korge with vsCode. It is again a `.bat` file so the problem is also present with Korge Wrapper, giving the error:

`
Downloading https://github.com/korlibs/compiler.korge.org/releases/download/v0.1.1/korge-kotlin-compiler-all.tar.xz into C:\Users\PC\.korge\compiler\korge-kotlin-compiler-all.0.1.1.jar.tar.xz
Extracting C:\Users\PC\.korge\compiler\korge-kotlin-compiler-all.0.1.1.jar.tar.xz...
tar: Error opening archive: Can't initialize filter; unable to run program "xz -d -qq"
Error: Unable to access jarfile C:\Users\PC\.korge\compiler\korge-kotlin-compiler-all.0.1.1.jar
`

So i tried to extract the file manually but the file got deleted almos instantly after failing to extract. So i had to use the download url and extract it in the compiler folder. 

After that it ran succesfully. Only the installers seem to have this issue so far so i updated the title to include the wrapper as well

**Comment by elMuso** [comment]
Update: Installed Korge succesfully after deleting the empty `jre-21` folder in .korge, using 7zip to extract the .xz file twice, changing the output folder name to `jre-21` and running the installer command again.

**Comment by soywiz** [comment]
Which windows version are you using?

**Comment by elMuso** [comment]
Windows 10 Pro 22H2 19045.4651

**Comment by soywiz** [comment]
So xz support was added in Windows 11 then. But running tar --help can you see the supported formats somehow?

**Comment by elMuso** [comment]
Sadly no. It says it uses bdstar 3.5.2 that has it's source here https://github.com/libarchive/libarchive/releases/tag/v3.5.2 
I looked into the tests code but it seems that they silently fail according to the operating system


```
tar --help
tar(bsdtar): manipulate archive files
First option must be a mode specifier:
  -c Create  -r Add/Replace  -t List  -u Update  -x Extract
Common Options:
  -b #  Use # 512-byte records per I/O block
  -f <filename>  Location of archive (default \\.\tape0)
  -v    Verbose
  -w    Interactive
Create: tar -c [options] [<file> | <dir> | @<archive> | -C <dir> ]
  <file>, <dir>  add these items to archive
  -z, -j, -J, --lzma  Compress archive with gzip/bzip2/xz/lzma
  --format {ustar|pax|cpio|shar}  Select archive format
  --exclude <pattern>  Skip files that match pattern
  -C <dir>  Change to <dir> before processing remaining files
  @<archive>  Add entries from <archive> to output
List: tar -t [options] [<patterns>]
  <patterns>  If specified, list only entries that match
Extract: tar -x [options] [<patterns>]
  <patterns>  If specified, extract only entries that match
  -k    Keep (don't overwrite) existing files
  -m    Don't restore modification times
  -O    Write entries to stdout, don't restore to disk
  -p    Restore permissions (including ACLs, owner, file flags)
bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp
```


I have tried using the command with the compression that 7zip supports this gave me the following results


```
H:\tttt>tar -xvzf "H:\tttt\1.bz2"
tar: Error opening archive: Can't initialize filter; unable to run program "bzip2 -d"

H:\tttt>tar -xvzf "H:\tttt\2t.gz"
tar: Error opening archive: Unrecognized archive format

H:\tttt>tar -xvzf "H:\tttt\result.tar"
x result.txt

H:\tttt>tar -xvzf "H:\tttt\result.txt.xz"
tar: Error opening archive: Can't initialize filter; unable to run program "xz -d -qq"

H:\tttt>tar -xvzf "H:\tttt\result.wim"
tar: Error opening archive: Unrecognized archive format

H:\tttt>tar -xvzf "H:\tttt\result.zip"
x result.txt

H:\tttt>tar -xvzf "H:\tttt\result.7z"
x result.txt: LZMA codec is unsupported
tar: Error exit delayed from previous errors.
```

So only .tar and .zip worked for me. The library list test for compression types that are not familiar to me like .grz .lz4 .lzo and i was not able to test

**Comment by soywiz** [comment]
So I have included a small download on a xzdec that includes only xz/lzma2 decompression, and then pipeing with plain that that seems to be supported on Windows 10 and Windows 11
