### ISSUE TITLE
IntelliJ Plugin is missing

### ISSUE THREAD

**Issue by gmitch215** [korlibs/korge#2295]
Woke up to find that the IntelliJ plugin no longer exists.

Can't search for it, and the [direct link](https://plugins.jetbrains.com/plugin/9676-korge) reports a 404.

![image](https://github.com/user-attachments/assets/011c266b-075b-4fe9-af21-b9be7cd16beb)

**Comment by soywiz** [comment]
Korge plugin was removed from the marketplace as it was outdated.

There are three options now:
* Use https://forge.korge.org/
* Use Intellij without the Korge plugin. It is not required to use Korge with gradle
* If you are using an old intellij version compatible with the plugin: https://github.com/korlibs/korge-intellij-plugin/releases/tag/v4.0.4 here is a zip file you can install in IntelliJ
