### ISSUE TITLE
View solid rect has clipping errors on JS build

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#23]
A solid rect isn't completely filled on JS buid.
System: Korge 1.1.3 with latest KoreUI. Browser Chrome or Firefox.

To repoduce:
``` kotlin
suspend fun main() = Korge(debug = true , width = 256, height = 256, bgcolor = Colors.LIGHTGREY) {
    solidRect(256,256, Colors.BLUE)
    solidRect(100,100, color = Colors.GREEN)
}
```
![2019-03-05_20h48_14](https://user-images.githubusercontent.com/1190109/53834006-38a6c100-3f8a-11e9-97d5-2eb8c59f2059.png)

For me it's not a big problem, because don't have this situation where it's visible in my game.

**Comment by soywiz** [comment]
Can't reproduce this one. Maybe it is related to some gpu-specifc stuff? Do you have nvidia/amd? Have you set override settings or something like that? So it adds antialiasing even if the program doesn't request it?

**Comment by TobseF** [comment]
I have a NVIDIA GerForce GTX 970. I tried it on different browsers, resolutions and UI scaling. I also resetted 3D settings.  But you`re right, on my laptop there is no line. So it's a driver, hardware or software related problem. We can close this issue and hope I'm the only one with this glitch.
