### ISSUE TITLE
Sprite of bmpSlice uses the whole bmp

### ISSUE THREAD

**Issue by SerVB** [korlibs/korge#235]
From https://kotlinlang.slack.com/archives/CJEF0LB6Y/p1592670241351300:

I see when I try to paint a bmpSlice as a sprite, the whole bitmap is painted. This is the place in sources:

https://github.com/korlibs/korge/blob/17a24338a004082625bfdc0b7a440528a06d44d3/korge/src/commonMain/kotlin/com/soywiz/korge/view/Sprite.kt#L46-L52

My workaround currently is to call `bmpSlice.extract()`.

It's noticeable that for `image(bmpSlice)`, the behavior is good.

**Comment by emign** [comment]
I’ll investigate. Thanks for pointing it out
