### ISSUE TITLE
Updating text size on TextButton does not flush old text

### ISSUE THREAD

**Issue by emign** [korlibs/korge#237]
```
val t = TextButton(text = "Hallo").apply { textSize = 30 }
addChild(t)
```
<img width="160" alt="Korge_und_korge-hello-world-master_8_–_main_kt__korge-hello-world-master_8_commonMain_" src="https://user-images.githubusercontent.com/5278352/85281508-66b75980-b48a-11ea-93d5-e723ac73486c.png">

**Comment by RezMike** [comment]
It's a text shadow. You need to specify `shadowSize` separately:
```
textButton(text = "Hallo") {
    textSize = 30
    shadowSize = 30
}
```
Or you can disable shadow:
```
textButton(text = "Hallo") {
    textSize = 30
    shadowVisible = false
}
```
