### ISSUE TITLE
How to deal with memory leaks when using `VectorBuilder`?

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#24]
In my naive implementation I tried to render shapes in some kind of game loop. So I used the 
`VectorBuilder` to draw primitives like `VectorBuilder.rect(...)`. After playing around a mentioned that my JVM running game instance had a consumption of 10 GB of ram and a GPU consumption of 44%. This seems to be a little to much for my small retro console emulation game. And after running it in the browser and waiting a little, this Browser tab nearly froze my dev machine. So what did I wrong?

Let's extend the korge hallo world example wit that loop:
``` kotlin
launchImmediately {
    while (true) {
        for(i  in 0..1000){
            graphics {
                beginFill(Context2d.Color(Colors.RED))
                rect(1+i, 1+i, 100, 100)
                endFill()
            }
        }

    image.tween(image::rotation[minDegrees], time = 1.seconds, easing = Easing.EASE_IN_OUT)
    }
}
```
I thought this loop shouldn't have a memory leak. Begin, draw, end and before we reach the end, all drawing state should be cleared. But watching the memory speaks another language:

![2019-03-06_00h18_29](https://user-images.githubusercontent.com/1190109/53844390-d360c900-3fa5-11e9-9962-ec1410f47d50.png)
Thousands of `double[]`s are stored in `GraphicsPath` they are growing on every loop iteration.

So what's so wrong on this approach? Did I missed a dispose method which I have to call?

**Comment by soywiz** [comment]
`graphics { }` creates a `Graphics` view. So you are creating 1000 `Graphics` instances and attaching them to the stage each frame. So in two step of the loop there are 2000 Graphics in the stage.

```
val graphicsList = (0 until 1000).map { graphics() } // Create and attach 1000 instances
while (true) {
     graphicsList.fastForEachWithIndex { i, graphics ->
          // Update this Graphics instance (clear the paths, and add new paths)
          graphics.apply {
                clear()
                beginFill(Context2d.Color(Colors.RED))
                rect(1+i, 1+i, 100, 100)
                endFill()
         }
     }
    // tween
}
```

**Comment by TobseF** [comment]
Good point. I thought the view provides one Graphics. So I changed it to this:
``` kotlin
val graphics = graphics()
launchImmediately {
    while (true) {
        graphics.apply {
            clear()
            for (i in 0..1000) {
                beginFill(Context2d.Color(Colors.RED))
                rect(1 + i, 1 + i, 100, 100)
                endFill()
            }
        }

        image.tween(image::rotation[minDegrees], time = 1.seconds, easing = Easing.EASE_IN_OUT)
    }
}
```

Now the overhead is much less. But still grows during looping.

![2019-03-06_09h43_28](https://user-images.githubusercontent.com/1190109/53868226-e307fe00-3ff5-11e9-9dfa-aa6620109051.png)
![2019-03-06_09h50_54](https://user-images.githubusercontent.com/1190109/53868240-ea2f0c00-3ff5-11e9-9a97-7a7d9ead640a.png)

I also foreced GC, which doesn't change the heap. Are there more things I have to reuse or to clear?

**Comment by soywiz** [comment]
Note that the graphics API rasterizes the graphics each time it gets dirty creating a Bitmap instance. It doesn’t create polygons for the shapes but an image, so it is more or less costly.

But at any rate it shouldn’t produce any leak. Ill use the snippet you put and will compare HEAPs to see where is the leak

**Comment by TobseF** [comment]
``` kotlin
suspend fun main() = Korge(debug = true, width = 1024, height = 1024, bgcolor = Colors.LIGHTGREY) {
    addComponent(Game(this.graphics(), this))
}

class Game(private val graphics: Graphics, override val view: View) : UpdateComponent {

    override fun update(ms: Double) {
        graphics
        graphics.apply {
            clear()
            for (i in 0..1000) {
                beginFill(Context2d.Color(Colors.RED))
                rect(1 + i, 1 + i, 100, 100)
                endFill()
            }
        }
    }
}
```
In this way you can reproduce it much faster, because the render update is triggered more often than in the example above.

**Comment by TobseF** [comment]
As a workaround of the poor shape performance and the memory leaking, I cache all shapes as Image. Now the memory stays nearly constant. Thanks for his hint!

**Comment by soywiz** [comment]
I guess this happens because how KorGE handles textures. Instead of destroying textures immediately, KorGE does a GC each 60 frames:
https://github.com/korlibs/korge/blob/d8970564461656382825d9d10a7aa408808352c8/korge/src/commonMain/kotlin/com/soywiz/korge/render/AgBitmapTextureManager.kt#L36

**Comment by soywiz** [comment]
Fixed here https://github.com/korlibs/korge/commit/1975a56d7df3c719ebb4256cab06cbbc70101f08
