### ISSUE TITLE
No audio after packing `packageJvmFatJar`

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#26]
After packing the app as JVM fat jar by the `packageJvmFatJar` task, mp3 audio files won't play anymore. No error are thrown. The fat jar includes the `com.soywiz.korau.format.mp3.MP3Decoder`. So I can't figure out what's going wrong. Is there any thing else, I have to configure for fat jar, when including **korau**?

Setup: korge-hello-world

**build.gradle.kts**
``` kotlin
korge {
    dependencyMulti("com.soywiz:korau-mp3:$korauVersion")
}
```

**main.kt**
``` kotlin
suspend fun main() = Korge(debug = true, width = 512, height = 512, bgcolor = Colors.LIGHTGREY) {
    val sound = resourcesVfs["sounds/ok.mp3"].readNativeSound()
    solidRect(100, 100, Colors.RED) {
        onClick {
            sound.play()
        }
    }
}
```
System: Win 10, x64

**Comment by soywiz** [comment]
Moved here: https://github.com/korlibs/korge-plugins/issues/2 since this is probably something lost when packing via gradle
