### ISSUE TITLE
Red images

### ISSUE THREAD

**Issue by leadpogrommer** [korlibs/korge#268]
Every image i create becomes red.
For example, here is screenshot of Korge HelloWorld.
![image](https://user-images.githubusercontent.com/42062111/87224801-6e478f80-c3b2-11ea-8262-d8e312a8ea34.png)

Target: jvm
OS: ArchLinux
Program Output:
screenWidth: 3840, screenHeight: 1080, winX=1664, winY=284, width=512, height=512
VI: native@0x7fdb38805b00, d: native@0x7fdb387e2740 (com.sun.jna.platform.unix.X11$Display@387ea71b), w: 0x7800001, glc: native@0x7fdb38805d90
GL_VENDOR: X.Org
GL_VERSION: 4.6 (Compatibility Profile) Mesa 20.1.3
GL_EXTENSIONS: 302
OpenglAG: Created program BatchBuilder2D.Premultiplied.Tinted with id 1 because contextVersion: -1 != 0
GameWindow.close
GameWindowCoroutineDispatcher.close
GameWindow.close
GameWindowCoroutineDispatcher.close

**Comment by soywiz** [comment]
Maybe blue channel is interchanged with the alpha channel?

Is that a x64 intel/amd cpu? is little endian? can you reproduce that in a virtual machine where I can try?

**Comment by leadpogrommer** [comment]
My CPU is AMD Ryzen 5 4600H, it is little endian.
I was unable to reproduce this bug inside virtual machine (I tried Ubuntu 20.04 inside Virtualbox)
Maybe it is somehow related to my integrated amd graphics? Can I somehow test it in software rendering mode?

**Comment by soywiz** [comment]
Using ArchLinux on a virtualmachine doesn't reproduce the issue either? runJs works well I suppose, right?

**Comment by leadpogrommer** [comment]
Yes, runJs works fine, I will try Arch tomorrow

**Comment by soywiz** [comment]
Also if you can try `./gradlew runNativeDebug` would be nice

**Comment by soywiz** [comment]
Relevant links:
* https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml
* https://github.com/korlibs/korgw/blob/e6aebe811a6a7b9c252ca3d82a3480859c8df34f/korgw/src/commonMain/kotlin/com/soywiz/korag/OpenglAG.kt#L91

Maybe we have to adjust https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPixelStore.xhtml or packing somehow. But it should work the same by default on all the targets

**Comment by leadpogrommer** [comment]
Yes, Arch on VM does not reproduce the issue, and yes, runJs works fine

**Comment by leadpogrommer** [comment]
Arch inside VM doesn't reproduce the issue
`./gradlew runNativeDebug` gives following errors:
`ld.lld: error: unable to find library -lopenal
ld.lld: error: unable to find library -lGL
ld.lld: error: unable to find library -lGLU
ld.lld: error: unable to find library -lglut
ld.lld: error: unable to find library -lX11`
despite that I have those libs installed

**Comment by soywiz** [comment]
I think other people had issues finding the development libraries on native on arch. Not sure how to fix the issue. Maybe we can allow to provide envs to set the library paths ?

**Comment by leadpogrommer** [comment]
I haven't libgl.a in my system. There are only .so files and headers.

**Comment by soywiz** [comment]
I just checked and it seems that I don't have .a files for libGL either. but I have libGLU.a and libGL.so.

In ubuntu:
```
/usr/lib/x86_64-linux-gnu/libGL.so
/usr/lib/x86_64-linux-gnu/libGLU.a
/usr/lib/x86_64-linux-gnu/libGLU.so
/usr/lib/x86_64-linux-gnu/libopenal.so
/usr/lib/x86_64-linux-gnu/libX11.a
```

---

```
sudo ldconfig -v 2>/dev/null | grep ':$' |sed -e 's/://'

/usr/lib/x86_64-linux-gnu/libfakeroot
/lib/i386-linux-gnu
/usr/local/lib
/lib/x86_64-linux-gnu
/lib32
/lib
```

**Comment by soywiz** [comment]
Things to try:

## Download this repo
https://github.com/korlibs/korgw/compare/fix/try.to.fix.red.image.issues?expand=1

```
git clone https://github.com/korlibs/korgw.git
git checkout try.to.fix.red.image.issues
./gradlew publishToMavenLocal
```

go to your hello world sample, and edit the `gradle.properties` with:
`korgwVersion=10-SNAPSHOT`

this will load your local changes.
You can try adjusting this lines alternating between TRUE and FALSE and recompiling and try to see if something changes:
https://github.com/korlibs/korgw/blob/8117f3564439b2017d8897ebafd830eaec3f49b8/korgw/src/commonMain/kotlin/com/soywiz/korag/OpenglAG.kt#L738-L739

## Try to not use the native image loader

```
resourcesVfs["korge.png"].readBitmap()
->
resourcesVfs["korge.png"].readBitmapNoNative(PNG)
```

## Java version

Which java version are you using? It is openjdk? java 8?

```
java -version
```

**Comment by leadpogrommer** [comment]
1. I tried every four combinations of those parameters, and nothing changed.
2. The only difference with noNative image loader is that whole image now red, instead of only it's opaque parts.
3. 
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10)
OpenJDK 64-Bit Server VM (build 11.0.7+10, mixed mode)

**Comment by leadpogrommer** [comment]
I've just realised that not only images are red --- everything is red.
![image](https://user-images.githubusercontent.com/42062111/87246516-22f7b480-c478-11ea-83e0-fb7992882144.png)
The code is
```
    val circle = circle(radius = 50.0, color = Colors.YELLOW).xy(100, 100);   
    val circle1 = circle(radius = 50.0, color = Colors.GREEN).xy(150, 100);
```

**Comment by soywiz** [comment]
Vector shapes are rasterized into images and uploaded as textures.
Must be something related to texture uploading. But if cannot reproduce myself it would be a problem.

I can try to reproduce it in an old laptop if you tell me the exact distro and config so I can install it

**Comment by leadpogrommer** [comment]
Please tell me what config do you want?

**Comment by soywiz** [comment]
Which Arch version (ideally the iso file to download) and if you installed something special relevant to this. For example how did you installed X11 if not available with the distro initially etc.

**Comment by Delorran** [comment]
I have the exact same problem with an up-to-date Fedora 32.
Same problems with the native target. I tried installing the missing libraries but that didn't help.
I am also missing the libGL.a, libGLU.a, etc.

Output for the example:
```
VI: native@0x7f7e9c8d31d0
screenWidth: 3840, screenHeight: 1080, winX=1664, winY=284, width=512, height=512
Preparing OpenGL context. Screen: 0
VI: native@0x7f7e9c8d31d0
d: native@0x7f7e9c8b3080 (com.sun.jna.platform.unix.X11$Display@9c8baffe), w: 0xbc00001, s: 0, VI: native@0x7f7e9c8d31d0, glc: native@0x7f7e9c8d3750
GL_RENDERER: 'AMD Radeon RX 5700 (NAVI10, DRM 3.37.0, 5.7.9-xanmod1, LLVM 10.0.0)'
GL_VENDOR: 'X.Org'
GL_VERSION: '4.6 (Compatibility Profile) Mesa 20.1.3'
GL_EXTENSIONS: 303
swapIntervalEXT: Proxy interface to native function@0x7f7e6c027790 (com.soywiz.korgw.x11.X11GameWindow$glXSwapIntervalEXTCallback)
```
Of course I also tested it with the standard version of the kernel

**Comment by soywiz** [comment]
I guess building the native version should be possible to be reproduced in a virtual machine. But I don't know if it will be the case with that graphics issue. It seems to happen on AMD graphic cards or something? I don't see any antialiasing on the images. So maybe its an issue where only allocates 1 bit per component or something like that?

**Comment by soywiz** [comment]
I'm going to try in an ancient laptop with Intel Pentium and Amd Radeon with Fedora 32. Let's see if I can reproduce the issue.

**Comment by soywiz** [comment]
Was not able to reproduce that issue in that machine sorry :( guess someone will have to figure out what's going on.

Maybe you can download the `korge-next` repository with all the libraries compiled together and try to adjust these lines:
https://github.com/korlibs/korge-next/blob/015621115e0eff5e971a4467254ece55e7680d52/korgw/src/linuxX64Main/kotlin/com/soywiz/korgw/X11GameWindow.kt#L36-L80

To try the changes you can run the hello world sample in that repo:

```
./gradlew :korge-hello-world:runJvm
```

**Comment by soywiz** [comment]
Can you try this repo:

https://github.com/korlibs/korge-next

like this:

```
git clone https://github.com/korlibs/korge-next.git
cd korge-next
./gradlew :samples:hello-world:runJvm
```

I have adjusted the glXChooseVisual here: https://github.com/korlibs/korge-next/commit/1a20976b8630ccd0c054673cdb19a982b293e7a7 and maybe it helps

**Comment by Delorran** [comment]
Unfortunately it did not work.
Terminal output:

> \> Task :samples:hello-world:runJvm
> NOT Using DisplayLink
> running: Thread[main,5,main]
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.soywiz.korgw.internal.MicroDynamic (file:/home/***/korge-next/korgw/build/libs/korgw-jvm-20-SNAPSHOT.jar) to method sun.awt.AWTAccessor.getComponentAccessor()
> WARNING: Please consider reporting this to the maintainers of com.soywiz.korgw.internal.MicroDynamic
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> VI: native@0x7fab6c090d30 (doubleBuffer=true, depth=24, bitsPerColorComponent=8, specifyRenderType=true)
> Preparing OpenGL context. Screen: 0
> VI: native@0x7fab6c090d30
> d: native@0x7fab6c04b930 (com.sun.jna.platform.unix.X11$Display@6c0538db), w: 0xb40001c, s: 0, VI: native@0x7fab6c090d30, glc: native@0x7fab6c07d870
> GL_RENDERER: 'AMD Radeon RX 5700 (NAVI10, DRM 3.37.0, 5.7.10-xanmod1, LLVM 10.0.0)'
> GL_VENDOR: 'X.Org'
> GL_VERSION: '4.6 (Compatibility Profile) Mesa 20.1.4
> GL_EXTENSIONS: 303
> swapIntervalEXT: Proxy interface to native function@0x7faba7033790 (com.soywiz.korgw.x11.X11GameWindow$glXSwapIntervalEXTCallback)
> prepareTexImage2D

![image](https://user-images.githubusercontent.com/22118145/89016111-71ca9880-d318-11ea-9da2-89873223da0e.png)

**Comment by soywiz** [comment]
Since I cannot reproduce it on any of my hardware, can some of you be kind enough to allow me a small remote code session so I can figure out what's going on?

**Comment by leadpogrommer** [comment]
I was able to bypass this issue by running program on discrete nVidia GPU.

**Comment by soywiz** [comment]
Still would be nice to reproduce and fix the issue. I would need help here. Either someone knowing opengl having the issue to look at it or someone that can do a remote coding sessions sharing he screen a few hours

**Comment by nanodeath** [comment]
What happens if you try running with the `MESA_LOADER_DRIVER_OVERRIDE=i965` environment variable set? Solved a similar graphics corruption issue on Fedora for me.

**Comment by leadpogrommer** [comment]
I've got black screen.

**Comment by sojuz151** [comment]
Same problem, also on Arch. Seams to be something to do with AMD drivers.  I could let you use my laptop over some remote desktop app if that would help solve this problem.

**Comment by soywiz** [comment]
@sojuz151 that will help. Can you join discord or slack so we can discuss how to do that?

**Comment by soywiz** [comment]
Thank you very much @sojuz151 for letting me to make a remote session with your computer to fix this!!

![](https://media2.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif)

**Comment by soywiz** [comment]
Just in the case you are curious about the issue:

This was an issue that the shader when performing tinting was using a packed normalized color. 4 bytes per color: 0xRRGGBBAA. Normalization helps to convert `0..255` range into `0f..1f` range.

This is the function to specify the vertex attribute:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml

Notice the `GLboolean normalized` argument.
`Glboolean` is usually GL_FALSE (0) or GL_TRUE (1).

I used boolean on JNA, but it seems that JNA convert false to 0 and true to -1 (0xFFFFFFFF).
I bet that most drivers doesn't care and just do:

```
if (normalized) {
    ...
} else {
   ...
}
```

but probably your driver was doing something like:

```c
if (normalized == GL_TRUE) { // -1 == 1? NO!
   // not normalizing
} else if (normalized == GL_FALSE) { // -1 == 0? NO!
  // not normalizing
} else { // invalid parameter 
 // error and not doing anything with the attribute. Probably sets the vector to 1f, 0f, 0f, 1f, so you clearly see that the code is wrong
}
```
