### ISSUE TITLE
No clicking with JS

### ISSUE THREAD

**Issue by voidpointerdev** [korlibs/korge#27]
(Using Firefox)
I made a test program to help me get a little KorGE, and failed. The program works 100% on the JVM, but not on JS. You can't click the button.
![image](https://user-images.githubusercontent.com/43734540/55281363-9e1f7080-52f0-11e9-89e3-c110d327969a.png)
What happens on the JVM:
![image](https://user-images.githubusercontent.com/43734540/55281367-b099aa00-52f0-11e9-8c1d-cb2d47af216f.png)
Nothing on JS. The button screen stays.
I also noticed, In _the examples_ on the website, I could only click on buttons/mouse input with my _touchscreen_... No idea why.

My Code:
```
import com.soywiz.korge.*
import com.soywiz.korge.input.*
import com.soywiz.korge.view.*
import com.soywiz.korim.color.*
import com.soywiz.korim.format.*
import com.soywiz.korio.file.std.*

suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors["#2b2b2b"]) {
	//val minDegrees = (-16).degrees
	//val maxDegrees = (+16).degrees
	val image = image(resourcesVfs["button.png"].readBitmap()) {
		//rotation = maxDegrees
		anchor(.5, .5)
		scale(.8)
		position(256, 256)
		val bmp2 = resourcesVfs["korge.png"].readBitmap()
		onClick {
			this.parent?.image(bmp2) {
				//rotation = maxDegrees
				anchor(.5, .5)
				scale(.8)
				position(256, 256)
			}
			this.removeFromParent()
		}
	}
}
```

**Comment by Indi-Code** [comment]
Demos work with MS Edge. No Firefox
My hit the button dosent though

**Comment by soywiz** [comment]
Can you press f12 to toggle debug mode and see how the x and y values change?

**Comment by Indi-Code** [comment]
They don't at all on firefox

**Comment by soywiz** [comment]
Tried to reproduce this this weekend without luck. Do you have a touchscreen by chance?
I will try this week on a touchscreen device with firefox to see if I can reproduce it.

**Comment by Indi-Code** [comment]
Yes @soywiz . Running on a Fujitsu T902 touchscreen laptop. Windows 10 Pro.

**Comment by Indi-Code** [comment]
Tried on a different non touchscreen pc. Same thing. No clicking

**Comment by Indi-Code** [comment]
You appear to have fixed it - GJ!
