### ISSUE TITLE
Black rectangles sometimes appear when running AndroidDeviceDebug

### ISSUE THREAD

**Issue by ryuryu-ymj** [korlibs/korge#279]
While running AndroidDeviceDebug, black rectangles sometimes appear on game window.
When I run the game on Android device, and move to Overview (press square button in navigation bar), then resume the game, sometimes some Views become black rectangle.
Maybe this phenomenon can be seen on most games made with KorGE, for example on the 2048 sample game.
My Android version is 8.0.0, and KorGE version is 1.12.2.2.

**Comment by soywiz** [comment]
Happens sometimes on the intellij plugin on linux at least. I have to figure out if it is an issue when detecting the context loss or when reuploading the textures. Since it seems to draw something I think the shader programs are restored correctly.

**Comment by mnonnenmacher** [comment]
I also very often get those black rectangles when resuming my game on Android. It's completely random which elements become black, sometimes it's bitmaps or bitmap fonts, sometimes shapes like `roundRect`. Often the elements become black not immediately after resume, but about a second later. There are no exceptions or other log output that seem to be related to the issue.
I use KorGE 1.15.0.0 on Android 10.
