### ISSUE TITLE
Overlapping contexts

### ISSUE THREAD

**Issue by AllanWang** [korlibs/korge#281]
A lot of the DSL are formatted like `T.() -> Unit`, resulting in overlapping variables:

![image](https://user-images.githubusercontent.com/6251823/91547609-08b75000-e8d9-11ea-96aa-b8ad50f4e94f.png)

![image](https://user-images.githubusercontent.com/6251823/91547626-0fde5e00-e8d9-11ea-8661-542e960d14a0.png)

attached are test methods called within `graphics`. Note that just be adding

```kt
(this as EventDispatcher).mouse {
   down { this.x }
}
```

The underlying `mouse` function changes.

Without it, it uses `x: Double` from View
With it, it uses `x: Int` from `MouseEvent`

Calling `Point` hides this change since it supports all numbers

Even if the desired use case it to better split functions to avoid overlapping contexts, I believe that the current state makes it difficult to debug problems for beginners (myself included).

**Comment by AllanWang** [comment]
By running the app, I see that `this as EventDispatcher` is invalid. It's weird to me that there is no IDE warning that the cast isn't possible, given that the type inference knows it's `Graphics`

**Comment by soywiz** [comment]
The problem is that the Stage is an EventDispatcher, while the rest of the views are not (we started using components instead for event handling). Since we use the DSL you get access to the stage too when using the DSL. We will revisit some of the APIs on KorGE 2.0
