### ISSUE TITLE
OutOfMemoryError when loading BitmapFont on Android

### ISSUE THREAD

**Issue by mnonnenmacher** [korlibs/korge#282]
I'm getting an `OutOfMemoryError`when loading a `BitmapFont` on Android. The stacktrace is:

```
java.lang.OutOfMemoryError: Failed to allocate a 134217848 byte allocation with 8388608 free bytes and 91MB until OOM, target footprint 180741392, growth limit 268435456
        at com.soywiz.kds.IntMap.<init>(IntMap.kt:27)
        at com.soywiz.kds.IntMap.grow(IntMap.kt:33)
        at com.soywiz.kds.IntMap.set(IntMap.kt:113)
        at com.soywiz.kds.IntMapKt.toIntMap(IntMap.kt:273)
        at com.soywiz.korim.font.BitmapFontKt.readBitmapFontTxt(BitmapFont.kt:266)
        at com.soywiz.korim.font.BitmapFontKt.readBitmapFont(BitmapFont.kt:195)
        at com.soywiz.korim.font.BitmapFontKt.readBitmapFont$default(BitmapFont.kt:188)
        ...
```

The problem seems to be that the [calculated capacity](https://github.com/korlibs/kds/blob/a27caf187d5a9e0b1e26f53d660345152652024c/kds/src/commonMain/kotlin/com/soywiz/kds/IntMap.kt#L19) for the `IntMap` created [here](https://github.com/korlibs/korim/blob/653b34075f6ee48916af7c68e6b07445b26e00f8/korim/src/commonMain/kotlin/com/soywiz/korim/font/BitmapFont.kt#L266) seems to be far too high. I have checked some values of the created `IntMap` using the debugger. The size of the input map is 717, which in the last call of the `grow()` function results in `nbits==22` and `capacity=33554432`.

If I run the game on the JVM the memory usage with the four `BitmapFont`s I load is 1.6GB, without them it is only 0.22GB.

**Comment by soywiz** [comment]
Can you provide the bitmapfont reproducing the issue?

**Comment by mnonnenmacher** [comment]
This contains a few variants of Roboto Regular created using Hiero with the extended charset:
[roboto-regular.zip](https://github.com/korlibs/korge/files/5146137/roboto-regular.zip)

**Comment by soywiz** [comment]
@RezMike can you look at this? If you can't let me know, and I will check at some point

**Comment by RezMike** [comment]
@soywiz, I'm afraid I don't have enough experience with bitmap fonts and image handling to fix it quickly

**Comment by soywiz** [comment]
Doesn't seems related to bitmap fonts, but it seems to be a bug on the kds IntMap that is generating a pretty big backing array.

**Comment by RezMike** [comment]
@soywiz, well, if so, I can check it later

**Comment by soywiz** [comment]
Nice. Ty

**Comment by RezMike** [comment]
> it seems to be a bug on the kds IntMap that is generating a pretty big backing array

Yeah, I just saw the implementation of IntMap, and I have a few questions about it that we should discuss later. I'll write to you @soywiz in slack later.
