### ISSUE TITLE
Got this:"WARNING: Please consider reporting this to the maintainers of com.soywiz.korgw.internal.MicroDynamic"

### ISSUE THREAD

**Issue by Lykdraft** [korlibs/korge#286]
This happens: 

```
 Task :runJvm
Using DisplayLink
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.soywiz.korgw.internal.MicroDynamic (file:/Volumes/HDD2/Luetze/.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.korgw/korgw-jvm/1.12.25/a0444142783a2b04d223f7a8798e470e058c5db2/korgw-jvm-1.12.25.jar) to method com.apple.eawt.FullScreenUtilities.setWindowCanFullScreen(java.awt.Window,boolean)
WARNING: Please consider reporting this to the maintainers of com.soywiz.korgw.internal.MicroDynamic
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

after running this code:

```
suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors["#2b2b2b"]) {
	solidRect(100, 100, Colors.RED)
}
```

BTW: I've seen this more than once now but not regularly.

**Comment by soywiz** [comment]
Hey Lykdraft, thanks for reporting the issue. We are aware of the issue and unfortunately it seems we cannot do anything about that. To change the fullscreen state on mac requires an API that is not exposed publicly so we need to do a reflective access that is deprecated in newer versions of Java. Though If you are aware of a way of circumvent this, please let us know.

**Comment by Lykdraft** [comment]
I see. Well, then I am not sure if it is useful to leave this issue open.

**Comment by soywiz** [comment]
Yeah, if you don't have any suggestion here to get rid of the issue, let's close this. If at some point you figure out a way to overcome this, don't hesitate to comment here and reopen the issue. Again, thanks for reporting and have a nice day
