### ISSUE TITLE
    myArray.shuffle() --> not working in KorGE (but working in Kotlin)

### ISSUE THREAD

**Issue by Lykdraft** [korlibs/korge#287]
This code:

```
    var myArray = intArrayOf(10,20,30)
    myArray.shuffle()
```

doesn't work in KorGE.
When creating a project with **project -> new -> Kotlin** it works.
When creating a project with **project -> new -> KorGe** it doesn't.
Any idea why? Or how to fix this?

Thanks,
tL.

**Comment by Lykdraft** [comment]
(.shuffle() is red and shows an 'unresolved reference error')

**Comment by Lykdraft** [comment]
Full problem description from the terminal:
```

Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public expect fun <T> MutableList<???>.shuffle(): Unit defined in kotlin.collections
public expect fun <T> MutableList<???>.shuffle(): Unit defined in kotlin.collections
public fun <T> MutableList<???>.shuffle(random: Random): Unit defined in kotlin.collections
public fun <T> MutableList<???>.shuffle(random: Random): Unit defined in kotlin.collections
```

**Comment by soywiz** [comment]
Looks like two incompatible libraries loaded. I'll check.

**Comment by soywiz** [comment]
I guess this is probably not an issue anymore. Feel free to reopen if it is the case
