### ISSUE TITLE
Does text support other language?

### ISSUE THREAD

**Issue by yayachang** [korlibs/korge#288]
I use Chinese or Japanese word

text = "謝謝"  or
text = "ありがとうございました"  in code. 
But it can't display

Any method to display them?

**Comment by soywiz** [comment]
It should, but maybe something is missing. How are you trying to display the text? Are you using a TTF font, or a Bitmap Font? The default embedded font only have latin-1 characters

**Comment by yayachang** [comment]
Thanks for your reply. 
I try Chinese TTF font and it works!

**Comment by soywiz** [comment]
Nice to know. I guess unicode 16-bits 0000-FFFF should work. That should include all the characters available in chinese and japanese, but won't include extended characters like emoji.
Closing the issue, feel free to reopen if required
