### ISSUE TITLE
KorGe native release compilation ---> self contained not possible?

### ISSUE THREAD

**Issue by Lykdraft** [korlibs/korge#289]
Hey there,

when I compile to native and send the app, no one is able to open it because of 
missing library errors. How can that be? I was under the impression that a Korge app
compiled to native is selfcontained, no?

Here's a picture a friend made to show what happens when he tries to open it:

![IMG_4534](https://user-images.githubusercontent.com/18437561/93469268-8d055d80-f8f0-11ea-9215-74e872fb7036.jpg)

**Comment by soywiz** [comment]
What a strange error. KorGE is standalone, only linked to OpenGL and CoreAudio and as much OpenAL, and the rest is Kotlin-Native compiler using LLVM compiling stuff. So that error is super strange.

Can you use otool and print the dependencies it contains?:
``` 
otool -L path/to/executable
```

**Comment by Lykdraft** [comment]
Gives me this:


```
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1673.126.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libcompression.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libate.dylib (compatibility version 1.0.0, current version 2.0.9)
	/usr/lib/libbsm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1348.12.4)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1894.10.126)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 1000.0.0)
```

**Comment by soywiz** [comment]
To have more information:

Which macos version did you use to compile the program, and which version failed to run it?

**Comment by Lykdraft** [comment]
Compiled on 10.14.6
Not sure on which this was run, but at least one major version back, if not maybe two.
I need to ask. I thought this would fail to run, but usually we get a  'needs newer OS version'  message 
so I am confused by this error report.

**Comment by soywiz** [comment]
Yeah, that's strange. Also likely not related to korge, but to Kotlin/Native or LLVM. I'm going to open an issue there and reference to this issue.

**Comment by soywiz** [comment]
I'm creating the issue. Please if you can ask, that will help to try to reproduce the issue with a virtual machine or something

**Comment by soywiz** [comment]
https://youtrack.jetbrains.com/issue/KT-41999

**Comment by Lykdraft** [comment]
Ok thanks, yeah, will do so and then report back.

**Comment by Lykdraft** [comment]
Another thing: Any assets won't get embedded in the app, right?
At least there seems no way to do that AFAIK.

**Comment by Lykdraft** [comment]
Alright, so the operating system where the error was triggered is actually 10.11.
I didn't know that it was that old.  

I will try to check again on a mac that has at least 10.12 or maybe 10.13.

However: Shouldn't the .png image from the KorGE basic init project for example
be embedded as well in a selfcontained native compilation?  

> Another thing: Any assets won't get embedded in the app, right?
> At least there seems no way to do that AFAIK.

After compilation of the basic KorGE init project the  .png is still a separate file and needs to be besides the app to be found. When I delete it, it won't show up in the app.
When compiling to .jar there's no need for that.It is embedded there.

So I am not sure if this has anything to do with the OS of anyone I might send it to?

**Comment by soywiz** [comment]
@Lykdraft assets are copied into the macOS `.app` automatically, and the `resourcesVfs` global property allows you to access them as usual.
In the case of linux and windows, they are not embedded, just copied along the executable. MacOS `.app` is a folder in the end, so it works fine as a bundle.

Right now there is no way to embed the resources on windows or linux executables.

A trick could be to add a small filesystem or zip file at the end of the executable that could be a separate issue, but won't work if you strip the exe.

**Comment by Lykdraft** [comment]
This is what I mean. I am on OSX and the .png is still there. NOT embedded into the Mac  OSX app.

**Comment by Lykdraft** [comment]
After compilation on OSX 10.14.6, this:

> After compilation of the basic KorGE init project the .png is still a separate file and needs to be besides the app to be found. When I delete it, it won't show up in the app.
> When compiling to .jar there's no need for that.It is embedded there.

So you say this shouldn't happen, right?

**Comment by soywiz** [comment]
Which task are you using? There is a task generating the executable, then another task generating the .app bundle including the executable, the icon, and the resources all together.

If you are having trouble with this and using the task generating the .app, you are welcome to join the slack or discord channels, so we can figure out what's going on

**Comment by Lykdraft** [comment]
No, alright, I got it, I was looking at the wrong folder.

**Comment by soywiz** [comment]
@Lykdraft It seems that it is a current limitation of Kotlin/Native compiler. It seems that it requires MacOS 10.12 as least

https://youtrack.jetbrains.com/issue/KT-41999#focus=Comments-27-4399129.0-0
> Artyom Degtyarev commented 11 minutes ago
> Hello, @Carlos Ballesteros Velasco! Thank you for the report. According to [this comment](https://github.com/korlibs/korge/issues/289#issuecomment-694288988), the problem is related to > Kotlin/Native missing OSX 10.11 support(see [GH-1025](https://github.com/JetBrains/kotlin-native/issues/1025)). As I cannot find any related issues in YouTrack, lets consider this one as a mirror for the GH-1025

**Comment by Lykdraft** [comment]
Alright, that's reasonable. 10.11 is very old anyways. Cool that it still supports 10.12
though. I consider this solved.
Thanks!
