### ISSUE TITLE
[Feature Request] Package assets in native

### ISSUE THREAD

**Issue by voidpointerdev** [korlibs/korge#29]
Basically put all the assets, which currently need to be in the same folder as the executable, *in* the executable.

**Comment by soywiz** [comment]
Would be possible to do using either:
https://github.com/JetBrains/kotlin-native/blob/61bed4965da3ecd2da2bef67327a3936c7fee5ad/runtime/src/main/kotlin/kotlin/native/Blob.kt#L86

Or inside Hexadecimal, or base64 strings. Appending an embedding filesystem at the end of the exe file usually also works but that's much more hacky.

**Comment by soywiz** [comment]
Moved to https://github.com/korlibs/korge-plugins/issues/1 since this could/should be implemented via gradle with an additional .kt file
