### ISSUE TITLE
onClick Listener doesn't register click when mouse is moved even a little bit inbetween click and release...

### ISSUE THREAD

**Issue by Lykdraft** [korlibs/korge#290]
So here's the problem:

The onClick listener only registers a click when you don't move the mouse cursor 
between click and release. Even if it is only a tiny little bit in a very
short amount of time. (I am not talking about long drags or something like that...)
This really isn't good for UX.

I don't know yet if this is also the behaviour in the final build.
I just used --runJvm for now inside IntelliJ.
Maybe when compiled this might behave differently?  

Best
tL.

_(I double-checked this with a uiButton and also with an onClickListener added to a circle.
Same behaviour...)_

**Comment by Lykdraft** [comment]
Small Demo:

![mouse](https://user-images.githubusercontent.com/18437561/93646811-40607600-fa07-11ea-85e5-b39dc826507b.gif)

**Comment by tradfursten** [comment]
I ran in to this problem as well and solved it by using onUp instead of onClick. That solved my small usecase.

**Comment by soywiz** [comment]
Traditionally the click event was emulated on mouse release when a threshold of time and distance happened.
But I see that right now it uses the CLICK event on the JVM as you can see here: https://github.com/korlibs/korgw/blob/f9f9a34a5ce421e7f0278243d257ba68ded1c973/korgw/src/jvmMain/kotlin/com/soywiz/korui/native/AwtComponent.kt#L148

So I guess that threshold is determined by the operating system and it is not bound to a view, so yeah, I think the UP event should work better in your cases. I'm closing the issue, but if you have an alternate suggestion to fix the issue, let me know
