### ISSUE TITLE
TileMap Color component swap problem

### ISSUE THREAD

**Issue by Suragul** [korlibs/korge#291]
Tried to make a game level with tileMaps but there are different results in PC and android:
PC
https://media.discordapp.net/attachments/728616340239417375/757992950067363910/tileMap3.png?width=832&height=468
Android
https://media.discordapp.net/attachments/728616340239417375/757992984829493359/Screenshot_2020-09-22-20-50-07.png?width=281&height=468
That happens only with tilemap. My device model Samsung Galaxy J1 SM-J120F.  Version of Android 5.1.1.

**Comment by soywiz** [comment]
Thanks for creating the issue @Suragul I'll investigate
