### ISSUE TITLE
Usa as a subview within an Android application.

### ISSUE THREAD

**Issue by lowwor** [korlibs/korge#292]
Just like this proposol in godot. [https://github.com/godotengine/godot/pull/39558](https://github.com/godotengine/godot/pull/39558)
Anyway we can use korge as a subview within an Android application?

**Comment by soywiz** [comment]
https://github.com/korlibs/korgw/pull/30

**Comment by soywiz** [comment]
Was supported here: https://github.com/korlibs/korge/blob/f1093f1506f3cf34f93694d4c84d6167c75e7038/korge/src/androidMain/kotlin/com/soywiz/korge/android/KorgeAndroidView.kt
