### ISSUE TITLE
admob android occur error

### ISSUE THREAD

**Issue by yayachang** [korlibs/korge#293]
I had added korge { admob("XXXXXXX") // Shortcut for admob} in build.gradle.kts

AdmobCreate(testing = true).bannerShow() in my main.kt and Splash.kt file

then do gradle installAndroidDebug to install in my android

but android:compileDebugKotlin FAILED

src/commonMain/kotlin/main.kt: (2, 25): Unresolved reference: admob
src/commonMain/kotlin/main.kt: (32, 24): Unresolved reference: AdmobCreate
src/commonMain/kotlin/scene/Splash.kt: (6, 25): Unresolved reference: admob
src/commonMain/kotlin/scene/Splash.kt: (77, 9): Unresolved reference: AdmobCreate

**Comment by soywiz** [comment]
On discord an user is using it successfully, so I think this shouldn't be happening anymore. Feel free to reopen again if it is not the case for you. You should include it from awesome.korge.org: https://awesome.korge.org/
