### ISSUE TITLE
Draggable doesn't move views 1:1 with mouse movement when virtual stage dimensions differ

### ISSUE THREAD

**Issue by nanodeath** [korlibs/korge#295]
**Expected:** if I set a virtual height and/or width when I initialize KorGE, I expect draggable items to still move 1:1 with the dragging mouse.
**Actual:** if I set the virtual height and width to be double my height and width, draggable items move at half speed when dragged.

KorGE version: 1.15.0.
Platforms tested:
* JVM: Shows the problem as described
* JS: Uh, the JS target is all sorts of messed up -- I think because the viewport is stretched to the size of the window, so even if virtual height equals height it also gets rather out of sync.

I've attached a [SSCCE](http://sscce.org/) based on the Hello World app.

[korge_draggable_virtual_bug.zip](https://github.com/korlibs/korge/files/5368939/korge_draggable_virtual_bug.zip)

**Comment by nanodeath** [comment]
FWIW, if I change [these lines](https://github.com/korlibs/korge/blob/e76caff8e1792bce43d8e1ac148d0d319b4d2ef3/korge/src/commonMain/kotlin/com/soywiz/korge/input/MouseDragComponent.kt#L38-L39) in MouseDragComponent to `globalMouseX`/`globalMouseY` it seems to fix the problem.

**Comment by soywiz** [comment]
Yeah, also we should probably transform the global coordinates into coordinates local to the subject view parent
