### ISSUE TITLE
SVG Image scale losing quality

### ISSUE THREAD

**Issue by MitchDart** [korlibs/korge#296]
Not sure if I should be posting this here or at the korim lib. It seems like the problem is related to korge.

I need to use SVG assets because the user can zoom in and out. When I load and scale the SVG it loses quality just like a Bitmap would. This kind of defeats the point of using an SVG.

Here is the code:
```
suspend fun main() = Korge(width = 1024, height = 1024, bgcolor = Colors["#2b2b2b"]) {
	val svg = SVG.read(resourcesVfs["untitled.svg"])
	image(svg) {
		scale = 5.0
	}
}
```

Here is the output:
![svg2](https://user-images.githubusercontent.com/7670593/98462243-7f1add00-21bb-11eb-93dd-3ddc595f811a.PNG)

**Comment by RezMike** [comment]
@MitchDart you should probably specify the final size of the image instead of scaling it.

**Comment by soywiz** [comment]
The image view just uses a bitmap/texture. So the SVG is renderer at its default size determined by the SVG viewport. I'm not sure (not tried) if the Graphics view supports already placing a SVG image there, and that supports scaling. If Graphics doesn't support it, maybe we can add a `VectorImage` view or something, so this would be a new feature.

**Comment by MitchDart** [comment]
I tried to render my images using graphics {}. I found that it suffers from the same issue. Even though the image is specified using vector paths, as soon as I scale it quality is lost. It seems that it is handled in the same way that SVGs are handled. In my opinion, these types of vector-based images should be able to scale, rotate, and translate pre-rasterization. I haven't looked into the implementation from korge. I will try and spend some time looking into how it works under the hood and maybe I can come up with a PR. 

If you wanted to make a VectorImage, would graphics then use the same implementation?

**Comment by RezMike** [comment]
@MitchDart you should use `sgraphics { }` or `graphics(autoScaling = true) { }`

**Comment by MitchDart** [comment]
@RezMike Thanks that works perfectly for graphics. It would still be a great feature if we could achieve the same with SVG's. I think most people who would use SVG's would do it for the dynamic scaling of vector images. 

Appreciate the help :)
