### ISSUE TITLE
Controller Stick input not mapped correctly

### ISSUE THREAD

**Issue by stewsters** [korlibs/korge#298]
The existing code in com.soywiz.korev.GamepadInfo transposes some of the GameButtons between the left, right, x and y.

   fun getX(stick: GameStick) = when (stick) {
        GameStick.LEFT -> get(GameButton.LX)
        GameStick.RIGHT -> get(GameButton.LY)
    }
    fun getY(stick: GameStick) = when (stick) {
        GameStick.LEFT -> get(GameButton.RX)
        GameStick.RIGHT -> get(GameButton.RY)
    }

I am not sure where the korev project is, otherwise I would do a pull request.  I think the code should look like this:

   fun getX(stick: GameStick) = when (stick) {
        GameStick.LEFT -> get(GameButton.LX)
        GameStick.RIGHT -> get(GameButton.RX)
    }
    fun getY(stick: GameStick) = when (stick) {
        GameStick.LEFT -> get(GameButton.LY)
        GameStick.RIGHT -> get(GameButton.RY)
    }

**Comment by soywiz** [comment]
Now, while preparing 2.0 you can make the PR here:
https://github.com/korlibs/korge-next/

**Comment by stewsters** [comment]
Awesome.  PR for this small change here:  https://github.com/korlibs/korge-next/pull/76

**Comment by soywiz** [comment]
Thanks for the PR, merged already! :)
