### ISSUE TITLE
Is it possible to run it on a canvas object on Android?

### ISSUE THREAD

**Issue by ferranpons** [korlibs/korge#31]
May it could sound a stupid question but I want to know if its possible to run Korge within the Android SDK classes like inside a "canvas" object instead of being Korge the main entrance to the game.

Something like I have a menu using the android sdk components like Activities and Fragments and I want to create an instance of Korge inside one of them or open a new screen after a button click.

Many thanks in advance!

**Comment by soywiz** [comment]
Hey Ferran :) I guess it is possible.

Here is the activity used for Korge:
https://github.com/korlibs/korui/blob/master/korgw/src/androidMain/kotlin/com/soywiz/korgw/KorgwActivity.kt

And here is the entrypoint generated for Android using korge plugin:
https://github.com/korlibs/korge/blob/master/plugins/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/targets/android/Android.kt#L205

You should be able to use that activity without the need of the korge plugin, by just including the right artifacts:

https://bintray.com/soywiz/soywiz/korge#files/com%2Fsoywiz%2Fkorge-android%2F1.2.0

Let me know if it works for you, to add that info to the documentation :)

**Comment by ferranpons** [comment]
Nice! I'll try that and I'll get back to you as soon as I test it.

Many thanks @soywiz !

**Comment by ferranpons** [comment]
@soywiz it works!

![party](https://media.giphy.com/media/l0IyjMoACyrgPwoMg/giphy.gif)

**Comment by soywiz** [comment]
:D 👯

**Comment by reymalahay** [comment]
@soywiz,

thank you for this information. 

the second link does not work. has it moved elsewhere?

please advise.

thanks in advance,
rey malahay

> Hey Ferran :) I guess it is possible.
> 
> Here is the activity used for Korge: https://github.com/korlibs/korui/blob/master/korgw/src/androidMain/kotlin/com/soywiz/korgw/KorgwActivity.kt
> 
> And here is the entrypoint generated for Android using korge plugin: https://github.com/korlibs/korge/blob/master/plugins/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/targets/android/Android.kt#L205
> 
> You should be able to use that activity without the need of the korge plugin, by just including the right artifacts:
> 
> https://bintray.com/soywiz/soywiz/korge#files/com%2Fsoywiz%2Fkorge-android%2F1.2.0
> 
> Let me know if it works for you, to add that info to the documentation :)

**Comment by soywiz** [comment]
@reymalahay 
They are different views (one from Android, the other from KorGE). You have an example embedding a KorGE project into an existing activity here:
https://github.com/korlibs/korge-samples/blob/231fa10e28e44a0e1415aaa1d031c11f382a55bd/integrations/android/app/src/main/java/org/korge/korgeviewexample/MainActivity.kt

**Comment by reymalahay** [comment]
thank you very much for this, @soywiz 

is there a plan to release `KDocs` for the classes? It be great if you could. It would help developers understand how the `KorGE` classes are related to each other, and how they should be used.

Please advise.

Thanks in advance,
rey malahay 

> @reymalahay They are different views (one from Android, the other from KorGE). You have an example embedding a KorGE project into an existing activity here: https://github.com/korlibs/korge-samples/blob/231fa10e28e44a0e1415aaa1d031c11f382a55bd/integrations/android/app/src/main/java/org/korge/korgeviewexample/MainActivity.kt

**Comment by soywiz** [comment]
They are slightly outdated, but you have some kdoc here:

* https://dokka.korge.org/korge/korge/
* https://dokka.korge.org/korio/korio/
* ...
* https://github.com/korlibs/dokka.korge.org

**Comment by Deorigami** [comment]
> @reymalahay They are different views (one from Android, the other from KorGE). You have an example embedding a KorGE project into an existing activity here: https://github.com/korlibs/korge-samples/blob/231fa10e28e44a0e1415aaa1d031c11f382a55bd/integrations/android/app/src/main/java/org/korge/korgeviewexample/MainActivity.kt

i dont Find Module() class or interface in the custom module file

**Comment by soywiz** [comment]
We are simplifying integrations here: https://github.com/korlibs/korge/pull/1962
Tehre you will create a korge view and will decorate it to configure a KorGE app, providing a suspending lambda with the entrypoint code, where you can create a scene container, or whatever
