### ISSUE TITLE
Bug with a logo

### ISSUE THREAD

**Issue by Suragul** [korlibs/korge#314]
Logo is flattened(
https://media.discordapp.net/attachments/728616340239417375/790279875554443264/Screenshot_2020-12-20-22-56-59.png?width=405&height=676
In this example I just add 
 icon = projectDir["src/commonMain/resources/korge.png"]
in build.gradle.kts
in new korge project

**Comment by soywiz** [comment]
As discussed, this is probably related to Android TV support added in 2.0.
As a workaround while we fix it, please open the project at: `build/platforms/android` and manually remove the Android TV icon and stuff
