### ISSUE TITLE
Review multitouch and gestures API on Android and iOS

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge#316]

**Comment by pablocaviglia-baires** [comment]
I've been trying to make this work a couple of months ago, but weren't successful on the try.

`package com.senaptec.toolframework.ui

import com.soywiz.kds.*
import com.soywiz.korge.component.*
import com.soywiz.korge.view.*
import com.soywiz.korio.async.*
import com.soywiz.korma.geom.*
import com.soywiz.korev.*
import kotlin.coroutines.*

val View.touch by Extra.PropertyThis<View, MultiTouchComponent> { this.getOrCreateComponentTouch { MultiTouchComponent(this) } }

suspend inline fun <T : View?> T?.onMultiTouchStart(noinline handler: suspend (MultiTouchComponent.Info) -> Unit) =
        this.apply { this?.touch?.onMultiTouchStart?.addSuspend(coroutineContext, handler) }

suspend inline fun <T : View?> T?.onMultiTouchEnd(noinline handler: suspend (MultiTouchComponent.Info) -> Unit) =
        this.apply { this?.touch?.onMultiTouchEnd?.addSuspend(coroutineContext, handler) }

suspend inline fun <T : View?> T?.onMultiTouchMove(noinline handler: suspend (MultiTouchComponent.Info) -> Unit) =
        this.apply { this?.touch?.onMultiTouchMove?.addSuspend(coroutineContext, handler) }

class MultiTouchComponent(override val view: View) : TouchComponent {
    data class Info(
            var touch: Touch = Touch.dummy,
            var gstart: Point = Point(),
            var gend: Point = Point(),
            var delta: Point = Point()
    ) {
        val id get() = touch.id
    }

    var Touch.touching by extraProperty("MultiTouchComponent.touching") { false }

    val info = Info()
    val onMultiTouchStart = Signal<Info>()
    val onMultiTouchMove = Signal<Info>()
    val onMultiTouchEnd = Signal<Info>()

    private fun updateStartEndPos(touch: Touch) {
        info.gstart.copyFrom(touch.current)
        info.gend.copyFrom(touch.current)
        info.delta.setToSub(info.gend, info.gstart)
    }

    private fun updateEndPos(touch: Touch) {
        info.gend.copyFrom(touch.current)
        info.delta.setToSub(info.gend, info.gstart)
    }

    override fun onTouchEvent(views: Views, e: TouchEvent) {
        println("------------------> $e")
        val touch = e.touches.first()
        info.touch = touch
        when (e.type) {
            TouchEvent.Type.START -> {
                if (view.hitTest(touch.current.x, touch.current.y) != null) {
                    touch.touching = true
                    updateStartEndPos(touch)
                    onMultiTouchStart(info)
                }
            }
            TouchEvent.Type.END -> {
                if (touch.touching) {
                    touch.touching = false
                    updateEndPos(touch)
                    onMultiTouchEnd(info)
                }
            }
            else -> {
                if (touch.touching) {
                    updateEndPos(touch)
                    onMultiTouchMove(info)
                }
            }
        }
    }
}
`

**Comment by soywiz** [comment]
Fixed here https://github.com/korlibs/korge-next/commit/2f85d93e09bfaee96f41b496d1dabc50ed295a7b
