### ISSUE TITLE
Circular camera view

### ISSUE THREAD

**Issue by codingpoets** [korlibs/korge#318]
I wanted to implement a circular camera view to achieve something like a spotlight where everything else is pitch black. The following image illustrates the scene with a rectangular camera view (white area).
![grafik](https://user-images.githubusercontent.com/10432668/103420109-16862600-4b96-11eb-8a0d-4ec94b17e4b8.png)

Is there a way to change the camera view to use a circle as the view area?
I am trying to find the lines of code where the actual shape of the camera view is defined. Can somebody give me a hint? Maybe there is a simple way to do it but I just didn't see it.

**Comment by soywiz** [comment]
The easiest way is to create an image covering all the screen with black except for a circle in the middle with transparent pixels.

Alternatively you could try to apply the `TransitionFilter` to the view holding the camera with a circle Transition. That acts like a mask:

https://github.com/korlibs/korge/blob/0efd90cb5cb03f708a4127b69f66985d30ed2df7/korge/src/commonMain/kotlin/com/soywiz/korge/view/filter/TransitionFilter.kt#L45

Another alternative is to use masks:

https://github.com/korlibs/korge-samples/blob/5d7f4e21701cc0998b14f521ad020cd2ae4dc480/sample/mask/src/commonMain/kotlin/main.kt#L16

**Comment by codingpoets** [comment]
Thank you for your suggestions! They helped a lot.
I tried the externally created image with transparent pixels as well as the `MaskedView`. Both solutions work well. If I find the time I will also have a look at the `TransitionFilter`.
I consider this issue closed.
