### ISSUE TITLE
Annoying particle emitter behavior

### ISSUE THREAD

**Issue by GiantNuker** [korlibs/korge#32]
The particle emitter seems to belch out some particles, then stop for a few seconds, then actually start. How can I make it go straight to actually starting?
Demo:
![gif](https://user-images.githubusercontent.com/43734540/55437825-bbed0f80-5554-11e9-9fc9-ace5ab82f7df.gif)
On a side node; Can you move a particleEmitterView after placing it? It's annoying having to make a new one every time I want to move it.

**Comment by soywiz** [comment]
Might be a bug. I'll check.

https://github.com/korlibs/korge/blob/master/korge/src/commonMain/kotlin/com/soywiz/korge/particle/ParticleEmitterView.kt

Do `view.simulator.emiterPos = Point(x, y)` work for you? I guess I should add something to change it maybe a emiterX and emiterY interpolable property that can be used with the tween. Suggestions are welcome.

Can you provide the .pex and texture file so I can reproduce it?

**Comment by Indi-Code** [comment]
[zip.zip](https://github.com/korlibs/korge/files/3039814/zip.zip)
