### ISSUE TITLE
 Illegal reflective access by com.soywiz.korgw.internal.MicroDynamic

### ISSUE THREAD

**Issue by JessJNielsen** [korlibs/korge#326]
Got this error:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.soywiz.korgw.internal.MicroDynamic (file:/Users/jessnielsen/.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.korgw/korgw-jvm/2.0.1/2e0bfbbd8134cdab5a96db7dd96bd7c7af2c4e21/korgw-jvm-2.0.1.jar) to method com.apple.eawt.FullScreenUtilities.setWindowCanFullScreen(java.awt.Window,boolean)
> WARNING: Please consider reporting this to the maintainers of com.soywiz.korgw.internal.MicroDynamic
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by soywiz** [comment]
It is a warning, you can ignore it for now.

More details here: https://github.com/korlibs/korge/issues/286

If you know a way to prevent this, feel free to make a PR at korge-next replacing this: https://github.com/korlibs/korge-next/blob/42b80d1a10e413ceb99e014e1ccff06b86625d78/korgw/src/jvmMain/kotlin/com/soywiz/korgw/awt/AwtGameWindow.kt#L72-L75
