### ISSUE TITLE
Multitouch bugs

### ISSUE THREAD

**Issue by Suragul** [korlibs/korge#331]
I think I find bugs) This is code:
suspend fun main() = Korge(width = 1280, height = 720, bgcolor = Colors["#2b2b2b"]) {
    val input = views.input
    val text = text("Touches ", color=Colors.YELLOWGREEN, textSize=64.0,)
    addUpdater {
        val ntouches: Int = input.activeTouches.size
        val touches: List<Touch> = input.activeTouches
        val rawTouch0: Touch = input.touches[0]
        text.text="Touches ${touches.size}"
    }
}
And there are bugs
1) Second touch is not detecting
https://discord.com/channels/728582275884908604/728616340239417375/802850246824427522
2) Korge shows one touch when there is no touch(((
https://discord.com/channels/728582275884908604/728616340239417375/802850594373107742

**Comment by Suragul** [comment]
My Android version is 5.1, Samsung Galaxy J1(2016) SM J-120F

**Comment by soywiz** [comment]
Relates to 
https://github.com/korlibs/korge/issues/316
