### ISSUE TITLE
[3D] Performance degradation for JVM

### ISSUE THREAD

**Issue by krzema12** [korlibs/korge#337]
Hi Carlos,

after updating to KorGE 2.0.6, I noticed my 3D app https://github.com/krzema12/stair-lift-simulator works significantly slower (like 2-5 FPS now) comparing to rather fluent experience on 2.0.0.2. On JS, it still works smoothly. I didn't check other platforms.

To reproduce, please see immediately before and after this commit: https://github.com/krzema12/stair-lift-simulator/commit/90a3fc51f517e69b92ea1c7d94600e5e42b4c59e . I changed just the version.

Best,
Piotr

**Comment by soywiz** [comment]
For me it works properly:

![2021-02-15 (1)](https://user-images.githubusercontent.com/570848/107934522-75560200-6f80-11eb-86ef-b9ca2019bcf4.png)

Can you press F7 and check the FPS bar? Additionally in the case you get a very low fps, can you profile the app with JVisualVM or other profiler?

**Comment by krzema12** [comment]
My setup: Ubuntu 20.04, display frequency 60.05 Hz, Java 11.0.7. FPS:

![image](https://user-images.githubusercontent.com/3110813/108605203-024ef000-73b3-11eb-8612-8a61769fd15d.png)

When I have some more time, I'll experiment with different Java version and check with the profiler.

**Comment by krzema12** [comment]
Spends >80% of the time in `sun.awt.X11GraphicsDevice.getDisplayMode()`:

![Screenshot from 2021-02-21 20-30-19](https://user-images.githubusercontent.com/3110813/108636150-c5066300-7483-11eb-91a5-52c00700c347.png)

**Comment by soywiz** [comment]
Thanks! This helps a lot. Looking at that profiling, it seems that getting the display mode is really expensive on Linux or at least under your system. Going to try to reproduce it. I guess we can try to get the display mode just once, but I might not work when plugging/unplugging a new monitor unless we can detect that? I'll investigate a bit. Thanks for reporting!

**Comment by soywiz** [comment]
Hey @krzema12 , I was able to reproduce it on a Virtual Machine, with not that problematic results, but still was able to perceive some time wasted there. I believe I have fixed it already, but can you check if that's the case? The way to try that is the following:

Clone 
```
git clone https://github.com/korlibs/korge-next.git
cd korge-next
./gradlew publishJvmLocal # this should publish common, metadata and jvm targets to maven local, in a reasonable amount of time
```

That should publish version `2.0.0.999` of the gradle plugin. Can you try that local version on your machine?

**Comment by soywiz** [comment]
![4z0vaq](https://user-images.githubusercontent.com/570848/108749255-df9e1200-753f-11eb-8800-9aa4f976bc45.jpg)

**Comment by krzema12** [comment]
Thanks for such quick action @soywiz!

I'm trying to run korge-next locally, but using `2.0.0.999` is not enough. I'm getting:

```
* Where:
Build file '/home/piotr/repos/stair-lift-simulator/build.gradle.kts' line: 25

* What went wrong:
'void kotlin.jvm.internal.PropertyReference0Impl.<init>(java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
```

Looking at the contents of `~/.m2`, I figured that the plugin's coordinates changed to `com.soywiz.korge:com.soywiz.korge.gradle.plugin`. By following this hint, I'm getting:

```
* Where:
Build file '/home/piotr/repos/stair-lift-simulator/build.gradle.kts' line: 25

* What went wrong:
Could not initialize class com.soywiz.korge.gradle.BuildVersions
```

Any idea what's wrong? Two months ago I used korge-next locally without issues.

**Comment by soywiz** [comment]
Have you tried a gradle clean on both projects? Can you try a full publishToMavenLocal too?

**Comment by krzema12** [comment]
Just tried the full korge-next publishing and cleaning both projects before building them - the same result :(

**Comment by soywiz** [comment]
Can you run gradle with —stacktrace?

maybe we can get more information on this error:

```
Could not initialize class com.soywiz.korge.gradle.BuildVersions
```

**Comment by krzema12** [comment]
I deleted the whole `~/.m2` when trying before. Now I additionally used `--stacktrace`:

```
* Exception is:
java.lang.NoClassDefFoundError: Could not initialize class com.soywiz.korge.gradle.BuildVersions
        at com.soywiz.korge.gradle.KorgeGradleApply$apply$1.invoke(KorgeGradlePlugin.kt:32)
        at com.soywiz.korge.gradle.KorgeGradleApply$apply$1.invoke(KorgeGradlePlugin.kt:20)
        at com.soywiz.korge.gradle.util.GradleToolsKt.invoke(GradleTools.kt:8)
        at com.soywiz.korge.gradle.KorgeGradleApply.apply(KorgeGradlePlugin.kt:21)
        at com.soywiz.korge.gradle.KorgeGradlePlugin.apply(KorgeGradlePlugin.kt:130)
        at com.soywiz.korge.gradle.KorgeGradlePlugin.apply(KorgeGradlePlugin.kt:126)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
...
```

Could you try to reproduce it on your machine? For your convenience, I pushed exactly the code I'm trying to build to a branch: https://github.com/krzema12/stair-lift-simulator/tree/korge-issue-337

**Comment by soywiz** [comment]
Reproduced with your project. It seems that the difference is that you are using an older version of gradle that included an older version of Kotlin, and they changed how properties work. The plugin is compiled against Kotlin 1.4.30. If you change your gradle version to 6.8.1 ( https://github.com/krzema12/stair-lift-simulator/blob/2e36ad96a216e88d1407bdfcdfab4b876d562f10/gradle/wrapper/gradle-wrapper.properties#L3 ), it works.

I'm going to either force to use a newer version of Gradle, or to not use property references.

**Comment by krzema12** [comment]
Thanks a lot, confirmed that it works and that the performance is as it should be, around 60 FPS :)

**Comment by krzema12** [comment]
![img](https://i.imgflip.com/4z6n9k.jpg)
