### ISSUE TITLE
Debug View (F7) freezes windows on macOS Bug Sur 

### ISSUE THREAD

**Issue by emign** [korlibs/korge#338]
Pressing F7 on JVM target (aarch64 and x86) freezes the window without opening the overlay or the debug window. 
Can only force close it.

Big Sur 11.2.1

Its a Apple Silicon Mac.

**Comment by soywiz** [comment]
Fixed here https://github.com/korlibs/korge-next/commit/36005565e42f6fa3374684b9a75bea3f43f1ddfc
