### ISSUE TITLE
docs: incorrect syntax highlighting

### ISSUE THREAD

**Issue by MairwunNx** [korlibs/korge#34]
![image](https://user-images.githubusercontent.com/39625750/56822716-8fc66500-685a-11e9-81ed-bc5693dcfb1e.png)
As you can see, on the screenshot, incorrect syntax highlighting, red and bright red on a dark background looks very bad, other colors are good, it would not be bad if the color was replaced with a calmer :), if you need help choosing colors, I will try to help 😉

**Comment by soywiz** [comment]
Moved here: https://github.com/korlibs/korlibs.soywiz.com/issues/7
