### ISSUE TITLE
Music not playing when initialized and played in different functions/coroutines.

### ISSUE THREAD

**Issue by 0megaD** [korlibs/korge#342]
# Introduction
When loading music with `readMusic()` in a scene in one of the overridden Container functions and playing it in another, no music actually plays.

When loading music with `readMusic()` in one coroutine, and playing in another, no music actually plays.

See attached zip for sample project.

### Does not work (Music *does not play* ):
```kotlin
        launchImmediately {
            bgm = resourcesVfs["music.wav"].readMusic()
        }
        launchImmediately {
            bgm.play(PlaybackParameters(volume = 0.05, times = PlaybackTimes.INFINITE))
        }
```

```kotlin
    override suspend fun Container.sceneInit() {
        bgm = resourcesVfs["music.wav"].readMusic()
    }

    override suspend fun sceneAfterInit() {
        bgm.play(PlaybackParameters(volume = 0.05, times = PlaybackTimes.INFINITE))
    }
```

### Works (Music plays):

```kotlin
    override suspend fun sceneAfterInit() {
        super.sceneAfterInit()
        bgm = resourcesVfs["music.wav"].readMusic()
        bgm.play(PlaybackParameters(volume = 0.05, times = PlaybackTimes.INFINITE))
    }
```

# Resources

## Broken sample project 
[korge-musicbug.zip](https://github.com/korlibs/korge/files/6064276/korge-musicbug.zip)

**Comment by dector** [comment]
Will this be backported to KorAU?

**Comment by soywiz** [comment]
Of course. next is only a temporal repo, when deploying I copy all the changes to each repo/artifact. In fact im already publishing a new version

**Comment by dector** [comment]
Awesome! Thank you very much!
