### ISSUE TITLE
onAttach, onDetach

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korge#346]
Hi, is there some way to listen on attach/detach events on View? 
I need those to properly free UI resources on component detached

**Comment by soywiz** [comment]
There are some tricks to detect those.
But what kind of freeing do you need? Everything exposed on Korge is managed and will be GCed once unreferenced. That include events attached to views

**Comment by BioRyajenka** [comment]
I am generating 2d game map on-fly, and since `Image` with map chunk is long to create, I want to do it in separate thread. 
For data synchronization I am using `IsolateState` (https://github.com/touchlab/Stately) and it has to be disposed to prevent memory leaks. So this kind of resource I want to free :)

**Comment by soywiz** [comment]
I see. I think there is a mechanism for that available. I don't remember right now, but I will check tomorrow and will comment 👍

**Comment by soywiz** [comment]
Here we go:

https://github.com/korlibs/korge/blob/dcddb3eb4d9e34a263a235089237deb89f339cd3/korge/src/commonMain/kotlin/com/soywiz/korge/component/StageComponent.kt#L7-L21

Maybe we can provide an easier way to include that component like adding onAttach, onDetach. And add documentation for those

**Comment by BioRyajenka** [comment]
Ok, thanks!
Should I close the issue now?

**Comment by soywiz** [comment]
Since it should be fast, I'm going to add the onAttach, onDetach now. Let me close it with a commit

**Comment by soywiz** [comment]
Thank you for your feedback

Fixed here: https://github.com/korlibs/korge-next/commit/4fb1a080201469a5965207384c5126940ae69745

Feel free to copy that method into your project so you can use it before a new version is deployed.
