### ISSUE TITLE
Onclick doesn't trigger in firefox.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korge#348]
I have a similar game to 2048. I used korge to compile it to js and run it in browser. 

It runs completely fine in chrome and edge, but not in firefox - where the game is running, but tapping a button / rectangle doesn't trigger onclick event.

**Comment by soywiz** [comment]
Any extra information? Which version of KorGE and Operating System? Are you using a mouse, or a mac trackpad for example?

**Comment by Josef-Vonasek** [comment]
Solved.

**Comment by soywiz** [comment]
In the case someone else faces a similar issue, which was the problem?
