### ISSUE TITLE
korge-box2d package on bintray is not updated.

### ISSUE THREAD

**Issue by toliner** [korlibs/korge#35]
Platform-specified implementations(e.g. korge-box2d-jvm, korge-box2d-js) are all updated now, but korge-box2d package is not updated.
Because of this, I can't add korge-box2d as dependency to my project.

**Comment by toliner** [comment]
There is only `mave-metadata.xml` file on korge-box2d:1.2.1
https://bintray.com/soywiz/soywiz/korge/1.2.1#files/com%2Fsoywiz%2Fkorge-box2d

**Comment by soywiz** [comment]
Updated here and synchronized to jcenter: https://bintray.com/korlibs/korlibs/kbox2d
