### ISSUE TITLE
can't create new project with plugin

### ISSUE THREAD

**Issue by 2x2xplz** [korlibs/korge#350]
Was excited to try out KorGE, but my brand new project using KorGE plugin fails to compile.

Blue bar appears over code window: Code insight unavailable (script configuration wasn't received)
![image](https://user-images.githubusercontent.com/16587079/111893980-26a6e800-89c4-11eb-8b39-693224932c5c.png)

In the Build sub-window, korge: failed
![image](https://user-images.githubusercontent.com/16587079/111893987-2f97b980-89c4-11eb-96eb-394c3e504d61.png)

the Hello World project compiles and runs via `gradlew.bat runJvm` but inside IntelliJ it has the same issues as above, and there is no auto-complete or hinting.

Alternatively, I created a regular plain Gradle project using Kotlin multiplatform. 
I added the line import com.soywiz.korge.gradle.* but "soywiz" cannot be resolved.
![image](https://user-images.githubusercontent.com/16587079/111894003-59e97700-89c4-11eb-8f17-16151b650171.png)

Using IntelliJ on Win10. Here is my environment:
```
IntelliJ IDEA 2020.3.1 (Community Edition)
Build #IC-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1990M
Cores: 4
Non-Bundled Plugins: com.4lex4.intellij.solarized, com.berzanmikaili.intellij.monokai_pro, com.jetbrains.CyanTheme, com.tylerthrailkill.intellij.pastellicious, com.vincentp.gruvbox-theme, monokai-pro, Dart, rasarts.espresso.light.theme, io.flutter, Docker, GrepConsole, org.jetbrains.kotlin, kotest-plugin-intellij, com.soywiz.korge.korge-intellij-plugin
```

Also followed the instructions here:
https://korlibs.soywiz.com/korge/gettingstarted/setup/gradle-plugin/
also no luck
![image](https://user-images.githubusercontent.com/16587079/111894674-f2cec100-89c9-11eb-9d37-b11170111138.png)

I've built many Kotlin projects, server-side and console. IntelliJ works fine on those project, no errors similar to above.

**Comment by soywiz** [comment]
Looks like a pretty old  version of KorGE (1.0.2). Latest version is 2.0.9.1: https://github.com/korlibs/korge-hello-world/blob/cbfd6bff7cf8026f462574d0c016bbb0762a2a8c/gradle.properties#L1

How did you get the project?

Have you either:
* Forked the hello world? https://github.com/korlibs/korge-hello-world
* Used the intellij plugin to generate the project? https://plugins.jetbrains.com/plugin/9676-korge

How did you get the project you are opening?

**Comment by 2x2xplz** [comment]
Hi. I did not fork any project. My plugin is version 2.0.6.1, I installed it directly within IntelliJ (Plugin Marketplace)
![image](https://user-images.githubusercontent.com/16587079/111920468-69140780-8a4c-11eb-984c-3dfa56ab786c.png)

and created new project based on the plugin:
![image](https://user-images.githubusercontent.com/16587079/111920511-a5dffe80-8a4c-11eb-80cc-48554cbef481.png)

**Comment by soywiz** [comment]
Can you show the `gradle.properties` generated? Which operating system are you using?

**Comment by 2x2xplz** [comment]
gradle.properties:
```
korgePluginVersion=2.0.7.1
org.gradle.jvmargs=-Xmx2g
kotlin.mpp.stability.nowarn=true
```

I am on Windows 10 Pro:
```
IntelliJ IDEA 2020.3.1 (Community Edition)
Build #IC-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1990M
Cores: 4
Non-Bundled Plugins: com.4lex4.intellij.solarized, com.berzanmikaili.intellij.monokai_pro, com.jetbrains.CyanTheme, com.tylerthrailkill.intellij.pastellicious, com.vincentp.gruvbox-theme, monokai-pro, Dart, rasarts.espresso.light.theme, io.flutter, Docker, GrepConsole, org.jetbrains.kotlin, kotest-plugin-intellij, com.soywiz.korge.korge-intellij-plugin
```

settings.gradle:
```
enableFeaturePreview("GRADLE_METADATA")
```

build.gradle.kts:
```
import com.soywiz.korge.gradle.*

buildscript {
	val korgePluginVersion: String by project

	repositories {
		mavenLocal()
		maven { url = uri("https://dl.bintray.com/korlibs/korlibs") }
		maven { url = uri("https://plugins.gradle.org/m2/") }
		mavenCentral()
		google()
	}
	dependencies {
		classpath("com.soywiz.korlibs.korge.plugins:korge-gradle-plugin:$korgePluginVersion")
	}
}

apply<KorgeGradlePlugin>()

korge {
	id = "com.example.example"
// To enable all targets at once

	//targetAll()

// To enable targets based on properties/environment variables
	//targetDefault()

// To selectively enable targets

	targetJvm()
	targetJs()
	targetDesktop()
	targetIos()
	targetAndroidIndirect() // targetAndroidDirect()
}
```

**Comment by retroredge** [comment]
Similar experience for me on OSX. I used the plugin (korgePluginVersion=2.0.7.1) to create a project but when I open main.kt is says "Kotlin not configured" and opening build.gradle.kts shows that it has 17 errors.

Intellij Ultimate 2021.1

**Comment by soywiz** [comment]
I guess this was fixed sometime ago
