### ISSUE TITLE
Tutorial is outdated

### ISSUE THREAD

**Issue by Someone1123698** [korlibs/korge#351]
I'm new and trying to follow the 2048 tutorial but a lot of the stuff shown there are actually outdated which makes learning how to use it harder than it already is

**Comment by soywiz** [comment]
This tutorial can be edited via github here:

https://github.com/korlibs/blog.korge.org/blob/3dd8a29268724840ca548cd5e05327f36466fcf9/_posts/2020-06-02-korge-tutorial-writing-2048-game-step-0.md

**Comment by jgedri** [comment]
But if they knew enough to edit the tutorial, would they be following it?
