### ISSUE TITLE
Adding supportBox2d fails with -> Could not find box2d:2.0.0-alpha

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#367]
I created a new project with the KorGE Intellij Plugin `2.0.6.1` and the "New Project Wizard". I checked the Box-2D Support:  
  
<img width="497" alt="2021-05-18_22h52_43" src="https://user-images.githubusercontent.com/1190109/118721924-c26d9c80-b82b-11eb-88c3-bb60260879fd.png">

The resulting project contains:
```kotlin
korgePluginVersion=2.1.1.1
supportBox2d()
```

But the gradle sync fails because of
```
Could not find com.soywiz.korlibs.kbox2d:kbox2d:2.0.0-alpha.
```

**Comment by soywiz** [comment]
Those should be updated: https://github.com/korlibs/korge-next/blob/c1df2a579643c1a763a58db6bf5ab937df6863a3/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/KorgeExtension.kt#L407-L424

Not sure if those should be deprecated, or somehow providing a way to update them without making a release

**Comment by ObsidianX** [comment]
The commit `supportBox2d()` points to (https://github.com/korlibs/korge-bundles/commit/4ac7fcee689e1b541849cedd1e017016128624b9) is from October and still references `2.0.0-alpha`.  A workaround is to call `bundle` directly.  I also found that you still need to add the dependency to kbox2d manually for some reason.

```kotlin
dependencyMulti("com.soywiz.korlibs.kbox2d:kbox2d:2.1.1")
bundle("https://github.com/korlibs/korge-bundles.git::korge-box2d::7439e5c7de7442f2cd33a1944846d44aea31af0a")
```

The commit hash is simply the latest one which refers to `kbox2d:2.1.1`:  https://github.com/korlibs/korge-bundles/commit/7439e5c7de7442f2cd33a1944846d44aea31af0a
