### ISSUE TITLE
IDE Error Cannot access 'kotlin.reflect.KAnnotatedElement' 

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#369]
After creating a new hallo world with the Korge "New project wizard" the method references in tweens are marked as error:

<img width="625" alt="2021-05-18_23h43_10" src="https://user-images.githubusercontent.com/1190109/118727275-d072eb80-b832-11eb-8b8d-a330215ddcc2.png">

#### ⚡Problem
```kotlin
Cannot access 'kotlin.reflect.KAnnotatedElement' which is a supertype of 'kotlin.reflect.KMutableProperty0'. 
Check your module classpath for missing or conflicting dependencies
```

korgePluginVersion: `2.1.1.1`
KorGE IDE Plugin Version: `2.0.6.1`
IDE: IntelliJ Ultimate `2021.1.1`

It's marked as error and listed under problems. But the gradle task `runJVM` is able to build and start the example.

**Comment by soywiz** [comment]
https://github.com/korlibs/korge-hello-world/issues/15

Reported here: https://youtrack.jetbrains.com/issue/KT-46434

I think they are investigating the issue already. But unfortunately nothing we can handle at KorGE level since it looks like a regression

**Comment by soywiz** [comment]
I believe this was fixed already 👍
