### ISSUE TITLE
Good vibrations -where to add?

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#37]
As I can see, there is no built in support for device vibration. For Android and web it would be very easy to add:
### JS
``` javascript
window.navigator.vibrate(200);
```
### Android
``` java
Vibrator v = (Vibrator) getSystemService(Context.VIBRATOR_SERVICE);
v.vibrate(400);
```
If its not planned in the near future, I would add it by my own.

But where is the best place? For me it seems something controller specific, because on a Computer you need a game-pad. Also in LibGDX we have a `Gdx.input.vibrate(2000);`.
Sou I would add some `Vibrator` in the `korge.input` package. Or better `GamepadComponent.vibrate()`?

Then the Android specific Implementation goes to the `KorgwActivity` in the **koreui**, right?

An we have to add a `android.permission.VIBRATE` to the build script:
**korge**: `gradle/targets/android/Android.kt`
Or should this only be added with a compiler flag? So wee can add it only if needed?

The reason for me is the Android target. A small and short vibration is a good button-pressed feedback.

**Comment by soywiz** [comment]
1.4.2 include vibrations already. Check this commit:
https://github.com/korlibs/korge/commit/87901e4b624a948bf16ddc43800ecb03cad121cc
