### ISSUE TITLE
🔊💢 Sound crashes and keeps playing after closing the game window

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#370]
I play a background music file during my game. All works fine, until I stop the game by closing the window. Then the music gets choppy and never stops. Check out the video for details.
```kotlin
resourcesVfs["musicFile.mp3"].readMusic().playAndWait()
```

https://user-images.githubusercontent.com/1190109/118870214-93683100-b8e6-11eb-85e4-1bccf641318d.mp4

KorGE-2.1.1.1
Kotlin-1.5
Platform: Win JVM

**Comment by soywiz** [comment]
Can't reproduce anymore with latest korge git
