### ISSUE TITLE
Icon doesn't change.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korge#381]
Adding a path to custom icon in `build.gradle.kts` doesn't change the icon of executable `App.exe`
```kotlin
korge {
    icon = file("./icon.png")
}
```

**Comment by soywiz** [comment]
I can asume you are referring to a window executable, right?

**Comment by Josef-Vonasek** [comment]
Yes, I do.

**Comment by Josef-Vonasek** [comment]
Ok, fixed this by using:

```kotlin
import com.soywiz.korge.gradle.util.*

korge {
    icon = project.projectDir["icon.png"]
}
```

**Comment by soywiz** [comment]
In theory the file() function is referring the the gradle project root. I assumed the icon was along the build.gradle file.
Can you do a small test so we can document and/or fix it?

can you place and execute this in your build.gradle and put the results here?

```
println(file("./icon.png"))
println(project.projectDir["icon.png"])
```

**Comment by Josef-Vonasek** [comment]
Both print the same thing with latest korge `2.2.1.0`.

**Comment by soywiz** [comment]
Then I don't understand why it didn't work for you 🤔
