### ISSUE TITLE
Multiple opengl textures

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korge#383]
Hi,
Is there a way to use multiple (say, two) different bitmaps without affecting performance? 

I am asking because quick googling gave me that you can use multiple _opengl textures_ in same shader (but I am not a specialist, so I might be wrong here).

Same question from the different angle: I want to improve my game performance by adding atlases. But I am sure I will need multiple atlases. But I have many different sprites in game, so most probably atlases will change frequently on GPU, giving no performance gain.

Here are quick tests:
```kotlin
val imSize = 20
val bitmaps = listOf("a.png", "b.png").map {
	bitmap(it).resized(imSize, imSize, ScaleMode.NO_SCALE, Anchor.TOP_LEFT)
}
var cnt = 0
for (i in 0 until HEIGHT / imSize) {
	for (j in 0 until WIDTH / imSize) {
		val bmp = bitmaps[(cnt++) % bitmaps.size] // this lines gives me around 30 fps
		val bmp = bitmaps[i % bitmaps.size] // this gives 120
		image(bmp).xy(j * imSize, i * imSize)
	}
}
```

**Comment by soywiz** [comment]
How many different atlases do you think you would need?

In some OpenGL versions we could use an array of textures/samplers, but they are not available at least on WebGL1, so in that case we would need to make a set of ifs to select the texture.

I did a different approach to optimize UI that was buffering drawing per attribute which would also help opaque 3D materials, but that doesn't preserves drawing order, which won't probably work in your case for 2d.

Going to try the IF/ELSE approach with maybe 2 or 3 different images.

**Comment by BioRyajenka** [comment]
Thanks for quick response!

For my specific case 2 atlases will be enough.

**Comment by soywiz** [comment]
I have configured it to support up to 4 different textures in a single batch

**Comment by BioRyajenka** [comment]
Cool! Thanks a lot!
How to use it? Will multiple bitmaps be used automatically?

**Comment by soywiz** [comment]
Yeah, for 2d it is automatic. There is a batcher that group geometry together preparing to send it to the gpu. Before, it was only able to pack one single texture in a single batch, now it can up to 4. As long as it uses the same shader, the same blending mode, and the premultiplied and smoothing properties are the same.

If you press `F7` ingame, there is a debug overlay displaying information. The huges bottleneck is the number of batches that appear on the top part. This feature reduces that number.

You can try already with your sample if you download the repo: `korlibs/korge-next`.
Then `gradlew publishToMavenLocal`.
Then use `2.0.0.999` as your korge plugin version.
