### ISSUE TITLE
Add `onFrame` function with suspend callback.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korge#384]
Currently, there are 3 ways to periodically update a `View`: `while loop`, `fixedUpdater` & `hrUpdater`.

However, none of them can launch a nonblocking suspend call.
Having a `View.onFrame(fn: suspend () -> Unit)` would be useful for e.g. an interactive file watch.

**Comment by soywiz** [comment]
onFrame is intended to be executed synchronously once per frame. Doing that other way might lead to accumulating stuff on each frame. Can you put an example of what you want to achieve? Maybe we can suggest you an alternative

**Comment by Josef-Vonasek** [comment]
I wanted to automatically unzip every file in a folder and show the progress in UI. 
I watched the folder for changes andstarted unzipping every file that appeared there during the run of the program.

Now I require explicit click on button from the user.
