### ISSUE TITLE
Mouse events performance issues

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korge#385]
Hi!
With many views on scene (but not on the screen) korge gives pretty bad performance.

Profiling tells me that mouse events play pretty notional role in this:
![image](https://user-images.githubusercontent.com/9904421/125963483-76e5272c-748e-4aee-bdeb-0ab2c13e884a.png)
![image](https://user-images.githubusercontent.com/9904421/125963544-177a45b1-ca5f-4cb9-8289-95bc062a65ea.png)

As you see, these three functions (`val globalSpeed: Double get(); getAllDescendantViews() and MouseEventsUpdate.update()`) takes about 25-30% of the CPU time. What is remarkable, **disabling mouse events do no difference**: `stage.mouseEnabled = false`

**Comment by BioRyajenka** [comment]
I checked the engine code here and I don't know how to improve `getAllDescendantViews()` (and I don't know what is `globalSpeed`).

But shouldn't `mouseEnabled = false` disable `MouseEventsUpdate.update()`? And maybe some switch can be introduced to disable `getAllDescendantViews` check?

**Comment by soywiz** [comment]
Can you either dump your view tree and paste it here, or indicate how is your tree structure?

How many views do you have? How many levels of hierarchy do you have etc.

**Comment by BioRyajenka** [comment]
[tree dump.txt](https://github.com/korlibs/korge/files/6832175/tree.dump.txt)
Here is json representation of the tree. If you have any ideas how to visualize, I can do it :)

The tree has about 5k elements in it (but only about 100-200 are visible)

**Comment by soywiz** [comment]
There is a `View.dump()` method you can use for this. It displays one line per view and uses indentation to represent hierarchy.

```kotlin
stage.dump()
```

KorGE doesn't have any integrated occlusion mechanism for this.
There are some specific views like UIVerticalList that handles what is visible or not, but that's a specific View, and it is not a system integrated. So for mouse events all the views are iterated.

What you can do is to have a separate structure to keep all the views,
and add to the container the ones that are visible with some custom code.

**Comment by BioRyajenka** [comment]
👍 thanks, I will do it this way

(but anyway, what `mouseEnabled` do?)

**Comment by soywiz** [comment]
There are two properties `mouseEnabled` and `mouseChildren`. You should probably try to set to false `mouseChildren`:

https://github.com/korlibs/korge/blob/3bfe8b8708c8bd40ebfb81751e005f738bf20ee7/korge/src/commonMain/kotlin/com/soywiz/korge/view/View.kt#L968-L988
