### ISSUE TITLE
Features link to 404s when reating a new Korge project in Intellij 

### ISSUE THREAD

**Issue by jlengrand** [korlibs/korge#387]
I just installed the korge plugin for the first time, when creating a project, I am offered to add support for features : 

![image](https://user-images.githubusercontent.com/921666/127003673-9c52be54-0598-4d52-b1e6-e71c39b42a69.png)

3D support, Dragon Bones, Box-2D Support, SWF all link to Github pages that are 404. 
Respectively 

* https://korlibs.soywiz.com/korge/animation/swf/
* https://korlibs.soywiz.com/korge/physics/box2d/
* https://korlibs.soywiz.com/korge/skeleton/dragonbones/
* https://korlibs.soywiz.com/korge/3d/

**Comment by jlengrand** [comment]
I'm guessing the actual links should be

* https://korlibs.soywiz.com/korge/reference/skeleton/
* https://korlibs.soywiz.com/korge/reference/3d/
* https://korlibs.soywiz.com/korge/reference/swf/#swf
* https://korlibs.soywiz.com/korge/reference/physics/#box2d

**Comment by jlengrand** [comment]
Looks to me like the code for this is located here : https://github.com/korlibs/korge-intellij-plugin/blob/e8c222b1d9c08d1d43d1cf81550a1bc3e31e111a/src/main/resources/com/soywiz/korge/intellij/korge-templates.xml#L6

I can have a tab at fixing it if that helps (and someone confirms the links are correct)

**Comment by soywiz** [comment]
Nice! Indeed it is that file. Could you make a PR fixing it, please?

**Comment by jlengrand** [comment]
See https://github.com/korlibs/korge-intellij-plugin/pull/33

**Comment by soywiz** [comment]
This was fixed sometime ago
