### ISSUE TITLE
delay function freezes coroutine on native build for korge-gradle-plugin:1.2.1

### ISSUE THREAD

**Issue by tranquilitor** [korlibs/korge#39]
When running a coroutine inside Scene class, if Kotlin native build is made with 1.2.1 korge version, all coroutines freeze as soon as delay is called (com.soywiz.korge.time.delay).
Works fine with Kotlin JVM build and Kotlin native build korge 1.2.0

**Comment by soywiz** [comment]
Should be fixed on the latest version
