### ISSUE TITLE
Feature Request: Raycast standard library

### ISSUE THREAD

**Issue by Snifexx** [korlibs/korge#390]
As I developed my golf 2D game (more of a minigame) I reached a point where continuing without rays was impossible. As everyone would do, I tried to implement my one.  The problem comes down to collision detection: in a 2D sprite-based game the closes thing to a collision system is either box2d or views. In both cases, often game could deploy particular shapes, look at RoundRect for example. These particular shapes make the task of implementing raycasting extremely tedious since the only plausible way to do it is raymarching. The latter is also very problematic to implement as we would need to write an SDF (Signed Distance Function) for every type of shape, and often an SDF doesn't even exist with some types of shapes.

What I ask is a simplification for the engine's user, through a standard class (e. g. RayCast) in a similar way as the Unity Engine

The implementation is still a problem, though another way to do it would be using a two-line collision algorithm. But we don't know the outline of each view (e. g. How could we get all the lines composing the outline of a RoundRect?). Implementing a way to retrieve these would be decisive.

If any of you know a better way to implement this, please share it in this post as it would be really useful

ALSO, VERY IMPORTANT SPECIFICATION: this is regarding a 2d NON-TILED system. In a grid the algorithm would already exist, for any of you interested in this check out this video: https://www.youtube.com/watch?v=NbSee-XM7WA&t=1432s (it's written in c++ but the theory is easily convertible in every language)

**Comment by soywiz** [comment]
Awesome. Thanks for the insights.

Right now there is no embedded raycasting functionality embedded in the engine. The closest stuff related to physics is box2d implementation.
There are tons of games that don't require raycasting to work properly, but agree that would be something nice to have.
I'm already adding collision detection stuff, based on shape collisions between objects and in tiles, but it is not designed to scale well right now outside that, since we don't have any structure to query 2d objects in a fast way to check only closest ones.
Without using box2d, and depending on your case, you can try to simulate a raycast by doing hit tests in small increments hit tests.
If nobody else implements it first, I will take this into account and will try to implement both a structure to place objects in bi and tridimensional spaces, and will implement some raycasting stuff. But since the backlog is pretty huge already, can't compromise to specific dates on this.

**Comment by Snifexx** [comment]
Another thing I just thought of is a mixed kind of algorithm. This would work like so:

Take a point and a direction, the raycast origin, and any kind of prop, so a roundrect view, a circle, anything.

then, we would get the bounds of the global rectangle of that object. Knowing that, use the SDF for rectangles in ALL cases.

After that make a quick check: if the ray hits the view we're done, otherwise, we simply continue with small increments.

The good thing about this idea is that implementation is straightforward, we removed the problem of to many handling cases by working with rectangle initially and then proceeding with small hitTest increments.

It could be better but this is still a HUGE improvement from just small increments:

Of course, the precision problem still is unresolved, whenever you will implement raycasting I suggest letting the developer chose the small increment value.

Other than that I wanted to suggest better documentation on box2d. This might be only my problem but I found it really difficult learning to use korge box2d with just examples. I don't really ask anything very specific, just a bit more documentation on the matter. It could be a youtube video on korge's channel, a simple dedicated page on Reference, or even add more on the current Physics tab

Thanks for considering the implementation of raycasting, it could really be helpful not to implement it every time!

**Comment by soywiz** [comment]
I have added a BVH structure to the latest version of KorGE so you can perform raycasts and range selection queries for 2D and 3D:

![raycast](https://user-images.githubusercontent.com/570848/129452220-e9eecd8f-9936-4c47-929f-6a7676f3afdc.png)

Right now it only works for filtering views on a ray or in a rectangle, fine-grained raycasting is still needed. Also not implemented for tiles yet.

**Comment by soywiz** [comment]
For the case of tile maps you have this: https://store.korge.org/module/korma-tile-raycasting/ along BVH, I guess this should be enough for most games. Also there are new tools in Shape2d for more complex scenarios: https://github.com/korlibs/korge/blob/7025b01d7733601ebef7b904509b70b2b4cc80f7/korge-sandbox/src/commonMain/kotlin/samples/MainShape2d.kt#L42
You can convert a Ray into a Line shape and check for intersection points.
