### ISSUE TITLE
Camera and TiledMap not render properly when it moveBy

### ISSUE THREAD

**Issue by zetazaw** [korlibs/korge#391]
I tried to use tiledmap and and camera as this sample [https://github.com/emign/korge-samples/blob/master/sample-tilemap/src/commonMain/kotlin/main.kt](url)

It is okay when the windows size is larger than double as the sample. But when I change fixedSizeContainer size to same as window size, camera does not render properly to go down. Move to top, right and left is okay. 
(only object layer render as attached picture)

And also please let me know if there is a TiledMap and Turtorial.

![korge](https://user-images.githubusercontent.com/7368006/129400842-8c3a5910-2187-4389-8eea-ff6329c26ade.png)

**Comment by soywiz** [comment]
That uses an old version of korge, that might have a bug in the tilemap renderer.

Please try this sample that uses the latest version:
* https://github.com/korlibs/korge-starter-kit-rpg
* https://korlibs.github.io/korge-starter-kit-rpg/
