### ISSUE TITLE
GradientPaint applies wrong colors on Android

### ISSUE THREAD

**Issue by funriser** [korlibs/korge#427]
sample app code:
```kotlin
suspend fun main() =
    Korge(width = 512, height = 512, bgcolor = Colors["#2b2b2b"]) {
        graphics {
            fill(
                LinearGradientPaint(
                    x0 = 0, 0,
                    x1 = 512, 512,
                ) {
                    addColorStop(0.3, Colors.RED)
                    addColorStop(1, Colors.GREEN)
                }
            ) {
                rect(0, 0, 512, 512)
            }
        }
    }
```

**Expected colors** (Screenshot from JVM app):

![Screenshot 2022-05-01 at 17 55 43](https://user-images.githubusercontent.com/17656589/166156124-1cff31b1-8d0e-45bb-a321-53b3f6bb45f7.png)

**Actual colors:**

![photo1651424023](https://user-images.githubusercontent.com/17656589/166156092-bcbeb15a-d120-47a3-8372-e09307a40027.jpeg)

**Comment by soywiz** [comment]
Fixed in 3.0.0-Beta3
