### ISSUE TITLE
Visual Editor 

### ISSUE THREAD

**Issue by atonamy** [korlibs/korge#43]
Now days to compete on game engine market is essential to have visual editor for 3d and 2d game scenes (ideally for game graphics as well), similarly what has been done by GODOT. So the gameplay can be visualised and edited in realtime. 

Any plans of Korge team to develop such a useful and essential tooling?

**Comment by Thanh9356** [comment]
Depends on developers, I just want coding and coding so I don't need a editor, I use design application as a tool makes me know x,y of Sprites

**Comment by soywiz** [comment]
I'm moving this issue to the new `korge-intellij-plugin` repository
