### ISSUE TITLE
Fix the issue where the the locally built 2.0.0.999 results in class references with no documentation

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#440]
Example, when using the 2.0.0.999 version (locally built), here's how the class reference looks like:

**FIGURE 1**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/173179634-bb7c00f0-e608-4068-a99b-986f19e4d5b2.png">

Notices the lack of implementation details and comments.

When using the 3.0.0-Beta3 version, here's how the class references looks like:

**FIGURE 2**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/173179707-780a3d27-4ca0-4044-88a5-4694fddfef4e.png">

**This can be easily reproducible:**

1. Clone the hello world repo: https://github.com/korlibs/korge-hello-world
2. Clone the korge-next repo.
3. Run `publishToMavenLocal` for korge-next
4. Modify hello world project to use version 2.0.0.999
5. Build then check class reference yourself via CTRL+CLICK.
6. Notice how there's no implementation details or comments.

This tells me that there must be some kind of difference that you're doing (or something different in the configuration) when publishing the "production" version and publishing the local version.

**Comment by soywiz** [comment]
I guess this was fixed here: https://github.com/korlibs/korge-intellij-plugin/pull/45
