### ISSUE TITLE
Delayed keyboard/mouse event tracking with lowered FPS

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korge#444]
Hello,
with `targetFPS=60` and `real fps=40` I get very laggy behaviour in sence of keyboard/mouse events. 

Here is the code snippet. Try move the mouse holding ctrl. You will see that events will be consumed even after a lot of time passed. It affects both event consumers and `stage.views.input.keys[LEFT_CONTROL]`.
```kotlin
suspend fun main() = Korge(width = 512, height = 512, targetFps = 60.0, entry = {
	val line = ShapeView(VectorPath(), stroke = WHITESMOKE, strokeThickness = 0.5, fill = TRANSPARENT_WHITE)

	addChild(line)

	var pressing = false

	onDown {
		check(!pressing)
		pressing = true
	}

	onUp {
		if (!it.button.isLeft) return@onUp
		pressing = false
	}

	addUpdater {
		Thread_sleep(1000 / 40)
		if (stage.views.input.keys[LEFT_CONTROL] && pressing) {
			val mousePos = globalToLocal(mouse.currentPosGlobal)
			line.updateShape {
				clear()
				line(256.0, 256.0, mousePos.x, mousePos.y)
			}
		}
	}
})
```

It feels like somewhere internally the engine tracks that this event should be visible for the next `n` frames, forgetting about the real fps. Do you have any ideas what may be the reason?

**Comment by BioRyajenka** [comment]
Hi, the issue seems to be resolved in new korge version. Suppose we can close the ticket?

**Comment by soywiz** [comment]
Sure. Let's close it 👍
