### ISSUE TITLE
Consolidate support/issues/help discord channels

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#446]
I'd like to propose to keep only one of the support/issues/help channels and archive the others. IMO all of these channels are the same thing to me and consolidating to one channel makes it easier to find past content (easier keep track of and CTRL+F on one channel than 3) since it won't be spread out.

You can "archive" channels by disabling commenting for the channels.

I also recommend changing the channel name for the archived channels. E.g "[archived] support"

**Comment by soywiz** [comment]
Done:

* Put a message: `Please use #support channel instead. Closing this one.`
* Disabled posting
* Prepended `#archive-`
* Moved to `Deprecated old channels category`
