### ISSUE TITLE
kbox2d : adding many bodies at once throws exception

### ISSUE THREAD

**Issue by emign** [korlibs/korge#45]
As described in this (closed due to migration to Korge) comment:
[https://github.com/korlibs/korio/issues/34](https://github.com/korlibs/korio/issues/34)

> Also, it should be just a single thread or at least just one thread executing at a time, so shouldn't be a concurrency problem related to threads, maybe the World is in an inconsistent state just before doing a suspension for I/O then it is suspending and a frame occurs that updates the World?

-> Maybe add a initialize block for box2d which creates the bodies in a suspendible manner. At the moment, we just call the Objects in the worldview lambda which causes these problems.

**Comment by soywiz** [comment]
Let's wait for the next version. But an immutable small sample reproducing the issue would help (either a small zip file or a link to a commit in a repository)

**Comment by emign** [comment]
https://github.com/emign/engineEmi/tree/dev

Just compile and run

**Comment by emign** [comment]
Funny thing: Compiling to JS and opening in the browser does NOT show that behavior. It spawns every body and its view correctly.
