### ISSUE TITLE
error: unknown type name 'mingwX64_kref_com_soywiz_klock_DateTime'

### ISSUE THREAD

**Issue by Tlioylc** [korlibs/korge#456]
we met this error when try build mingwx64 sharelib.
Task :library:linkDebugSharedMingwX64
e: Compilation failed: The C:\Users\CJ2DWF3\.konan\dependencies\llvm-11.1.0-windows-x64-essentials/bin/clang++ command returned non-zero exit code: 1.
output:
C:\Users\CJ2DWF3\AppData\Local\Temp\konan_temp14004258268168574351\api.cpp:297:8: error: unknown type name 'mingwX64_kref_com_soywiz_klock_DateTime'
static mingwX64_kref_com_soywiz_klock_DateTime _konan_function_4_impl(mingwX64_kref_me_test_library_Greeting arg0) {
       ^
C:\Users\CJ2DWF3\AppData\Local\Temp\konan_temp14004258268168574351\api.cpp:304:12: error: use of undeclared identifier 'mingwX64_kref_com_soywiz_klock_DateTime'
  return ((mingwX64_kref_com_soywiz_klock_DateTime){ .pinned = CreateStablePointer(result)});

build.gradle.kts:
plugins {     kotlin("multiplatform") }  group = "me.test" version = "1.0-SNAPSHOT"  kotlin {     jvm {         compilations.all {             kotlinOptions.jvmTarget = "1.8"         }         withJava()         testRuns["test"].executionTask.configure {             useJUnitPlatform()         }     }     mingwX64(){         binaries {             sharedLib {                 baseName = "mingwX64"             }         }     }     sourceSets {         val commonMain by getting{             dependencies {                 implementation("com.soywiz.korlibs.klock:klock:2.4.10")             }         }         val commonTest by getting {             dependencies {                 implementation(kotlin("test"))             }         }         val jvmMain by getting         val jvmTest by getting         val mingwX64Main by getting         val mingwX64Test by getting     } } 

code mingwX64Main :
`
actual class Greeting actual constructor() {     actual fun greeting(): String {         return "hello world"     }     fun getReceivedDateTime(): DateTime?{         return null     } }

`

**Comment by soywiz** [comment]
I'm closing this, since it was for a really old version already. Feel free to reopen if makes sense
