### ISSUE TITLE
[DragonBones] The edges of the picture are a bit blurry, but rendering with Cocos is normal

### ISSUE THREAD

**Issue by yunlinos** [korlibs/korge#516]
Use korge-dragonbones to render the animation, and find that the edges of the picture are a little blurry, but it is normal to use Cocos Creator to render. I have set quality to GameWindow.Quality.QUALITY but it has no effect. Is there any way to improve the clarity or solve this problem?

![image](https://user-images.githubusercontent.com/19150644/177153331-e3b4aad8-fa70-401c-968e-f17c5e0ea2bc.png)

**Comment by soywiz** [comment]
@yunlinos Can you provide a dragonbones file and a small korge main function loading it, to reproduce the problem easily?

**Comment by yunlinos** [comment]
@soywiz For some compliance reasons, I cannot provide you the file publicly, I have sent a demo to your gmail(soywiz@gmail.com).

please check it in your gmail, thanks.

**Comment by soywiz** [comment]
I have investigated this, and it seems that that edge would be sharp. Maybe cocos creator is using a MSAA antialiasing or something for the whole canvas. That comes at a cost. I have created a PR to support adding MSAA to Android easily.
