### ISSUE TITLE
Incorrect SVG parsing

### ISSUE THREAD

**Issue by ArtemiyAAA** [korlibs/korge#534]
Tried read and render svg image, but there is parsing error on expressions like `-2.45.624` or `-.003.001` (with two dots) (`java.lang.NumberFormatException: multiple points`)

Path example:
`<path d="M14.6 0c-1.3 0-2.45.624-3.18 1.59v-.001l-1.85 1.85v50.5h37.3l1.85-1.85-.003.001c.965-.723 1.59-1.87 1.59-3.18v-45a3.96 3.96 0 0 0-3.97-3.97z" fill="url(#A)"/>`
`<path d="M11.9 2.65c-1.3 0-2.45.625-3.18 1.59v-.002l-7.14 7.14v50.8h37l7.41-7.41h-.002c.964-.723 1.59-1.87 1.59-3.18v-45a3.96 3.96 0 0 0-3.97-3.97z" fill="url(#B)"/>`

Seems to this is right syntax and there is a bug in parser
![image](https://user-images.githubusercontent.com/79256621/177578234-d6e75ba8-60ef-4dd8-a97b-1257d981a523.png)

Exception thowed from SVG.Companion.tokenizePath (StrReader.readNumber)
![image](https://user-images.githubusercontent.com/79256621/177577851-603460ba-73f8-45ac-9000-ab68955fd864.png)

**Comment by soywiz** [comment]
Just. checked and that was fixed here: https://github.com/korlibs/korge/commit/06f75fb42387d2c57b526277e5b137405dfee651

Available since `3.0.0-Beta3` and also available in the last published version `3.0.0-Beta5`

Which version are you using?

**Comment by ArtemiyAAA** [comment]
@soywiz I used 2.7.0.
3.0.0-Beta5 works fine, Thank you!
