### ISSUE TITLE
Complex UI elements are not styled correctly when a custom UI skin is provided.

### ISSUE THREAD

**Issue by v79** [korlibs/korge#549]
You can override the default style of many UI components by setting the View.uiSkin value. Below I've set a green colour on the elements. This works for basic elements like UIButton.

```kotlin
uiSkin = UISkin {
	val colorTransform = ColorTransform(0.7, 0.9, 0.2)
	this.uiSkinBitmap = this.uiSkinBitmap.withColorTransform(colorTransform)
	this.buttonBackColor = this.buttonBackColor.transform(colorTransform)
	this.textSize = 14.0
}
```

## UIComboBox

- The combo box does pick up the correct green style. But the menu items do not, which are rendered in the default KorGE gray, nor do they pick up `buttonTextAlignment` property.

![ui_combobox_style_bug_1](https://user-images.githubusercontent.com/18570/155715233-99d1e3e3-77d2-4b01-a160-8ce2b0402028.png)

## Checkboxes, Radio buttons

These components do not respect any of the button colour overrides set in the uiSkin. I think you can override the ninepatch/bitmapslices for these buttons, I would have expected them to behave the same as UIButton and be coloured according to `uiSkinBitmap.withColorTransform` when the no custom bitmapslices are provided.

## UIWindow

Is not styleable at all; colours and sizes are hard-coded.

## UITextInput

Does not respect text size from skin. Colours are hard-coded. Cannot be disabled by calling disable().

**Comment by soywiz** [comment]
This is outdated, the UISkin has now disappeared and replaced by styles.
