### ISSUE TITLE
When updating the sprite IDs of a TiledMap layer tile, the view isn't always refreshed and sometimes "stalls" until player action takes place

### ISSUE THREAD

**Issue by v79** [korlibs/korge#551]
**Describe the bug**

I have an RPG-style game using *Tiled* maps. The player can plant crops onto a particular TiledMap.Layer, and once a second the game calls a `grow()` method which returns the ID of sprite for the crop at its current state of growth.

The new sprite ID is assigned to the appropriate tile and _usually_ the TiledMapView refreshes with the updated sprite.

However, this is not guaranteed, and sometimes stalls until another action takes place, like the player moving around the map.

The behaviour is inconsistent.

In the examples below I have "planted" a crop with sprite "1". As it grows, it moves to sprite "2", "3" etc and stops growing at "9".

In both recordings, the visualization of the growth stalls at "4", and in the second recording it stalls again around "7" or "8". Moving the player instantly refreshes the view to show the correct sprites.

### Stalls at 4

![StalledAt4](https://user-images.githubusercontent.com/18570/149652325-1704dbc0-067f-4eb5-a782-303d879e73bf.gif)

### Planting real plants as well as numbers, stalling at 3/4

![StalledAt3And7](https://user-images.githubusercontent.com/18570/149652330-4123977f-57f0-483c-8fa3-ac4c71342351.gif)

Here is the code which calls the growing method, which returns a list of tile update events:

```kotlin
val farmUpdateTime = TimeSpan(1000.0)
tiledMapView.addFixedUpdater(1.timesPerSecond) {
val toUpdate =
	  gameState.growThings(farmUpdateTime, farmland)
toUpdate.forEach { update ->
	  farmland?.let { field ->
		  field[update.tile.x, update.tile.y] = update.tileUpdateEvent.newSpriteID
	  }
  }
  }
```

The full code for the project reproducing this issue is at https://github.com/v79/TheAlchemist/tree/tiledmaprefresh .

(Of course, in making these recordings, the game behaved much better than I had seen myself, when it would usually stall at "1".)

**Annoyment level**

> How annoyed are you in a scale of 1-3 because this shitty code doesn't work properly

* [ ] 1 - No rush from my side
* [X] 2 - It is inconvenient, but I can circumvent the issue for now
* [ ] 3 - FUUUU
* [ ] 4

**Payment**

> How do you plan to compensate the time we will invest fixing this?

* [ ] I will add a message with "Thanks" when merged to let you know I'm grateful
* [ ] I will also add a [meme image](https://imgflip.com/memegenerator) relevant to the issue to make you smile so we both have fun
* [ ] In fact, I'm going to add a meme here in this issue too
* [X] I'm going to write about KorGE in my blog, spread the voice on social networks, or maybe even make a TikTok wearing a KorGE T-Shirt while dancing

> You can also consider donating some money via Github Sponsors to the person fixing the issue.

**Meme**

> Here you can put a meme to motivate us to fix the issue.

**Comment by soywiz** [comment]
This was fixed sometime ago. You have to use the lock, to wrap places where you update the content of the tiles:

https://github.com/korlibs/korge/blob/b6b0cc5404603eff61975592b6d539c099c2ffa0/korge/src/commonMain/kotlin/korlibs/korge/view/tiles/TileMap.kt#L92
