### ISSUE TITLE
Playback of video

### ISSUE THREAD

**Issue by dpreguza** [korlibs/korge#57]
As we know Korge can play audio (through the korau module).
But I found out that there is no way to show a video using korge.

There would be many use cases for video, especially in games.

For example, I want to add some interactive graphics over a video, and I thought korge would be a good choice (though maybe wrong).

So far I'm interested in windows and browser platforms.

What do you think?

Thanks!

**Comment by soywiz** [comment]
Regarding to this. Do you need native decoding? I could do several approaches.

For example, I did this library sometime ago: https://github.com/soywiz/haxe-openfl-webm

I could support a specific codec on all targets by converting a java library into Kotlin and adapting it for Kotlin/Common. That wouldn't support accelerated decoding, but would work the same and consistently on all targets.
For example. I could port this one to Kotlin: https://github.com/jcodec/jcodec

The other approach would be to use the APIs for each different platform. For example: the JS video API, directshow on windows, or AVFoundation on Apple platforms and the Android Media Player.

I could also do a mixed approach. Start with porting a library, and then also supporting the videos supported for each platform progressively with the native APIs.

**Comment by soywiz** [comment]
https://github.com/korlibs/korge-samples/commit/3ced591e97950b3521fdb669e0a0afc82462ae42 <-- Just for the JVM for now and still in early stages
