### ISSUE TITLE
Stroke line graphic not rendered if perfectly horizontal or vertical

### ISSUE THREAD

**Issue by nathanglevy** [korlibs/korge#574]
**Describe the bug**
When using graphics+vectorBuilder to create a straight line, if the line is perfectly verticle or horizontal in endpoints, no line is rendered. Example code:
```
graphics {
		stroke(Colors.BLUE, StrokeInfo(thickness = 3.0)) {
			this.line(Point(10.0,10.0),Point(10.0,52.0))
		}
}
```

**Annoyment level**
It's problematic, the only way I am able to currently get around it is if I add a check in cases where they are perfectly in line and 'shift' the endpoints by several pixels. Far from ideal, and obviously often doesn't look right.
* [X] 2 - It is inconvenient, but I can circumvent the issue for now

Workaround provided by @soywiz - Use the following code instead:
```
solidRect(width = 3.0, height = Point.distance(p1,p2), color = Colors.BLUE) {
        position(p1)
        rotation(Angle.between(p1,p2).minus(Angle.fromDegrees(90)))
        anchor(Anchor.TOP_CENTER)
}
```

**Payment**
> How do you plan to compensate the time we will invest fixing this?
* [X] I will add a message with "Thanks" when merged to let you know I'm grateful
* [X] I'm going to write about KorGE in my blog, spread the voice on social networks, or maybe even make a TikTok wearing a KorGE T-Shirt while dancing

**Comment by soywiz** [comment]
This was fixed already sometime ago
