### ISSUE TITLE
Option to suppress e.printStackTrace() in async()

### ISSUE THREAD

**Issue by ph4r05** [korlibs/korge#593]
Thanks for nice library! I am using it in a project and it works great.

However, I am currently having issues with https://github.com/korlibs/korio/blob/f470e77a69709c93a9134e185aa11f582b7b6822/korio/src/commonMain/kotlin/com/soywiz/korio/async/AsyncExt.kt#L48-L57 

The exception is perfectly handled by the caller, but the `e.printStackTrace()` is polluting my stdout. I would like to get rid of it, but I can come up just with workarounds, like: wrap exceptions to one overriding `printStackTrace()` with an empty body. But this does not work if the exception is thrown by the JVM inside async, e.g., socket exceptions. 

In order to suppress that, I have to reimplement AsyncThread() https://github.com/korlibs/korio/blob/cb4dc4520178deccb28fa6c175cb33a764be3115/korio/src/commonMain/kotlin/com/soywiz/korio/async/AsyncQueue.kt#L48

and replace `asyncImmediately` by 
```kotlin
CoroutineScope(context).async(context, CoroutineStart.UNDISPATCHED)
``` 
and reimplement classes that uses that.

Any ideas how can I suppress this?
Maybe checking system property would work?

Thanks for suggestions!

**Comment by soywiz** [comment]
This waas fixed sometime ago `Environment["DEBUG_ASYNC_LAUNCH_ERRORS"] == "true"` to enable it
