### ISSUE TITLE
VfsFile#delete behaves differently on JVM and native

### ISSUE THREAD

**Issue by saket** [korlibs/korge#595]
Sorry for filing so many issues, but I may have found another discrepancy between JVM and native for `VfsFile#delete`. The JVM implementation is able to delete directories if they're empty, but the native implementation does not. It seems like the `unlink` posix API refuses to delete directories. I understand that I can use `file.vfs.rmdir` for directories, but it may be worth matching their behaviors.

**Comment by soywiz** [comment]
Hey @saket, why did you close this? Is this fixed already?

**Comment by saket** [comment]
Sorry, I was cleaning up all my stale issues that have remained open for many years.

**Comment by schmidt9** [comment]
any updates on this? will this be fixed? I faced this - unable to delete directories on iOS, only files get deleted

**Comment by schmidt9** [comment]
trying to workaround this way, but `rmdir` also fails for some reason not deleting empty directory and returning `false`

```
suspend fun VfsFile.deleteRecursivelyFix(includeSelf: Boolean = true) {
    if (this.isDirectory()) {
        this.list().collect {
            if (it.isDirectory()) {
                it.deleteRecursivelyFix()
            } else {
                it.delete()
            }
        }
    }
    if (includeSelf) {
        if (this.isDirectory()) {
            this.vfs.rmdir(this.path)
        } else {
            this.delete()
        }
    }
}
```

**Comment by soywiz** [comment]
This is rmdir on native:

https://github.com/korlibs/korlibs-io/blob/b0d7410ea0bc21e06e33d908aead97aac0e06540/korlibs-io/src%40native/korlibs/io/file/std/LocalVfsNative.kt#L290-L291

It is a direct call to native posix rmdir. If it is not working, it might be either permissions or something I'm not aware. But feel free to make PRs to that repo.
