### ISSUE TITLE
How to check whether sound is still playing?

### ISSUE THREAD

**Issue by aoussou** [korlibs/korge#614]
Hello,

I'm looking for a way of checking whether a sound is till playing in KMP (desktop only). It seems like the "playing" attributes of NativeSoundChannel might be what I'm looking for but I've been unable to access it.

Approach 1:

    val nsp = NativeSoundProvider()
    val wavBytes =  File(path).readBytes()
    sound = nsp.createSound(wavBytes)
    sound.playAndWait()

sound has no attribute "playing"

Approach 2:

        val sound = resourcesVfs[path].readSound()
        val channel = sound.play()
        channel.await()

This doesn't work because it can't find the file in "src/main/resources"

Is there an alternative to check whether the sound is playing?

**Comment by soywiz** [comment]
Closing this, as there is an issue linked to this one regarding documenting this.
