### ISSUE TITLE
AES256/SHA512...etc

### ISSUE THREAD

**Issue by cydhhp** [korlibs/korge#628]
I Love this Project
It is very useful fir me
Now 
I need
1.AES 256 with IV
2.SHA512
3.HMACSHA256
for pure kotlin in commonMain
May you help to build new version
Thanks a lot

**Comment by dzikoysk** [comment]
There's SHA512 impl in commonModule, but idk if it works properly:

* https://github.com/korlibs/korge/blob/e0e9acfda95ff2af3cbd3517bfec4c98cada8559/krypto/src/commonMain/kotlin/korlibs/crypto/SHA512.kt#L66

Do you think it should be listed on website (https://docs.korge.org/krypto/#hash-md5sha1sha256), or is it still not safe to use? 🤔

**Comment by soywiz** [comment]
These tests are passing:
* https://github.com/korlibs/korge/blob/e0e9acfda95ff2af3cbd3517bfec4c98cada8559/krypto/src/jvmTest/kotlin/korlibs/crypto/SHA512JvmTest.kt#L8
* https://github.com/korlibs/korge/blob/e0e9acfda95ff2af3cbd3517bfec4c98cada8559/krypto/src/commonTest/kotlin/korlibs/crypto/SHA512Test.kt#L7

I guess that comment refers to the need of doing the override. But the implementation seems to work.

**Comment by iTanChi** [comment]
@soywiz Could you update to support HmacSHA512?
```
fun hmacSHA512(key: ByteArray, data: ByteArray): Hash = hmac(key, data, SHA512())
```
 In the code I see that you are using it in pbkdf2:
```
fun pbkdf2WithHmacSHA512(password: ByteArray, salt: ByteArray, iterationCount: Int, keySizeInBits: Int): Hash =
            pbkdf2(password, salt, iterationCount, keySizeInBits, SHA512())
...
u = HMAC.hmac(password, u, hasher).bytes // hasher is SHA512()
```

**Comment by soywiz** [comment]
I'm going to close this issue. The reason is that this is issue not [S.M.A.R.T](https://en.wikipedia.org/wiki/SMART_criteria) and covers too many cases. Feel free to open one per use-case.
@iTanChi feel free to open an issue for HMAC SHA512.
