### ISSUE TITLE
Maven description -> Multiplatform Kotlin Game Engine 

### ISSUE THREAD

**Issue by MartinX3** [korlibs/korge#634]
It says it's a `Multiplatform Kotlin Game Engine` everywhere
https://mvnrepository.com/search?q=Soywiz+korte

As a new user it confuses me, which package I should use in my quarkus project to convert string templates from the database for usage in emails.

Also there is version 2.3.1, while this repo only has version 2.2.0.
So I think these packages are wrong.

**Comment by soywiz** [comment]
Well the maven description was updated, so I guess this is fixed.
