### ISSUE TITLE
FolderBasedNativeSystemFontProvider doesn't find fonts recursively

### ISSUE THREAD

**Issue by xszqxszq** [korlibs/korge#648]
On Windows, fonts are placed in `C:\Windows\Fonts` directly, but on linux they're usually inside folders under `/usr/share/fonts`, such as `/usr/share/fonts/liberation-mono/LiberationMono-Bold.ttf`. 

I tested and found that only those not inside subfolders of `/usr/share/fonts` could be listed and loaded when using FolderBasedNativeSystemFontProvider.

**Comment by soywiz** [comment]
This was fixed here: https://github.com/korlibs/korge/commit/a3748612107f71e3073154579816ade85cb18f22#diff-8a781a907de28df225e8a440b7c49b1f77115254f3afe63280b0815b598ff22dR145
