### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ghost** [korlibs/korge#653]
I want to use this library, but I don't find any documentation.

The link to "Full documentation" is the same content as on GitHub. I miss a "Getting started" or any kind of sample project to see how I can use it to load Bitmaps, resize them and so on.

Do I overlook something or is there right now no documentation at all?

**Comment by soywiz** [comment]
I believe this specific issue is solved. There are other tasks for other parts of the documentation. For this one:
https://docs.korge.org/imaging/bitmap/#scaling-a-bitmap
