### ISSUE TITLE
broken readme badge - "CI no status"

### ISSUE THREAD

**Issue by matkoniecz** [korlibs/korge#67]
https://github.com/korlibs/korge#korge

**Comment by emign** [comment]
I think this is intended behavior in the time, the CI-Task is actually running. After it finishes, the badge should be displayed properly

**Comment by matkoniecz** [comment]
It is now shown as "passing". "running" or showing latest status would be nicer, but it seems to be quite good, better than usual permanently broken CI badge.

**Comment by soywiz** [comment]
Can't do anything about it. Travis used to cache the latest finished result, but Github Actions doesn't and reports about the latest task even if. They will probably fix it at some point, but can't do anything myself, so I'm closing this issue.
