### ISSUE TITLE
DateFormat("z") is not working with "+09:00"

### ISSUE THREAD

**Issue by kubode** [korlibs/korge#670]
Hi.
When I was upgrading from 1.12.0 to 1.12.1, my test cases using `DateFormat("z")` went failing after that.

```kotlin
    @Test
    fun test() {
        val expected = TimezoneOffset(9.hours)
        val actual = DateFormat("z").parse("+09:00").offset
        assertEquals(expected, actual)
    }
```

This test case success with 1.12.0 but, it fails with 1.12.1 and 2.0.0-rc2.

```
kotlin.AssertionError: Expected <GMT+0900>, actual <UTC>.
```

Changes between 1.12.0 and 1.12.1: https://github.com/korlibs/klock/compare/v1.12.0...v1.12.1

**Comment by soywiz** [comment]
This was already fixed
