### ISSUE TITLE
Bugs when parsing DateTimeTz from string in AM/PM format

### ISSUE THREAD

**Issue by CharlesKozel** [korlibs/korge#676]
I found two issues when attempting to parse a DateTimeTz from a string with AM/PM format. 

1.  "am" or "pm" must be lowercase.
2.  a PM time from 12:00pm to 12:59pm is incorrectly converted into 24 hour time such that 12:30pm is converted to 00:30 +1day

**Comment by soywiz** [comment]
This was fixed already
