### ISSUE TITLE
Circle scaling issue

### ISSUE THREAD

**Issue by LeHaine** [korlibs/korge#723]
Description: When scaling a parent container with a `Circle` child view that is not anchored at 0, 0 causing the circle rendering to move from the correct position. When the `Circle` view is anchored to 0, 0 it will scale correctly. Tested in game.

![Video in game](https://user-images.githubusercontent.com/4951150/117442038-3cd11f00-af04-11eb-8e24-26c30ad84aee.mp4)

**Comment by soywiz** [comment]
I believe this was fixed sometime ago.
