### ISSUE TITLE
Update documentation to state that the artifacts are being published to Maven Central

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge#733]

**Comment by NorbertSandor** [comment]
Wow, I almost _not_ used this nice library because I thought it is not published to Maven Central :)

**Comment by soywiz** [comment]
@NorbertSandor what made you think that they might not have been published to central? Is there a specific text or something stating the opposite? or the lack of finding information about it?

**Comment by NorbertSandor** [comment]
Now I see the "maven-central" badge on the GitHub page.
But first I've only seen some info about "./gradlew publishToMavenLocal" and how to use it with a weird version number.
Maybe the first page should contains some more explicit info about using via Maven Central...
Btw. it was my fault, I should have paid more attention, sorry...

**Comment by soywiz** [comment]
No worries, and not your fault at all. If it is not obvious, we can make improvements to make it more obvious. Since you discovered the central badge, maybe that helps to make it more obvious. I ahve added it to the documentation:
* https://github.com/korlibs/korge/commit/de656f3f25dcf813b0ef9fca6511b0a81255c82b

<img width="782" alt="2023-06-05_22-59-39" src="https://github.com/korlibs/korge/assets/570848/06cccb83-ef36-4924-9f4f-57c9b9f8e2cc">
