### ISSUE TITLE
Energy efficiency: Add API to dynamically control maximum FPS

### ISSUE THREAD

**Issue by yvolk** [korlibs/korge#739]
I noticed that even when [my code](https://github.com/andstatus/game2048/blob/master/README.md#readme) does nothing, the KorGe app consumes a lot of CPU / GPU.
The pattern is similar both for jvmRun (CPU % depends on window size...) and for Android run (about 47% CPU when full screen).
I suspect that even "idle" app draws the same image on a screen many times per second in the "game loop"...

This is a critical feature for energy / computation efficiency.
Every game has pauses, when nothing changes on a screen for some time. Doing 1 fps e.g. for time ticks would be enough for such cases. Or even zero fps for static screens / pictures.

As @soywiz noted, this is not currently implemented, but could be implemented in a future version. Both not flipping the buffer and adjusting the fps.

**Comment by soywiz** [comment]
Since 4.0.0, you can now do:

```kotlin
fun main() = Korge(forceRenderEveryFrame = false) {
}
```

This will re-render the window only when something changed.

https://github.com/korlibs/korge/blob/656078f3a41505f1b1625f39210edb3cb2110117/korge/src/commonMain/kotlin/korlibs/korge/Korge.kt#L85
