### ISSUE TITLE
Error on `publishToMavenLocal` - Expected object 'NativeStorage' has no actual declaration in module 

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#74]
Running `publishToMavenLocal` causes an error:

<img width="499" alt="2020-01-21_11h06_47" src="https://user-images.githubusercontent.com/1190109/72795662-4adf2b80-3c3e-11ea-9685-f222d94f8fc8.png">

``` java
e: C:\Users\Tobse\IdeaProjects\games\tools\korge-engine\korge\src\commonMain\kotlin\com\soywiz\korge\service\storage\
NativeStorage.kt: (3, 15): Expected object 'NativeStorage' has no actual declaration in module 
````

So the build step ` :korge:compileKotlinNativePosix` is broken. The other build targets work fine.

Also checked this on a second PC after a fresh checkout.  
**System:** Windows, IntelliJ Ultimate 2019.3 - Gradle 5.6.4  - Java JDK 12 - Kotlin 1.3.61

**Comment by soywiz** [comment]
I guess this is not an issue anymore. Closing it 👍
