### ISSUE TITLE
Weird hash mismatch on supportBox2D() call on windows machines 

### ISSUE THREAD

**Issue by emign** [korlibs/korge#740]
Compiling a project on windows machines produces this error:

```
Bundle 'korge-box2d' expects 
SHA256 = d15f5b28abbc2f58ba375d7204a6db2e90342978d02e675cd29249d0cade8f9f , 
but found SHA256 = e5559756b3b45d25663806318b74f502eaf57fe4b702b694fbf23c1010c64dd0
```

The same build on linux and Mac does report other errors

You can easily compare the issues here:

Windows: https://github.com/emign/projektQ11_21/runs/1960680315?check_suite_focus=true
Mac: https://github.com/emign/projektQ11_21/runs/1960680250?check_suite_focus=true
Linux: https://github.com/emign/projektQ11_21/runs/1960680187?check_suite_focus=true

For reference:
https://discord.com/channels/728582275884908604/728616340239417375/813727595664769035

**Comment by soywiz** [comment]
I guess this was for bundles and now kproject is used instead. So let's close this
