### ISSUE TITLE
Charset.forName() always returns UTF8

### ISSUE THREAD

**Issue by zhanghai** [korlibs/korge#794]
https://github.com/korlibs/korge/blob/78125b99e432601479e0454ec31f67fc4a5bd395/korio/src/commonMain/kotlin/com/soywiz/korio/lang/Charset.kt#L21-L23

There's [Charset](https://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html) on JVM and [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) on the Web, so maybe we can at least make it work on these platforms? For native, maybe we can use `libiconv` [like ktor](https://github.com/ktorio/ktor/blob/main/ktor-io/posix/src/io/ktor/utils/io/charsets/CharsetNative.kt#L15)

**Comment by zhanghai** [comment]
I'm trying to parse some local files that were provided with Shift-JIS encoding. For now I rolled my own platform-dependent solution for JVM and JS as described in my initial comment, and yes maybe I should just pre-process them, because integrating `libiconv` may not be trival (probably still better than ICU though).

But for the sake of being a library, maybe it's still better to throw an exception on unsupported charset, instead of silently returning a UTF-8 instance?

**Comment by soywiz** [comment]
Thanks for the details. I have already made a PR with that throws and also supports the other embedded charsets. Also I have added a mechanism to plug-in other charsets, so one could fallback to `libiconv`, `jvm.Charset` and `TextDecoder`.

Let me elaborate on this:

The problem of using strings to load the charset is that your binary has to include all the charsets supported by the libraries even if you don't use them. So if I include libiconv I would need to increase the binary size including a library that might have characters that most people won't use. I plan to make a WASM -> C+SDL converted so people can compile korge games in any platform supporting a C compiler, SDL and OpenGL, and thus I want to keep referenced dependencies really limited and code size as restrained as possible for the JVM and JS this wouldn't increase the binary size but for WASM, K/N it would.

Still I see your point on wanted to support that, and thus I have added the extension mechanism for registering charsets. I could provide a piece of code registering libiconv, jvm.Charset and TextDecoder, while not having to include the whole charsets for everyone that won't use them in a way that dead code elimination won't work.

**Comment by zhanghai** [comment]
Thank you for the reply!

Considering JVM `Charset` and JS `TextDecoder` are built-in and incur minimal cost on code/binary size, can we include them in Korge by default? `libiconv` would surely still require extra work if one wants to support native. This would make it similar to the situation of media codecs, we provide what's avaialble on the platform by default so every platform may be different.

And just in case it may be helpful, this is my simple Kotlin/JS implementation of a minimal charset:

```kotlin
actual class Charset(private val textDecoder: TextDecoder) {
    actual val name: String
        get() = textDecoder.encoding

    actual fun decode(buffer: ByteArray, offset: Int, length: Int): String =
        textDecoder.decode(buffer.unsafeCast<Uint8Array>().subarray(offset, offset + length))

    actual companion object {
        actual fun forName(charsetName: String): Charset = Charset(TextDecoder(charsetName))
    }
}

external class TextDecoder(utfLabel: String) {
    val encoding: String

    fun decode(buffer: ArrayBufferView): String
}
```
