### ISSUE TITLE
When we install the library then we got some error

### ISSUE THREAD

**Issue by GaurDev06** [korlibs/korge#796]
Could not resolve com.soywiz.korlibs.korim:korim:2.2.0.
Required by:
    project :shared
    
And if we remove  iosSimulatorArm64() from my code then it will successfully implemented.
And in case of IOS app it's necessary to run the app.

**Comment by soywiz** [comment]
Hey @GaurDev06 `2.2.0` didn't support ios simulator arm64. Can you try `3.0.0-Beta6`? https://github.com/korlibs/korge/releases/tag/v3.0.0-Beta6
