### ISSUE TITLE
Infinite busy loop when playing MP3 sound infinitely finishes the first playback

### ISSUE THREAD

**Issue by zhanghai** [korlibs/korge#799]
`SoundAudioStream` implements `PlaybackTimes.INFINITE` with the following loop that invokes `stream.currentPositionInSamples = 0L` and replays the audio:

https://github.com/korlibs/korge/blob/75eb38c9382459cb64eaa64946496604ad971ace/korau/src/commonMain/kotlin/com/soywiz/korau/sound/SoundAudioStream.kt#L40-L53

However, the `AudioStream` implementation inside `BaseMinimp3AudioFormat` never sets `finished` back to `false` once the playback is finished for the first time:

https://github.com/korlibs/korge/blob/75eb38c9382459cb64eaa64946496604ad971ace/korau/src/commonMain/kotlin/com/soywiz/korau/format/mp3/minimp3/BaseMinimp3AudioFormat.kt#L46-L96

As a result, `SoundAudioStream` will get into an infinite busy loop and the game will hang:

```kotlin
                while (times.hasMore) { // true
                    while (!stream.finished) { // false
...
                    }
                    times = times.oneLess
                    stream.currentPositionInSamples = 0L
                }
```

**Comment by soywiz** [comment]
Superseeds https://github.com/korlibs/korge/issues/505
