### ISSUE TITLE
Allow using pre-multiplied alpha when blending

### ISSUE THREAD

**Issue by zhanghai** [korlibs/korge#827]
(Sorry for the frequent edits - I kept realizing my previous thought was wrong.)

Currently rendering to texture results in rendering with straight alpha, which doesn't allow a number of blending mode to be implement correctly.

For example, the color of the OVER operator should be ![{C_{o}={\frac {C_{a}\alpha _{a}+C_{b}\alpha _{b}(1-\alpha _{a})}{\alpha _{o}}}}](https://wikimedia.org/api/rest_v1/media/math/render/svg/7b9ae9d876ada5aa76414829b379ed13cef81645), however that's not possible with straight alpha because there's no way to divide by ![{\alpha _{o}}](https://wikimedia.org/api/rest_v1/media/math/render/svg/6b97ca5af177111e7be85910a51bf682ed2225fa).

Another example is the PLUS_LIGHTER operator, though it doesn't seem formally defined. But if we do it with straight alpha, the background would become unexpectedly darker (unless it's opaque) every time we blend onto it, due to color being multiplied with alpha every time. However with premultiplied alpha, we won't have such an issue. See also the code on https://jakearchibald.com/2021/dom-cross-fade/ :

```
// Red 50% opacity
const source = [1, 0, 0, 0.5];
// Blue 50% opacity
const destination = [0, 0, 1, 0.5];

// plus-lighter also works with premultiplied colours:
const premultipliedSource = multiplyAlpha(source);
const premultipliedDestination = multiplyAlpha(destination);

const premultipliedResult = premultipliedDestination
  // But then the pixels are just added together:
  .map((channel, i) => channel + premultipliedSource[i])
  // Clamped to 0-1:
  .map((channel) => {
    if (channel < 0) return 0;
    if (channel > 1) return 1;
    return channel;
  });

// Then, the alpha is unmultiplied:
const result = unmultiplyAlpha(premultipliedResult);
```

**Comment by soywiz** [comment]
Yeah, my plan was to use always premultiplied alpha on render targets but the main one (that is the final output and AFAIK cannot be set as premultiplied). To support all blend modes, maybe render everything in a internal buffer.

What I'm going to do initially, is to allow to specify blending factors for premultiplied destinations, and for non-premultiplied destinations with alpha=1, and use one or another depending on the render targets. Intermediate render targets will be considered as premultiplied alpha

**Comment by zhanghai** [comment]
Note that I'm a bit surprised to find that the `Texture.premultiplied` is `true` for the ones used for filters, so that the default shader for `IdentityFilter` would automatically unmultiply alpha for the pixels drawn onto the texture, and make the end result for two images in my case look correct.

https://github.com/korlibs/korge/blob/f59ed0ed5a0c15696d467b7a9f8d7058c9edc986/korge/src/commonMain/kotlin/com/soywiz/korge/render/BatchBuilder2D.kt#L806-L808

However it seems to me this behavior is still strange (despite happening to work for me), considering that we didn't use premultiplied alpha when rendering onto the texture, but we are still considering the texture premultiplied alpha and doing unmultiplication for it.

This is also confirmed by the following code that uses `BlendMode.NONE` for the semi-transparent image on RHS in an container with `IdentityFilter` and finds non-opaque pixels unexpectedly become brighter due to the extra unmultiplication.

```kotlin
suspend fun main() = Korge(width = 1024, height = 512, bgcolor = Colors.WHITE) {
    val identityFilterContainer = container {
        filter = IdentityFilter
    }
    val bitmap = resourcesVfs["korge.png"].readBitmap()
    fun Container.image(x: Int, y: Int, alpha: Double, blendMode: BlendMode) =
        image(bitmap, 0.0, 0.0) {
            this.blendMode = blendMode
            position(x, y)
            alpha(alpha)
        }
    val image1 = image(0, 0, 0.5, BlendMode.INHERIT)
    val image2 = identityFilterContainer.image(512, 0, 0.5, BlendMode.NONE)
}
```

![image](https://user-images.githubusercontent.com/4469895/178715545-d5a4b1d8-03be-4e5d-a787-03fa4f875c4b.png)

(I hope I'm finally having a correct understanding of the situation now...)

**Comment by soywiz** [comment]
@zhanghai Can you try https://github.com/korlibs/korge/pull/831 and see if it helps here?

**Comment by zhanghai** [comment]
Do you know if there's any easy way to try #831? I assume building Korge locally on my machine would take some time set up and would like to avoid that if possible. If I have to build Korge locally, do you have any doc on that and on how to use a local Korge build in my project?

**Comment by zhanghai** [comment]
Note that I would also found (interrupting) animations on an `Image` inside such a `Container` with `IdentityFilter` seems to affect the alpha of `Image` sibling to the container under some circumstances - sometimes it seems the other `Image` got premultiplied alpha shown directly so that it became darker, and sometimes it seems to lose any pixels with alpha. I don't have a clean MWE to reproduce this yet (though it can be stably reproduced in my project), and not sure if your PR can fix that as well, but just wanted to let you know in advance.

**Comment by soywiz** [comment]
It is fast and straightforward to compile it:
```
git clone/checkout
…
./gradlew publishJvmPublicationToMavenLocal
…
Then use korge 2.0.0.999 in your project
```

By default it search first on mavenLocal, then on central, so it just works

**Comment by soywiz** [comment]
Regarding to affecting other parts: that looks like a problem with the batcher. Which version of korge are you using?

**Comment by zhanghai** [comment]
> Regarding to affecting other parts: that looks like a problem with the batcher. Which version of korge are you using?

`3.0.0-Beta6`

**Comment by zhanghai** [comment]
@soywiz I got a signing issue when publishing to local Maven:

```
> Task :korge-gradle-plugin:signKorgePluginMarkerMavenPublication FAILED
Kotlin build report is written to /home/zh/workspace/git/external/korge/build/reports/kotlin-build/korlibs-build-2022-07-14-21-34-08.txt

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':korge-gradle-plugin:signKorgePluginMarkerMavenPublication'.
> Cannot perform signing task ':korge-gradle-plugin:signKorgePluginMarkerMavenPublication' because it has no configured signatory
```

Is there any way to work around it? (I tried searching on the Internet and tried things but I'm not familiar enough with gradle to get it working.)

**Comment by zhanghai** [comment]
@soywiz Another issue with local publication - after I run `publishJvmPublicationToMavenLocal` and used `korge = { id = "com.soywiz.korge", version = "2.0.0.999" }` in my project, the `runJvm` task still looked for the common artifact in addition to the JVM ones that's available, which created a lot of dependency errors.

```
Execution failed for task ':compileKotlinJvm'.
> Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlinJvm'
   > Could not resolve all files for configuration ':jvmCompileClasspath'.
      > Could not find com.soywiz.korlibs.korvi:korvi:2.0.0.999.
        Searched in the following locations:
          - file:/home/zh/.m2/repository/com/soywiz/korlibs/korvi/korvi/2.0.0.999/korvi-2.0.0.999.pom
          - https://repo.maven.apache.org/maven2/com/soywiz/korlibs/korvi/korvi/2.0.0.999/korvi-2.0.0.999.pom
          - https://dl.google.com/dl/android/maven2/com/soywiz/korlibs/korvi/korvi/2.0.0.999/korvi-2.0.0.999.pom
        Required by:
            project :
      > Could not find com.soywiz.korlibs.klock:klock:2.0.0.999.
        Searched in the following locations:
          - file:/home/zh/.m2/repository/com/soywiz/korlibs/klock/klock/2.0.0.999/klock-2.0.0.999.pom
          - https://repo.maven.apache.org/maven2/com/soywiz/korlibs/klock/klock/2.0.0.999/klock-2.0.0.999.pom
          - https://dl.google.com/dl/android/maven2/com/soywiz/korlibs/klock/klock/2.0.0.999/klock-2.0.0.999.pom
        Required by:
            project :
```

I also tried `./gradlew publishToMavenLocal` to build Korge for all the targets but then it asked me to install a lot of things including Android SDK. Is there a way to build & publish the common artifacts only?

**Comment by soywiz** [comment]
`publishJvmLocal` publishes JVM and common artifacts:

* https://github.com/korlibs/korge/blob/171c21eac63a546c4a21b16e00a7a7dacba5c7cc/build.gradle.kts#L1139

In theory android is only configured if an SDK is detected:

https://github.com/korlibs/korge/blob/171c21eac63a546c4a21b16e00a7a7dacba5c7cc/build.gradle.kts#L136-L141

Signing is only configured if there are the following properties in your `~/.gradle/gradle.properties` file (`signing.signingKey` or `signing.secretKeyRingFile`):

https://github.com/korlibs/korge/blob/171c21eac63a546c4a21b16e00a7a7dacba5c7cc/buildSrc/src/main/kotlin/com/soywiz/korlibs/modules/Signing.kt#L17

Typically from a fresh computer it builds normally, since the android sdk is not detected and those gradle properties are not set

**Comment by zhanghai** [comment]
I see, that explains things except for the common libraries weren't published with `publishJvmPublicationToMavenLocal`. I'm an Android developer and I have my PGP key ID (but not password) in gradle.properties. I also have an Android SDK but I only installed the latest stable platform (API 32). In the end, I passed my password with command line and installed the required Android SDK components to run the full build, and I was able to use the local build in my project.

The result is promising - I only had to hack `BlendMode.ADD` because it's still using the non-premultiplied `AG.Blending.ADD`, so just one additional little thing to fix.

https://github.com/korlibs/korge/blob/171c21eac63a546c4a21b16e00a7a7dacba5c7cc/korge/src/commonMain/kotlin/com/soywiz/korge/view/BlendMode.kt#L47

https://github.com/korlibs/korge/blob/171c21eac63a546c4a21b16e00a7a7dacba5c7cc/korgw/src/commonMain/kotlin/com/soywiz/korag/AG.kt#L326-L329

After hacking it to `Blending(BlendFactor.ONE, BlendFactor.ONE, BlendFactor.ONE, BlendFactor.ONE)`, the additive blending can work properly. And in general I guess having everything pre-multiplied would also benefit texture filtering, so thanks for fixing this!

Regarding the other potential batcher issue (https://github.com/korlibs/korge/issues/827#issuecomment-1184357392), unfortunately it is still reproducibe. I suspect it's related to usage of animation, IdentityFilter and addition/removal of `Image` instances around that time. If this doens't provide any meaningful clue for you, I can also try to create a MRE for it later.

**Comment by zhanghai** [comment]
Hmm.. upon further debugging, I'm suspecting this is related to my usage of `zIndex` - the problem seems to disappear when I set a `Container` with a larger index in its parent but with a smaller `zIndex` than its predecessor, to invisible, and comes back when I set it back to visiblie. Do you know if the batcher could be misbehaving in terms of alpha pre/unmultiplication when child order isn't the same as `zIndex` order?
