### ISSUE TITLE
The onDown event cordiantes are not scaled

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#83]
The `onClick` event coordinates are scaled with the current screen size. But the `onDown` event isn't. After changing the window size, you can still use the `onClick` event, but the `onDown` coordinates are wrong.

**How to reproduce:**
``` kotlin
suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors["#2b2b2b"]) {
    val image = image(resourcesVfs["korge.png"].readBitmap()) {
        anchor(.5, .5)
        scale(.8)
        position(256, 256)
    }

    onClick {
        println("onClick:" + it.currentPos)
    }
    onDown {
        println("onDown:" + it.downPos)
    }

}
```

Now click on the right alien eye:
![2020-02-09_19h53_55](https://user-images.githubusercontent.com/1190109/74108030-0af0d180-4b76-11ea-8d50-6e023360b3bb.png)

It will print out the correct coordinates for both event types:
```
onDown:(281, 270)
onClick:(281, 270)
```
Then change the window size and click the eye again:
```
onDown:(696, 657)
onClick:(276.88091353996737, 274.3752039151713)
```

As you can see the new `onDown` coordinates are `696, 657` instead of `276.88, 274.37`.

So I can't use mouse events on scaled window instances. Is there a build in way to map these coordinates to the right world pixels?

**Comment by emign** [comment]
Mac 4K Monitor here:
Click unscaled:

```
onDown:(556, 557)
onClick:(278, 278)
```

Click scaled:

```
onDown:(1117, 1003)
onClick:(278.0215053763441, 276.094623655914)
```

**Comment by soywiz** [comment]
I have added `downPosLocal` and `upPosLocal` and deprecate old names that were confusing about the coordinate system. Now there are variants suffixed with Global and Local.

In the meantime, you can use there extension methods:
```
val MouseEvents.downPosLocal get() = view.globalToLocal(downPos)
val MouseEvents.upPosLocal get() = view.globalToLocal(upPos)
```
