### ISSUE TITLE
Box2D dependency URL in documention incorrect

### ISSUE THREAD

**Issue by hughjdavey** [korlibs/korge#84]
Hi - let me know if this is the right place to put this :)

I was trying to add Box2D to the Korge sample project, and the [docs here](https://korlibs.soywiz.com/korge/physics/box2d/) say you need to add:
```
dependencies {
    commonMainApi "com.soywiz:korge-box2d:$korgeVersion"
}
```
to your `build.gradle`. However this did not work for me as IntelliJ could not find the dependency anywhere. After finding someone else's project using Korge on GitHub I realized it should actually be:
```
dependencies {
    commonMainApi "com.soywiz.korlibs.korge:korge-box2d:$korgeVersion"
}
```

Also the docs don't mention that you need `supportBox2d()` in your `korge` plugin block.

I am happy to update the docs and make a PR if they are in a public repo, but I couldn't find them.

Thanks for your time.

**Comment by soywiz** [comment]
This is the right repo: https://github.com/korlibs/korlibs.soywiz.com/

You can also change it yourself if you want with the pencil button:
https://github.com/korlibs/korlibs.soywiz.com/blob/master/korge/physics/box2d/index.md

**Comment by hughjdavey** [comment]
Thanks for picking this up
