### ISSUE TITLE
linkReleaseExecutableMingwX64 error

### ISSUE THREAD

**Issue by jihuayu** [korlibs/korge#86]
I use linkReleaseExecutableMingwX64 tasks,but it give me a error.
[error change](https://github.com/jihuayu/korge-bug/commit/e20059622736f3ebe1fb7159af5e547cecea7b8b)
[error report](https://github.com/jihuayu/korge-bug/runs/451856270?check_suite_focus=true#step:4:72)

[succeed report](https://github.com/jihuayu/korge-bug/runs/451855813?check_suite_focus=true)

this is my [github action script](https://github.com/jihuayu/korge-bug/blob/master/.github/workflows/master.yml)

**thinks**

**Comment by soywiz** [comment]
Can you try to change `1.5.6.0` to `1.5.6.3` (that is the latest version)?

**Comment by jihuayu** [comment]
Also [error report](https://github.com/jihuayu/korge-bug/runs/452046923?check_suite_focus=true#step:4:73)
[version](https://github.com/jihuayu/korge-bug/blob/master/gradle.properties)

**Comment by soywiz** [comment]
I will investigate 👍 maybe it's a bug in Kotlin/Native that can be avoided

**Comment by soywiz** [comment]
Reported here: https://github.com/JetBrains/kotlin-native/issues/3956

**Comment by soywiz** [comment]
I am able to circumvent the issue: https://www.youtube.com/watch?v=5-Y8Juwewic
