### ISSUE TITLE
Suspend alternative to addUpdater

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korge#873]
Hi, is there any suspend alternative to `addUpdater()`?
I.e. something which will allow me to write
```kotlin
suspend fun View.foo(ts: TimeSpan) {}

view.addUpdater(::foo)
```

Thanks!

meme for you
<img src="https://user-images.githubusercontent.com/9904421/180618053-8e7a253e-af67-4ef7-aabb-8c19d8f34585.png" width="45%" />

**Comment by soywiz** [comment]
@BioRyajenka What do you want to achieve with this? Do you have any example? Suspending in something that executes every 16ms is a bit dangerous, in fact right now, until multihreaded rendering is enabled, suspensions are executed in the next frame so this would probably end in a behaviour not working as expected.
Alternatively you can do something like:

https://github.com/korlibs/korge/blob/fe4eb1e1ad9eaec35b7ff79ae5ca434d53897826/korge-sandbox/src/commonMain/kotlin/samples/MainCoroutine.kt#L23

https://github.com/korlibs/korge/blob/fe4eb1e1ad9eaec35b7ff79ae5ca434d53897826/korge-sandbox/src/commonMain/kotlin/samples/MainCoroutine.kt#L38

**Comment by BioRyajenka** [comment]
I was looking for ways to write UI code conveniently. What I wanted to archieve may be represented by the following pseudo code:
```kotlin
suspend fun respondToUserInput() {
	...
	val additionalInfo = if (additionalInfoNeeded) {
		askForAdditionalInfo() // show some UI dialog here, suspending until answer received
	} else null
	... // do the rest
}
```

I even implemented handmade version of `addSuspendableUpdater()`, but it gave me poor user experience: `keys` events seems to be relevant only on *non-suspendable* frame ticks.

For now I decided to go with simple old-fashioned 
```kotlin
suspend fun respondToUserInput() {
	...
	if (...) {
		askForAdditionalInfo(onFinish = ::doTheRest)
	} else doTheRest()
}
```

**Comment by soywiz** [comment]
If you want to have a lightweight thread to sequentially wait for a key and then do something, you can do a launch:

```
launchImmediately {
  while (true) {
    println("Do something")
    val key = keys.onKeyPress.waitOne() // <-- suspending
    println("Do something with the key")
  }
}
```

**Comment by BioRyajenka** [comment]
I am waiting not for the key, but for the other kind of UI interaction (button click in my case).
But thanks for the suggestion, didn't know about it!

I think we can close the issue, wdyt? Maybe this kind of convenience is just not achivable yet :(

**Comment by soywiz** [comment]
@BioRyajenka Please, have a look to this code:

https://github.com/korlibs/korge/pull/894/files#diff-88f96a4ef19b052cea2357b3310889c2bae1eaab0beeb6276113a5d2bfc0d68dR17-R41

If you create a `CancellableGroup` a `CompletableDeferred` and register several events, you can register to several events and wait for one to be triggered like the code in the sample. Does that work for you?

**Comment by BioRyajenka** [comment]
Hmm it might work. Thank you so much, I will try!
