### ISSUE TITLE
SoundChannel.playingOrPaused from readMusic() always returns true on JS/Chrome

### ISSUE THREAD

**Issue by zhanghai** [korlibs/korge#874]
It works fine on JVM and will properly return `false` when audio has finished playback, but on JS/Chrome it keeps returning `true` even after playback has finished.

**Comment by soywiz** [comment]
Thanks for reporting. I will investigate

**Comment by soywiz** [comment]
I was not able to reproduce it with this code:

```kotlin
    val sound = resourcesVfs["sounds/Snowland.mp3"].readSound()
    val channel = sound.play()
    launchImmediately {
        while (true) {
            println("channel.playingOrPaused=${channel.playingOrPaused}, channel.playing=${channel.playing}, channel.paused=${channel.paused}")
            delay(1.seconds)
        }
    }
```

Works fine on the JVM and JS on the main branch: true -> false when the playback finishes. Unless I'm missing something or was not able to reproduce it properly. Do you have a small snippet reproducing the issue to confirm?

**Comment by zhanghai** [comment]
Sorry for the late reply, I've been too busy with my day job last month. I'm still reproducing this on 3.0.1 and I dont' think I had this in 3.0.0 betas. I'll try your code with my audio file later, and let you know if I can reproduce.

**Comment by soywiz** [comment]
I haven’t tried with OGG. Not sure right now if the JS version support what the browser supports, but for the JVM target for example, only MP3 and WAV are directly supported.
So please, if you can reproduce it, can you share a snippet and a small ogg file reproducing the issue?

**Comment by zhanghai** [comment]
OK I reproduced it, but sorry I got the file format wrong, it was indeed MP3 - I converted my audio files to MP3 one month ago and I forgot about it myself :/

The sample code you provided worked fine, but as soon as I changed `readSound()` to `readMusic()`, i.e. with `streaming = true`, `SoundChannel.playingOrPaused` became always `true` even after the audio file finished playing.

**Comment by soywiz** [comment]
Oh I see, thanks for the clarification. I will check reading it in the straming mode

**Comment by soywiz** [comment]
All the audio API was reimplemened in korlibs-6.0.0-beta1 with most bugs fixed. Hopefully working fine now.
