### ISSUE TITLE
runJs: When webpage is opened on mobile, tapping on UITextInput does not open up the keyboard.

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge#880]

**Comment by Kietyo** [comment]
Video showing what I'm talking about: https://www.youtube.com/watch?v=8rrcf2eKOyc&ab_channel=XenoTactic

**Comment by soywiz** [comment]
Yes. That's expected. It is not implemented in JS. I will try to implement it for 3.0, or 3.1 if I don't have enough time for the release.
