### ISSUE TITLE
Support editable text area / text field

### ISSUE THREAD

**Issue by RezMike** [korlibs/korge#91]

**Comment by RezMike** [comment]
I could implement it on korge level. But I need an initial support for that on korgw level from you @soywiz.

**Comment by soywiz** [comment]
Depends on https://github.com/korlibs/korgw/issues/23
Depends on https://github.com/korlibs/korgw/issues/34

**Comment by soywiz** [comment]
Tested on:

* [x] JVM
* [x] K/N Win32
* [x] Android
* [ ] JS
* [ ] Linux
* [ ] MacOS
* [ ] iOS

**Comment by soywiz** [comment]
For linux:
* https://stackoverflow.com/questions/43004441/how-to-get-unicode-input-from-xcb-without-further-ado
* http://www.xfree86.org/current/Xutf8LookupString.3.html
* https://docs.oracle.com/cd/E19455-01/806-2914/xtxlib-11/index.html
