### ISSUE TITLE
Create Dokka documentation for all modules

### ISSUE THREAD

**Issue by PlanexDev** [korlibs/korge#915]
I think that having [Dokka](https://kotlin.github.io/dokka/1.6.0/) documentation for all modules (especially the core `korge` module) could be helpful, as we won't need to manually parse the in-code documentation.

**Comment by soywiz** [comment]
https://dokka.korge.org/korge/korge/

**Comment by PlanexDev** [comment]
Oh, sorry, didn't see that.
