### ISSUE TITLE
RunJS Build gets pixalated in smaller sizes after uploaded

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#92]
I started my [candy-crush-clone](https://github.com/TobseF/Candy-Crush-Clone) with `runJS` and resized the browser window to a small size of 949x644:

### Localhost  949x644
![2020-02-26_23h08_16](https://user-images.githubusercontent.com/1190109/75393612-bd52c380-58ee-11ea-9fb7-9f0b96b604de.png)
Then I uploaded the conntets of the `build/web` folder with my FileZille on my FTP. Reopened the site with the same small resolution and get:

### Online  949x644
![2020-02-26_23h08_13](https://user-images.githubusercontent.com/1190109/75393609-bb890000-58ee-11ea-8b11-c485e52dfd42.png)

**Browser Window:** 949x644 **Viewport:** 949x564 

The problem is, that my mobile also shows it in this pixalated version. 

I made several tests with different versions, all become bury after upload und resized to a small browser size:

* http://tobsefritz.de/java/candy/runjs/
* http://tobsefritz.de/java/candy/web/
* http://tobsefritz.de/java/candy/webmin/
* http://tobsefritz.de/java/candy/no-sound/
* http://tobsefritz.de/java/candy/new/

I have no idea why the game renders different on my local machine and on the web.
I cleared be target folder before I run  `runJS`, to make sure I uploaded the correct files.
Any idea what's going wrong?

**Comment by soywiz** [comment]
You have to specify `Korge(..., quality = GameWindow.Quality.QUALITY)` so the JS target uses `devicePixelRatio`. I will probably change the default to QUALITY in a future version.

Check the patch here:
https://github.com/soywiz/Candy-Crush-Clone/commit/b260dfe1a8e1f708e20f1eec38d9c2ee5849c4c2
