### ISSUE TITLE
There are many test files in the assets directory of apk when i update korge-dragonbones to 3.0.0

### ISSUE THREAD

**Issue by yunlinos** [korlibs/korge#921]
There are many test files in the assets directory of apk when i dependency com.soywiz.korlibs.korge2:korge-dragonbones:3.0.0, but the 3.0.0-Beta5 version does not have these files. These files are very large and greatly affect the size of the apk.

![image](https://user-images.githubusercontent.com/19150644/182757155-9b29a2a1-0283-4857-9032-4a1c995f8674.png)

**Comment by soywiz** [comment]
This artifact doesn't seem to include those files:
https://search.maven.org/remotecontent?filepath=com/soywiz/korlibs/korge2/korge-dragonbones-jvm/3.0.0/korge-dragonbones-jvm-3.0.0.jar

Not included here either: https://search.maven.org/remotecontent?filepath=com/soywiz/korlibs/korim/korim-jvm/3.0.0/korim-jvm-3.0.0.jar

The `dice.qoi` file is in the `commonTest` resources folder that shouldn't be included in the korim artifact either:
https://github.com/korlibs/korge/blob/f448b148c5d1da60e32359df03538f1ecf118473/korim/src/commonTest/resources/dice.qoi

Can you reproduce it with a small project so we can check?

**Comment by soywiz** [comment]
Likely fixed here: https://github.com/korlibs/korge/issues/1065 & https://github.com/korlibs/korge/pull/1068
