### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by Anivie** [korlibs/korge#926]
I found that this program seems to be leaking memory then I try to runNativeRelease.

When it first started, the memory usage was about 30mb, but after minimizing or repeatedly minimizing, the memory continued to increase at a speed of 20m per second until it crashed,i can't find any error message in console(only a ERROR: 127),how can i fix it?

**Comment by soywiz** [comment]
@Anivie can you share the code that is producing the leak so we can try to reproduce the issue?
