### ISSUE TITLE
unresolved reference: soywiz

### ISSUE THREAD

**Issue by monyettenyom** [korlibs/korge#941]
Hallo,

I'm using IntelliJ Ultimate 2022.1, Korge Version 3.0.0. I created a project with template Codes from the plugin installed on the IDE. I tried running the gradle build and I got these errors:

![Bildschirmfoto 2022-08-25 um 13 49 13](https://user-images.githubusercontent.com/58295352/186657314-f0d44261-4534-46fe-a22c-99d10d04b5f8.png)

![Bildschirmfoto 2022-08-25 um 13 49 19](https://user-images.githubusercontent.com/58295352/186657342-18e548bd-6805-4471-ae99-deea367df55e.png)

my build.gradle.kts looks like this:

![Bildschirmfoto 2022-08-25 um 13 48 52](https://user-images.githubusercontent.com/58295352/186657741-60f7e089-f361-4064-abe3-f3c0edc3de6e.png)

Please help. Thanks

**Comment by soywiz** [comment]
That file shouldn't be generated with the latest intellij plugin. The file should look like this one:
https://github.com/korlibs/korge-hello-world/blob/87aed7e99113ebfaac3da6fc9c3a67a345728493/build.gradle.kts

If for some reason the intellij plugin is not working for you, you can download the hello-world repo and open that project instead. Here's a zip with that repo: https://github.com/korlibs/korge-hello-world/archive/main.zip
