### ISSUE TITLE
Bug(KorTE): String with newline-character breaks table in Template

### ISSUE THREAD

**Issue by SoftMachina** [korlibs/korge#955]
Version: KorTE 2.7.0

Sometimes when creating a table, I want to have a column for text. The problem arises, if the text contains a newline. It breaks the table. 

Example: 
"100g of flour
2 eggs
50g of sugar"

Something like that breaks the table.

My current Workaround is to convert this `String` into a `List<String>` using Kotlin's `fun CharSequence.lines(): List<String>` and then, in my template, I iterate using a `{% for -%}`-loop, to create a List inside the table column.

**Comment by SoftMachina** [comment]
It also breaks with KorTE 3.0

**Comment by soywiz** [comment]
@SoftMachina I need some more context:

1. What do you mean by create a table?
2. Which kind of content are you generating? I suspect you are not generating HTML.
3. How would be a good output if the text contains a new line?

**Comment by SoftMachina** [comment]
Thank you for the fast response, 
1 & 2. I'm trying to generate a HTML-table. I first define a header like:
 `| recipe name | ingredients | some other property |` and `| ---- | ------ | ----|`. This generates the table header for me. I then create the columns like: `| {{r.name}} | {{r.ingredients}} | {{r.something}}`
the ingredients contain what I initially mentioned, a String containing a new line. This breaks the HTML-table. 

It should however, just display the text, including the new line in the table column.
3. I think replacing newlines with a `<br>` would be good. It should look something like this: 
`<table style="border-collapse: collapse;">
   <thead>
      <tr>
         <th style="padding: 10px; border: 1px solid black;">recipe name</th>
         <th style="padding: 10px; border: 1px solid black;">ingredients</th>
         <th style="padding: 10px; border: 1px solid black;">something</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td style="padding: 10px; border: 1px solid black;">cookies</td>
         <td style="padding: 10px; border: 1px solid black;">100g flour <br> 2 eggs <br> 50g sugar</td>
         <td style="padding: 10px; border: 1px solid black;">some other info</td>
      </tr>
      <tr>
         <td style="padding: 10px; border: 1px solid black;">pizza</td>
         <td style="padding: 10px; border: 1px solid black;">500g flour <br> 2g fresh yeast <br> 600ml water</td>
         <td style="padding: 10px; border: 1px solid black;">other info</td>
      </tr>
   </tbody>
</table>`

But instead i get: `<table style="border-collapse: collapse;">
   <thead>
      <tr>
         <th style="padding: 10px; border: 1px solid black;">recipe name</th>
         <th style="padding: 10px; border: 1px solid black;">ingredients</th>
         <th style="padding: 10px; border: 1px solid black;">something</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td style="padding: 10px; border: 1px solid black;">cookies</td>
         <td style="padding: 10px; border: 1px solid black;">100g flour</td>
      </tr>
      </tbody>
</table>
<p>2 eggs || 50g sugar |  |some other info ... and so on</p>`

**Comment by SoftMachina** [comment]
Thank you very much :)

**Comment by soywiz** [comment]
I have created: https://github.com/korlibs/korge/issues/956
