### ISSUE TITLE
[klock] clarify that DateTime.fromUnix takes milliseconds instead of seconds

### ISSUE THREAD

**Issue by MinmoTech** [korlibs/korge#959]
Currently `DateTime.fromUnix()` takes a timestamp in milliseconds but with just the name `fromUnix` I would have expected it to use seconds instead.

I would recommend to rename this function to `fromUnixMilliseconds` and maybe to additionally add the function `fromUnixSeconds`.

**Comment by soywiz** [comment]
Yeah, makes sense: in PHP, Python and C I believe unix are in seconds. While in Java and JS it is in milliseconds.
Can you make a PR? Maybe the method can be deprecated and suggest a replacement to use `fromUnixMilliseconds` instead

**Comment by Kietyo** [comment]
fixed
