### ISSUE TITLE
Shaders support

### ISSUE THREAD

**Issue by i-d-c-p** [korlibs/korge#96]
Is there any plan to support shaders? I'm really exciting about this framework and I'm about porting some experimental LibGdx games here but the lack of shaders could be a problem.

**Comment by soywiz** [comment]
There are shaders already:

https://github.com/korlibs/korge/blob/ff21596f9bbd69dc3eae15c1a843f2719a3da695/korge/src/commonMain/kotlin/com/soywiz/korge/view/filter/ShaderFilter.kt#L48-L62

https://github.com/korlibs/korge/blob/ff21596f9bbd69dc3eae15c1a843f2719a3da695/korge/src/commonMain/kotlin/com/soywiz/korge/view/filter/WaveFilter.kt#L61-L69

Or do you mean GLSL shaders? What I did was a DSL to create shaders, so I can generate either GLSL or Metal or DirectX shaders transparently. You have to add shaders programmatically right now. But I could add a GLSL parser that generates that DSL transparently, but that's not in the current roadmap.

If you want to do use GLSL right now it in a hacky way. You can cast the AG instance into an AGOpengl instance:
https://github.com/korlibs/korgw/blob/00cd871ef72dbf10fcce43b65842e058fc394f11/korgw/src/commonMain/kotlin/com/soywiz/korag/OpenglAG.kt

Then get the `abstract val gl: KmlGl` instance: https://github.com/korlibs/korgw/blob/00cd871ef72dbf10fcce43b65842e058fc394f11/korgw/src/commonMain/kotlin/com/soywiz/kgl/IKmlGl.kt
There you have raw OpenGL/OpenGL|ES calls.

But I'd suggest you to use the DSL instead for now. And if you really want a GLSL parser support, issue a feature request here: https://github.com/korlibs/korgw/issues

**Comment by i-d-c-p** [comment]
Thanks man, I'm going to give a try to that DSL to create shaders, it sounds awesome.

**Comment by soywiz** [comment]
Nice. Feel free to join our slack https://slack.soywiz.com/ or open an issue if you have issues with it
