### ISSUE TITLE
Problems with blending in FSprites

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korge#965]
Hello,
after updating korge to 3.0 I noticed transparent images stopped to render properly with FSprites. The issue seems to be related to premultiplied images.

korge 2.0 / korge 3.0:
<p float="left">
  <img src="https://user-images.githubusercontent.com/9904421/188312685-a530e5ab-4847-45de-9dd0-d0823fec393f.png" width="35%" />
  <img src="https://user-images.githubusercontent.com/9904421/188312698-28c87619-c744-4b59-bc7f-2e1619d7575f.png" width="35%" />
</p>

If I comment [this line](https://github.com/korlibs/korge/blob/2b0cba9c76441171b82f0135362f4ba472cf4453/korge/src/commonMain/kotlin/com/soywiz/korge/view/fast/FSprites.kt#L274) in FSprites, it starts to work as expected.

Don't understand the details about this function though 
![image](https://user-images.githubusercontent.com/9904421/188312756-8350ed30-b858-42c2-8593-0ba28497f6b1.png)

**Comment by soywiz** [comment]
This should be fixed now. Now all the textures are expected to be premultiplied.
