### ISSUE TITLE
Ninepatch image get streched

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#97]
I created a nine-patch image and added it with:
``` kotlin
val ninePath = resourcesVfs["images/$fileName"].readNinePatch()
 view.ninePatch(ninePath , 450.0, 600.0) {
   position(120, 400.0)
}
``` 
The image has a size of 127 x 95, so it should expand and not get streched with a 450 x 600 render size.
I also checked the IDE... the korge plugin also shows that the nine-patch should work:
![2020-03-06_11h49_38](https://user-images.githubusercontent.com/1190109/76077519-24344480-5fa1-11ea-914c-99bc9dcb05c5.png)

But instead, its gets streched in my game. You can even see the black borders:
![2020-03-06_11h53_31](https://user-images.githubusercontent.com/1190109/76077584-43cb6d00-5fa1-11ea-9e49-538be7de6352.png)

So the korge IDE plugin parses the image in a different way, than Korge itself.

This is the image file:
![button 9](https://user-images.githubusercontent.com/1190109/76077692-81c89100-5fa1-11ea-9e92-d1ffec2ad64b.png)

**Comment by soywiz** [comment]
Fixed in 1.14.0.0.
You can try this sample: https://github.com/korlibs/korge-samples/blob/master/ninepatch/src/commonMain/kotlin/main.kt
