### ISSUE TITLE
Could not resolve com.soywiz.korlibs.korim:korim:3.0.1.

### ISSUE THREAD

**Issue by aimdie** [korlibs/korge#981]
Could not resolve com.soywiz.korlibs.korim:korim:3.0.1.

**Comment by soywiz** [comment]
Please, check the repositories you have registered. It seems that the artifact is available:

* https://search.maven.org/remotecontent?filepath=com/soywiz/korlibs/korim/korim/3.0.1/korim-3.0.1.jar
* https://search.maven.org/artifact/com.soywiz.korlibs.korim/korim/3.0.1/jar

**Comment by aimdie** [comment]
these are my repositories  in settings , Am I missing something?

allprojects {
  repositories {
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    google()
    mavenCentral()
    mavenLocal()
  }
}
